using RichnessSoft.Entity.Class;
using RichnessSoft.Entity.Model;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
namespace RichnessSoft.Data
{
    public static class initCountry
    {
        public static void InitializeAsync(RicnessDbContext context
            , RichnessLogDbContext contextlog
            , SuperAdminDefaultOptions superAdminDefaultOptions)
        {
            List<postalCountry> Listpostalcountry = new List<postalCountry>()
            {
                new postalCountry { code = "00", code2 = "000", name = "<ไม่ระบุประเทศ>", name2 = "<ColorNot Define>", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "AA", code2 = "ABW", name = "อารูบา", name2 = "Aruba", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "AC", code2 = "ATG", name = "แอนติกาและบาร์บูดา", name2 = "Antigua and Barbuda", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "AF", code2 = "AFG", name = "อัฟกานิสถาน", name2 = "Afghanistan", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "AG", code2 = "DZA", name = "แอลจีเรีย", name2 = "Algeria", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "AJ", code2 = "AZE", name = "อาเซอร์ไบจาน", name2 = "Azerbaijan", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "AL", code2 = "ALB", name = "แอลเบเนีย", name2 = "Albania", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "AM", code2 = "ARM", name = "อาร์เมเนีย", name2 = "Armenia", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "AN", code2 = "AND", name = "อันดอร์รา", name2 = "Andorra", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "AO", code2 = "AGO", name = "แองโกลา", name2 = "Angola", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "AQ", code2 = "ASM", name = "อเมริกันซามัว", name2 = "American Samoa", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "AR", code2 = "ARG", name = "อาร์เจนตินา", name2 = "Argentina", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "AS", code2 = "AUS", name = "ออสเตรเลีย", name2 = "Australia", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "AU", code2 = "AUT", name = "ออสเตรีย", name2 = "Austria", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "AV", code2 = "AIA", name = "แองกวิลลา", name2 = "Anguilla", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "AY", code2 = "ATA", name = "แอนตาร์กติกา", name2 = "Antarctica", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "BA", code2 = "BHR", name = "บาห์เรน", name2 = "Bahrain", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "BB", code2 = "BRB", name = "บาร์เบโดส", name2 = "Barbados", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "BC", code2 = "BWA", name = "บอตสวานา", name2 = "Botswana", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "BD", code2 = "BMU", name = "เบอร์มิวดา", name2 = "Bermuda", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "BE", code2 = "BEL", name = "เบลเยี่ยม", name2 = "Belgium", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "BF", code2 = "BHS", name = "บาฮามาส", name2 = "Bahamas, The", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "BG", code2 = "BGD", name = "บังกลาเทศ", name2 = "Bangladesh", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "BH", code2 = "BLZ", name = "เบลีซ", name2 = "Belize", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "BK", code2 = "BIH", name = "บอสเนียและเฮอร์เซโก", name2 = "Bosnia and Herzegovina", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "BL", code2 = "BOL", name = "โบลิเวีย", name2 = "Bolivia", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "BM", code2 = "MMR", name = "เมียนมาร์ (พม่า)", name2 = "Myanmar (Burma)", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "BN", code2 = "BEN", name = "เบนิน", name2 = "Benin", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "BO", code2 = "BLR", name = "เบลารุส", name2 = "Belarus", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "BP", code2 = "SLB", name = "หมู่เกาะโซโลมอน", name2 = "Solomon Islands", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "BR", code2 = "BRA", name = "บราซิล", name2 = "Brazil", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "BT", code2 = "BTN", name = "ภูฏาน", name2 = "Bhutan", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "BU", code2 = "BGR", name = "บัลแกเรีย", name2 = "Bulgaria", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "BV", code2 = "NOR", name = "เกาะบูเวต", name2 = "Bouvet Island", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "BX", code2 = "BRN", name = "บรูไน", name2 = "Brunei", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "BY", code2 = "BDI", name = "บุรุนดี", name2 = "Burundi", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "CA", code2 = "CAN", name = "แคนาดา", name2 = "Canada", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "CB", code2 = "KHM", name = "กัมพูชา", name2 = "Cambodia", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "CD", code2 = "TCD", name = "ชาด", name2 = "Chad", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "CE", code2 = "LKA", name = "ศรีลังกา", name2 = "Sri Lanka", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "CF", code2 = "COG", name = "คองโก", name2 = "Congo", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "CG", code2 = "ZAR", name = "ซาอีร์", name2 = "Zaire", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "CH", code2 = "CHN", name = "ประเทศจีน", name2 = "China", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "CI", code2 = "CHL", name = "ชิลี", name2 = "Chile", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "CJ", code2 = "CYM", name = "หมู่เกาะเคย์แมน", name2 = "Cayman Islands", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "CK", code2 = "CCK", name = "หมู่เกาะโคโคส (คีลิง)", name2 = "Cocos (Keeling) Islands", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "CM", code2 = "CMR", name = "แคเมอรูน", name2 = "Cameroon", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "CN", code2 = "COM", name = "คอโมโรส", name2 = "Comoros", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "CO", code2 = "COL", name = "โคลอมเบีย", name2 = "Colombia", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "CQ", code2 = "MNP", name = "หมู่เกาะนอร์เทิร์นมาเรียนา", name2 = "Northern Mariana Islands", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "CS", code2 = "CRI", name = "คอสตาริกา", name2 = "Costa Rica", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "CT", code2 = "CAF", name = "สาธารณรัฐแอฟริกากลาง", name2 = "Central African Republic", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "CU", code2 = "CUB", name = "คิวบา", name2 = "Cuba", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "CV", code2 = "CPV", name = "เคปเวิร์ด", name2 = "Cape Verde", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "CW", code2 = "COK", name = "หมู่เกาะคุก", name2 = "Cook Islands", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "CY", code2 = "CYP", name = "ไซปรัส", name2 = "Cyprus", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "DA", code2 = "DNK", name = "เดนมาร์ก", name2 = "Denmark", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "DJ", code2 = "DJI", name = "จิบูตี", name2 = "Djibouti", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "DO", code2 = "DMA", name = "โดมินิกา", name2 = "Dominica", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "DQ", code2 = "UMI", name = "เกาะจาร์วิส", name2 = "Jarvis Island", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "DR", code2 = "DOM", name = "สาธารณรัฐโดมินิกัน", name2 = "Dominican Republic", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "EC", code2 = "ECU", name = "เอกวาดอร์", name2 = "Ecuador", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "EG", code2 = "EGY", name = "อียิปต์", name2 = "Egypt", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "EI", code2 = "IRL", name = "ไอร์แลนด์", name2 = "Ireland", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "EK", code2 = "GNQ", name = "อิเควทอเรียลกินี", name2 = "Equatorial Guinea", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "EN", code2 = "EST", name = "เอสโตเนีย", name2 = "Estonia", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "ER", code2 = "ERI", name = "เอริเทรีย", name2 = "Eritrea", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "ES", code2 = "SLV", name = "เอลซัลวาดอร์", name2 = "El Salvador", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "ET", code2 = "ETH", name = "เอธิโอเปีย", name2 = "Ethiopia", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "EZ", code2 = "CZE", name = "สาธารณรัฐเช็ก", name2 = "Czech Republic", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "FG", code2 = "GUF", name = "เฟรนช์เกีย", name2 = "French Guiana", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "FI", code2 = "FIN", name = "ฟินแลนด์", name2 = "Finland", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "FJ", code2 = "FJI", name = "ฟิจิ", name2 = "Fiji", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "FK", code2 = "FLK", name = "หมู่เกาะฟอล์กแลนด์ (Islas Malvinas)", name2 = "Falkland Islands (Islas Malvinas)", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "FM", code2 = "FSM", name = "สหพันธรัฐไมโครนีเซีย", name2 = "Federated States of Micronesia", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "FO", code2 = "FRO", name = "หมู่เกาะแฟโร", name2 = "Faroe Islands", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "FP", code2 = "PYF", name = "เฟรนช์โปลินีเซีย", name2 = "French Polynesia", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "FQ", code2 = "UMI", name = "เกาะเบเกอร์", name2 = "Baker Island", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "FR", code2 = "FRA", name = "ฝรั่งเศส", name2 = "France", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "FS", code2 = "ATF", name = "ดินแดนทางตอนใต้และแอนตาร์กติกของฝรั่งเศส", name2 = "French Southern & Antarctic Lands", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "GA", code2 = "GMB", name = "แกมเบีย, The", name2 = "Gambia, The", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "GB", code2 = "GAB", name = "กาบอง", name2 = "Gabon", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "GG", code2 = "GEO", name = "จอร์เจีย", name2 = "Georgia", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "GH", code2 = "GHA", name = "กานา", name2 = "Ghana", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "GI", code2 = "GIB", name = "ยิบรอลตาร์", name2 = "Gibraltar", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "GJ", code2 = "GRD", name = "เกรนาดา", name2 = "Grenada", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "GK", code2 = "XGK", name = "เกิร์นซีย์", name2 = "Guernsey", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "GL", code2 = "GRL", name = "กรีนแลนด์", name2 = "Greenland", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "GM", code2 = "DEU", name = "เยอรมนี", name2 = "Germany", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "GO", code2 = "REU", name = "หมู่เกาะกลอริโอโซ", name2 = "Glorioso Islands", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "GP", code2 = "GLP", name = "กวาเดอลูป", name2 = "Guadeloupe", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "GQ", code2 = "GUM", name = "กวม", name2 = "Guam", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "GR", code2 = "GRC", name = "กรีซ", name2 = "Greece", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "GT", code2 = "GTM", name = "กัวเตมาลา", name2 = "Guatemala", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "GV", code2 = "GIN", name = "กินี", name2 = "Guinea", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "GY", code2 = "GUY", name = "กายอานา", name2 = "Guyana", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "GZ", code2 = "ISR", name = "ฉนวนกาซา", name2 = "Gaza Strip", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "HA", code2 = "HTI", name = "เฮติ", name2 = "Haiti", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "HM", code2 = "HMD", name = "เกาะเฮิร์ดและหมู่เกาะแมคโดนัลด์", name2 = "Heard Island & McDonald Islands", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "HO", code2 = "HND", name = "ฮอนดูรัส", name2 = "Honduras", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "HQ", code2 = "UMI", name = "เกาะฮาวแลนด์", name2 = "Howland Island", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "HR", code2 = "HRV", name = "โครเอเชีย", name2 = "Croatia", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "HU", code2 = "HUN", name = "ฮังการี", name2 = "Hungary", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "IC", code2 = "ISL", name = "ไอซ์แลนด์", name2 = "Iceland", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "ID", code2 = "IDN", name = "อินโดนีเซีย", name2 = "Indonesia", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "IM", code2 = "XIM", name = "ไอล์ออฟแมน", name2 = "Isle of Man", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "IN", code2 = "IND", name = "อินเดีย", name2 = "India", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "IO", code2 = "IOT", name = "บริติชอินเดียนโอเชียนเทร์ริทอรี", name2 = "British Indian Ocean Territory", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "IR", code2 = "IRN", name = "อิหร่าน", name2 = "Iran", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "IS", code2 = "ISR", name = "อิสราเอล", name2 = "Israel", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "IT", code2 = "ITA", name = "อิตาลี", name2 = "Italy", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "IV", code2 = "CIV", name = "ไอวอรีโคสต์", name2 = "Ivory Coast", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "IZ", code2 = "IRQ", name = "อิรัก", name2 = "Iraq", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "JA", code2 = "JPN", name = "ญี่ปุ่น", name2 = "Japan", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "JE", code2 = "XJE", name = "เจอร์ซี", name2 = "Jersey", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "JM", code2 = "JAM", name = "จาเมกา", name2 = "Jamaica", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "JN", code2 = "SJM", name = "สฟาลบาร์และยานไมเอน", name2 = "Svalbard and Jan Mayen", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "JO", code2 = "JOR", name = "จอร์แดน", name2 = "Jordan", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "JQ", code2 = "UMI", name = "จอห์นสตันอะทอลล์", name2 = "Johnston Atoll", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "JU", code2 = "REU", name = "เกาะฮวนเดอโนวา", name2 = "Juan De Nova Island", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "KE", code2 = "KEN", name = "เคนยา", name2 = "Kenya", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "KG", code2 = "KGZ", name = "คีร์กีซสถาน", name2 = "Kyrgyzstan", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "KN", code2 = "PRK", name = "เกาหลีเหนือ", name2 = "North Korea", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "KR", code2 = "KIR", name = "คิริบาส", name2 = "Kiribati", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "KS", code2 = "KOR", name = "เกาหลีใต้", name2 = "South Korea", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "KT", code2 = "CXR", name = "เกาะคริสต์มาส", name2 = "Christmas Island", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "KU", code2 = "KWT", name = "คูเวต", name2 = "Kuwait", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "KZ", code2 = "KAZ", name = "คาซัคสถาน", name2 = "Kazakhstan", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "LA", code2 = "LAO", name = "ลาว", name2 = "Laos", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "LE", code2 = "LBN", name = "เลบานอน", name2 = "Lebanon", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "LG", code2 = "LVA", name = "ลัตเวีย", name2 = "Latvia", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "LH", code2 = "LTU", name = "ลิทัวเนีย", name2 = "Lithuania", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "LI", code2 = "LBR", name = "ไลบีเรีย", name2 = "Liberia", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "LO", code2 = "SVK", name = "สโลวาเกีย", name2 = "Slovakia", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "LS", code2 = "LIE", name = "ลิกเตนสไตน์", name2 = "Liechtenstein", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "LT", code2 = "LSO", name = "เลโซโท", name2 = "Lesotho", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "LU", code2 = "LUX", name = "ลักเซมเบิร์ก", name2 = "Luxembourg", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "LY", code2 = "LBY", name = "ลิเบีย", name2 = "Libya", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "MA", code2 = "MDG", name = "มาดากัสการ์", name2 = "Madagascar", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "MB", code2 = "MTQ", name = "มาร์ตินีก", name2 = "Martinique", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "MC", code2 = "MAC", name = "มาเก๊า", name2 = "Macau", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "MD", code2 = "MDA", name = "มอลโดวา", name2 = "Moldova", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "MF", code2 = "MYT", name = "มายอต", name2 = "Mayotte", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "MG", code2 = "MNG", name = "มองโกเลีย", name2 = "Mongolia", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "MH", code2 = "MSR", name = "มอนต์เซอร์รัต", name2 = "Montserrat", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "MI", code2 = "MWI", name = "มาลาวี", name2 = "Malawi", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "MK", code2 = "MKD", name = "มาซิโดเนีย", name2 = "Macedonia", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "ML", code2 = "MLI", name = "มาลี", name2 = "Mali", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "MN", code2 = "MCO", name = "โมนาโก", name2 = "Monaco", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "MO", code2 = "MAR", name = "โมร็อกโก", name2 = "Morocco", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "MP", code2 = "MUS", name = "มอริเชียส", name2 = "Mauritius", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "MQ", code2 = "UMI", name = "หมู่เกาะมิดเวย์", name2 = "Midway Islands", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "MR", code2 = "MRT", name = "มอริเตเนีย", name2 = "Mauritania", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "MT", code2 = "MLT", name = "มอลตา", name2 = "Malta", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "MU", code2 = "OMN", name = "โอมาน", name2 = "Oman", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "MV", code2 = "MDV", name = "มัลดีฟส์", name2 = "Maldives", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "MW", code2 = "MON", name = "มอนเตเนโกร", name2 = "Montenegro", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "MX", code2 = "MEX", name = "เม็กซิโก", name2 = "Mexico", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "MY", code2 = "MYS", name = "มาเลเซีย", name2 = "Malaysia", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "MZ", code2 = "MOZ", name = "โมซัมบิก", name2 = "Mozambique", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "NC", code2 = "NCL", name = "นิวแคลิโดเนีย", name2 = "New Caledonia", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "NE", code2 = "NIU", name = "นีอูเอ", name2 = "Niue", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "NF", code2 = "NFK", name = "เกาะนอร์ฟอล์ก", name2 = "Norfolk Island", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "NG", code2 = "NER", name = "ไนเจอร์", name2 = "Niger", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "NH", code2 = "VUT", name = "วานูอาตู", name2 = "Vanuatu", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "NI", code2 = "NGA", name = "ไนจีเรีย", name2 = "Nigeria", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "NL", code2 = "NLD", name = "เนเธอร์แลนด์", name2 = "Netherlands", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "NO", code2 = "NOR", name = "นอร์เวย์", name2 = "Norway", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "NP", code2 = "NPL", name = "เนปาล", name2 = "Nepal", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "NR", code2 = "NRU", name = "นาอูรู", name2 = "Nauru", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "NS", code2 = "SUR", name = "ซูรินาเม", name2 = "Suriname", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "NT", code2 = "ANT", name = "เนเธอร์แลนด์", name2 = "Netherlands Antilles", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "NU", code2 = "NIC", name = "นิการากัว", name2 = "Nicaragua", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "NZ", code2 = "NZL", name = "นิวซีแลนด์", name2 = "New Zealand", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "PA", code2 = "PRY", name = "ประเทศปารากวัย", name2 = "Paraguay", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "PC", code2 = "PCN", name = "หมู่เกาะพิตแคร์น", name2 = "Pitcairn Islands", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "PE", code2 = "PER", name = "เปรู", name2 = "Peru", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "PF", code2 = "XPF", name = "หมู่เกาะพาราเซล", name2 = "Paracel Islands", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "PG", code2 = "XPG", name = "หมู่เกาะสแปรตลี", name2 = "Spratly Islands", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "PK", code2 = "PAK", name = "ปากีสถาน", name2 = "Pakistan", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "PL", code2 = "POL", name = "โปแลนด์", name2 = "Poland", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "PM", code2 = "PAN", name = "ปานามา", name2 = "Panama", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "PO", code2 = "PRT", name = "โปรตุเกส", name2 = "Portugal", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "PP", code2 = "PNG", name = "ปาปัวนิวกินี", name2 = "Papua New Guinea", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "PS", code2 = "PLW", name = "หมู่เกาะแปซิฟิก (ปาเลา)", name2 = "Pacific Islands (Palau)", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "PU", code2 = "GNB", name = "กินี-บิสเซา", name2 = "Guinea-Bissau", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "QA", code2 = "QAT", name = "กาตาร์", name2 = "Qatar", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "RE", code2 = "REU", name = "เรอูนียง", name2 = "Reunion", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "RM", code2 = "MHL", name = "หมู่เกาะมาร์แชลล์", name2 = "Marshall Islands", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "RO", code2 = "ROM", name = "โรมาเนีย", name2 = "Romania", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "RP", code2 = "PHL", name = "ฟิลิปปินส์", name2 = "Philippines", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "RQ", code2 = "PRI", name = "เปอร์โตริโก้", name2 = "Puerto Rico", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "RS", code2 = "RUS", name = "รัสเซีย", name2 = "Russia", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "RW", code2 = "RWA", name = "รวันดา", name2 = "Rwanda", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "SA", code2 = "SAU", name = "ซาอุดิอาราเบีย", name2 = "Saudi Arabia", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "SB", code2 = "SPM", name = "เซนต์ปิแอร์และมีเกอลง", name2 = "St. Pierre and Miquelon", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "SC", code2 = "KNA", name = "เซนต์คิตส์และเนวิส", name2 = "St. Kitts and Nevis", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "SE", code2 = "SYC", name = "เซเชลส์", name2 = "Seychelles", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "SF", code2 = "ZAF", name = "แอฟริกาใต้", name2 = "South Africa", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "SG", code2 = "SEN", name = "เซเนกัล", name2 = "Senegal", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "SH", code2 = "SHN", name = "เซนต์เฮเลนา", name2 = "St. Helena", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "SI", code2 = "SVN", name = "สโลวีเนีย", name2 = "Slovenia", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "SL", code2 = "SLE", name = "เซียร์ราลีโอน", name2 = "Sierra Leone", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "SM", code2 = "SMR", name = "ซานมาริโน", name2 = "San Marino", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "SN", code2 = "SGP", name = "สิงคโปร์", name2 = "Singapore", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "SO", code2 = "SOM", name = "โซมาเลีย", name2 = "Somalia", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "SP", code2 = "ESP", name = "สเปน", name2 = "Spain", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "SR", code2 = "SRB", name = "เซอร์เบีย", name2 = "Serbia", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "ST", code2 = "LCA", name = "เซนต์ลูเซีย", name2 = "St. Lucia", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "SU", code2 = "SDN", name = "ซูดาน", name2 = "Sudan", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "SV", code2 = "SJM", name = "สฟาลบาร์", name2 = "Svalbard", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "SW", code2 = "SWE", name = "สวีเดน", name2 = "Sweden", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "SX", code2 = "SGS", name = "เซาท์จอร์เจียและเซาท์แซนด์วิชคือ", name2 = "South Georgia and the South Sandwich Is", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "SY", code2 = "SYR", name = "ซีเรีย", name2 = "Syria", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "SZ", code2 = "CHE", name = "สวิตเซอร์แลนด์", name2 = "Switzerland", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "TC", code2 = "ARE", name = "สหรัฐอาหรับเอมิเรตส์", name2 = "United Arab Emirates", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "TD", code2 = "TTO", name = "ตรินิแดดและโตเบโก", name2 = "Trinidad and Tobago", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "TH", code2 = "THA", name = "ประเทศไทย", name2 = "Thailand", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "TI", code2 = "TJK", name = "ทาจิกิสถาน", name2 = "Tajikistan", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "TK", code2 = "TCA", name = "หมู่เกาะเติกส์และหมู่เกาะเคคอส", name2 = "Turks and Caicos Islands", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "TL", code2 = "TKL", name = "โทเคอเลา", name2 = "Tokelau", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "TN", code2 = "TON", name = "ตองกา", name2 = "Tonga", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "TO", code2 = "TGO", name = "โตโก", name2 = "Togo", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "TP", code2 = "STP", name = "เซาตูเมและปรินซิปี", name2 = "Sao Tome and Principe", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "TS", code2 = "TUN", name = "ตูนิเซีย", name2 = "Tunisia", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "TU", code2 = "TUR", name = "ไก่งวง", name2 = "Turkey", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "TV", code2 = "TUV", name = "ตูวาลู", name2 = "Tuvalu", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "TW", code2 = "TWN", name = "ไต้หวัน", name2 = "Taiwan", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "TX", code2 = "TKM", name = "เติร์กเมนิสถาน", name2 = "Turkmenistan", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "TZ", code2 = "TZA", name = "แทนซาเนียสหสาธารณรัฐ", name2 = "Tanzania, United Republic of", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "UG", code2 = "UGA", name = "ยูกันดา", name2 = "Uganda", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "UK", code2 = "GBR", name = "ประเทศอังกฤษ", name2 = "United Kingdom", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "UP", code2 = "UKR", name = "ยูเครน", name2 = "Ukraine", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "US", code2 = "USA", name = "สหรัฐ", name2 = "United States", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "UV", code2 = "BFA", name = "บูร์กินาฟาโซ", name2 = "Burkina Faso", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "UY", code2 = "URY", name = "อุรุกวัย", name2 = "Uruguay", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "UZ", code2 = "UZB", name = "อุซเบกิสถาน", name2 = "Uzbekistan", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "VC", code2 = "VCT", name = "เซนต์วินเซนต์และเกรนาดีนส์", name2 = "St. Vincent and the Grenadines", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "VE", code2 = "VEN", name = "เวเนซุเอลา", name2 = "Venezuela", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "VI", code2 = "VGB", name = "หมู่เกาะบริติชเวอร์จิน", name2 = "British Virgin Islands", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "VM", code2 = "VNM", name = "เวียดนาม", name2= "Vietnam", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "VQ", code2 = "VIR", name = "หมู่เกาะเวอร์จิน", name2 = "Virgin Islands", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "WE", code2 = "ISR", name = "เวสต์แบงก์", name2 = "West Bank", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "WF", code2 = "WLF", name = "วาลลิสและฟุตูนา", name2 = "Wallis and Futuna", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "WI", code2 = "ESH", name = "ซาฮาร่าตะวันตก", name2 = "Western Sahara", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "WQ", code2 = "UMI", name = "เกาะเวก", name2 = "Wake Island", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "WS", code2 = "WSM", name = "ซามัวตะวันตก", name2 = "Western Samoa", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "WZ", code2 = "SWZ", name = "สวาซิแลนด์", name2 = "Swaziland", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "YM", code2 = "YEM", name = "เยเมน", name2 = "Yemen", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "ZA", code2 = "ZMB", name = "แซมเบีย", name2 = "Zambia", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "ZI", code2 = "ZWE", name = "ซิมบับเว", name2 = "Zimbabwe", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now },
                new postalCountry { code = "WA", code2 = "NAM", name = "นามิเบีย", name2 = "Namibia", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now }

            };
            //foreach (postalCountry postalCountry in Listpostalcountry)
            //{
            //    context.Add(postalCountry);
            //}
            context.AddRange(Listpostalcountry.ToArray());
            context.SaveChanges();
        }
    }
}
