using System;
using System.Collections.Generic;
using System.Text;
using RichnessSoft.Entity.Class;
using RichnessSoft.Entity.Model;
using System.Linq;
using RichnessSoft.Common;

namespace RichnessSoft.Data
{
    public static class initMenu
    {
        public static void InitializeAsync(RicnessDbContext context
            , RichnessLogDbContext contextlog
            , SuperAdminDefaultOptions superAdminDefaultOptions)
        {
            IList<menu> menus = new List<menu>();

            menus.Add(new menu { code = "01-001", name = "รับคำสั่งขาย", name2 = "Sale Order", Desc1 = "", Desc2 = "", Module = "Sale Order", MenuType = "H1", parrentMenu = "01-001", path = "SO", icon = "fas fa-file-contract text-hover-primary fs-2x pr-3", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "01-002", name = "จองสินค้า", name2 = "Order", Desc1 = "", Desc2 = "", Module = "Sale Order", MenuType = "H2", parrentMenu = "01-001", path = "SO", icon = "", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "01-003", name = "บันทึกเสนอราคา", name2 = "Quotation", Desc1 = "เพิ่ม/แก้ไข ใบเสนอราคา เพื่อนำเสนอราคาให้กับลูกค้าพิจราณา", Desc2 = "Add/edit quotation", Module = "Sale Order", MenuType = "S", parrentMenu = "01-002", path = "SO/QT", icon = "fa fa-file-contract fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "01-004", name = "บันทึกสั่งขาย", name2 = "Sale Order", Desc1 = "เพิ่ม/แก้ไข ใบสั่งขาย บันทึกเมื่อลูกค้าสั่งซื้อสินค้าหรือเมื่อได้รับเอกสารใบสั่งซื้อ(PO) จากลูกค้า", Desc2 = "Add/edit sale order", Module = "Sale Order", MenuType = "S", parrentMenu = "01-002", path = "SO/SO", icon = "fa fa-file-signature fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "02-001", name = "ขายเชื่อ", name2 = "Accounts Receivable", Desc1 = "", Desc2 = "", Module = "Sale", MenuType = "H1", parrentMenu = "02-001", path = "AR", icon = "fas fa-file-invoice text-hover-primary fs-2x pr-3", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "02-002", name = "ตั้งลูกหนี้การค้า", name2 = "Sales Bill", Desc1 = "", Desc2 = "", Module = "Sale", MenuType = "H2", parrentMenu = "02-001", path = "Invoice", icon = "", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "02-003", name = "ขายเชื่อ", name2 = "Sales Invoice", Desc1 = "เพิ่ม/แก้ไข บิลขาย(ใบกำกับภาษี/ใบแจ้งหนี้/ใบส่งสินค้า) เพื่อตั้งหนี้ลูกหนี้การค้า สามารถเพิมใหม่หรือแก้ไขบิลเดิม", Desc2 = "Add/edit sales tax invoice", Module = "Sale", MenuType = "S", parrentMenu = "02-002", path = "Invoice/SOC", icon = "fa fa-file-invoice fa-3x", command = "IVS; SIV", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu
            {
                code = "02-004",
                name = "ลดหนี้",
                name2 = "Sales Credit Note",
                Desc1 = "เพิ่ม/แก้ไข ลดหนี้(ใบกำกับภาษี/ใบลดหนี้) เพื่อลดหนี้ลูกหนี้การค้าโดยกำหนดคืนสินค้าหรือคืนเงิน สามารถเพิมใหม่หรือแก้ไขบิลเดิม",
                Desc2 = "Add/edit sales credit note",
                Module = "Sale",
                MenuType = "S",
                parrentMenu = "02-002",
                path = "Invoice/CN",
                icon = "fa fa-file-download fa-3x",
                command = "SALE;CNS;SCN",
                CreateAtUtc = DateTime.Now,
                UpdateAtUtc = DateTime.Now
            });
            menus.Add(new menu
            {
                code = "02-005",
                name = "เพิ่มหนี้",
                name2 = "Sales Debit Note",
                Desc1 = "เพิ่ม/แก้ไข เพิ่มหนี้(ใบกำกับภาษี/ใบเพิ่มหนี้)เพื่อเพิ่มหนี้ลูกหนี้การค้าโดยกำหนดเพิ่มสินค้าหรือเพิ่มเงิน สามารถเพิมใหม่หรือแก้ไขบิลเดิม",
                Desc2 = "Add/edit sales debit note",
                Module = "Sale",
                MenuType = "S",
                parrentMenu = "02-002",
                path = "Invoice/DN",
                icon = "fa fa-file-upload fa-3x",
                command = "SALE;DNS;SDN",
                CreateAtUtc = DateTime.Now,
                UpdateAtUtc = DateTime.Now
            });
            menus.Add(new menu { code = "02-009", name = "เงินมัดจำรับ", name2 = "Deposit Received", Desc1 = "เพิ่ม/แก้ไข เงินมัดจำรับล่วงหน้า เพื่อตั้งหนี้ลูกหนี้เงินมัดจำรับล่วงหน้า สามารถเพิมใหม่หรือแก้ไขบิลเดิม", Desc2 = "Add/edit advance deposit receipts", Module = "Sale", MenuType = "S", parrentMenu = "02-002", path = "Invoice/DR", icon = "fa fa-file-contract fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "03-001", name = "รับชำระ", name2 = "Receipt", Desc1 = "", Desc2 = "", Module = "Receipt", MenuType = "H1", parrentMenu = "03-001", path = "Receipt", icon = "fas fa-receipt text-hover-primary fs-2x pr-3", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "03-002", name = "ขายสด", name2 = "Cash Sales bill", Desc1 = "", Desc2 = "", Module = "Receipt", MenuType = "H2", parrentMenu = "03-001", path = "Receipt", icon = "", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "03-003", name = "บิลเงินสด", name2 = "Cash Sell", Desc1 = "เพิ่ม/แก้ไข บิลขายสด(ใบกำกับภาษี/ใบเสร็จรับเงิน) เพื่อตั้งหนี้ลูกหนี้การค้า สามารถเพิมใหม่หรือแก้ไขบิลเดิม", Desc2 = "", Module = "Receipt", MenuType = "S", parrentMenu = "03-002", path = "-", icon = "fa fa-file-invoice fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "03-004", name = "ลดหนี้", name2 = "Cash Sell Credit Note", Desc1 = "เพิ่ม/แก้ไข ลดหนี้เงินสด(ใบกำกับภาษี/ใบลดหนี้/ใบเสร็จรับเงิน) เพื่อลดหนี้ลูกค้าโดยกำหนดคืนสินค้าหรือคืนเงิน สามารถเพิมใหม่หรือแก้ไขบิลเดิม", Desc2 = "", Module = "Receipt", MenuType = "S", parrentMenu = "03-002", path = "-", icon = "fa fa-file-download fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "03-005", name = "เพิ่มหนี้ ", name2 = "Cash Sell Debit Note", Desc1 = "เพิ่ม/แก้ไข เพิ่มหนี้(ใบกำกับภาษี/ใบเพิ่มหนี้/ใบเสร็จรับเงิน) เพื่อเพิ่มหนี้ลูกค้าโดยกำหนดเพิ่มสินค้าหรือเพิ่มเงิน สามารถเพิมใหม่หรือแก้ไขบิลเดิม", Desc2 = "", Module = "Receipt", MenuType = "S", parrentMenu = "03-002", path = "-", icon = "fa fa-file-upload fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "03-006", name = "รับเงินมัดจำ", name2 = "Cash Sell Deposit", Desc1 = "เพิ่ม/แก้ไข รับเงินมัดจำรับล่วงหน้า(ใบกำกับภาษี/ใบเสร็จรับเงิน) เพื่อเพิ่มหนี้ลูกค้าโดยกำหนดเพิ่มสินค้าหรือเพิ่มเงิน สามารถเพิมใหม่หรือแก้ไขบิลเดิม", Desc2 = "", Module = "Receipt", MenuType = "S", parrentMenu = "03-002", path = "-", icon = "fa fa-file-invoice-dollar fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "03-007", name = "ตามหนี้", name2 = "Cash Sales bill", Desc1 = "", Desc2 = "", Module = "Receipt", MenuType = "H2", parrentMenu = "03-001", path = "Receipt", icon = "", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "03-008", name = "ใบวางบิล", name2 = "Bill", Desc1 = "เพิ่ม/แก้ไข ใบวางบิล บันทึกเอกสารวางบิลเพื่อทำการวางบิลลูกค้าเหมือนเป็นการหนี้ลูกค้าก่อนรับชำระเงิน", Desc2 = "Add/edit bill", Module = "Receipt", MenuType = "S", parrentMenu = "03-007", path = "Bill/RL", icon = "fa fa-receipt fa-3x", command = "RBL", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "03-009", name = "สร้างใบวางบิลอัตโนมัติ", name2 = "Auto Generate billing", Desc1 = "สร้างใบวางบิลอัตโนมัติ ใช้ในกรณีต้องการให้โปรแกรม Generate Bill Auto โดยสร้างจากเงื่อนไขในการกำหนดการวางบิล", Desc2 = "", Module = "Receipt", MenuType = "S", parrentMenu = "03-007", path = "-", icon = "fa fa-file-import fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "03-010", name = "ใบเสร็จรับเงิน", name2 = "Cash Sales bill", Desc1 = "", Desc2 = "", Module = "Receipt", MenuType = "H2", parrentMenu = "03-001", path = "Receipt", icon = "", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "03-011", name = "ใบเสร็จก่อนรับเงิน", name2 = "Prepare Receipt", Desc1 = "เพิ่ม/แก้ไข ใบเสร็จ ก่อนการรับเงิน(ใบเสร็จรับเงิน) ใบเสร็จก่อนรับเงินเปรียบเสมือนการพิมพ์ใบเสร็จเพื่อนำไปเก็บเงินและให้ลูกค้า แต่ระบบยังไม่ตัดลูกหนี้การค้า เนื่องจากยังไม่ได้รับเงินจริง", Desc2 = "Add/edit prepare receipt", Module = "Receipt", MenuType = "S", parrentMenu = "03-010", path = "Receipt/RP", icon = "fa fa-file-powerpoint fa-3x", command = "RPR; RPI ", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "03-012", name = "ใบเสร็จรับเงิน", name2 = "Receipt", Desc1 = "เพิ่ม/แก้ไข ใบเสร็จรับเงิน บันทึกเมื่อมีการได้รับเงินจากลูกค้าเรียบร้อย โปรแกรมจะทำการล้างลูกหนี้การค้าออกจากระบบ ", Desc2 = "Add/edit receipt", Module = "Receipt", MenuType = "S", parrentMenu = "03-010", path = "Receipt/RE", icon = "fa fa-receipt fa-3x", command = "RRE; RIV ", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "04-001", name = "สั่งซื้อสินค้า", name2 = "Purchase Order", Desc1 = "", Desc2 = "", Module = "Purchase order", MenuType = "H1", parrentMenu = "04-001", path = "Purchase order", icon = "fas fa-file-contract text-hover-primary fs-2x pr-3", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "04-002", name = "สั่งซื้้อ", name2 = "Purchase Order", Desc1 = "", Desc2 = "", Module = "Purchase order", MenuType = "H2", parrentMenu = "04-001", path = "PO", icon = "", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "04-003", name = "ใบขอซื้อ", name2 = "Purchase Request", Desc1 = "", Desc2 = "", Module = "Purchase order", MenuType = "S", parrentMenu = "04-002", path = "-", icon = "fa fa-file-contract fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "04-004", name = "ใบสั่งซื้อ", name2 = "Purchase Order", Desc1 = "", Desc2 = "", Module = "Purchase order", MenuType = "S", parrentMenu = "04-002", path = "-", icon = "fa fa-file-signature fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "05-001", name = "ซื้้อเชื่อ", name2 = "Accounts Payable", Desc1 = "", Desc2 = "", Module = "Purchase", MenuType = "H1", parrentMenu = "05-001", path = "Purchase", icon = "fas fa-file-invoice text-hover-primary fs-2x pr-3", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "05-002", name = "ตั้งเจ้าหนี้การค้า", name2 = "Purchase Bill", Desc1 = "", Desc2 = "", Module = "Purchase", MenuType = "H2", parrentMenu = "05-001", path = "", icon = "", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "05-003", name = "ซื้อเชื่อ", name2 = "Purchase Tax Invoice", Desc1 = "", Desc2 = "", Module = "Purchase", MenuType = "S", parrentMenu = "05-002", path = "-", icon = "fa fa-file-invoice fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "05-004", name = "ลดหนี้", name2 = "Purchase Credit note", Desc1 = "", Desc2 = "", Module = "Purchase", MenuType = "S", parrentMenu = "05-002", path = "-", icon = "fa fa-file-alt fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "05-005", name = "เพิ่มหนี้", name2 = "Purchase Debit note", Desc1 = "", Desc2 = "", Module = "Purchase", MenuType = "S", parrentMenu = "05-002", path = "-", icon = "fa fa-file-upload fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "05-006", name = "เงินมัดจำจ่าย", name2 = "Advance Dposit Paid", Desc1 = "", Desc2 = "", Module = "Purchase", MenuType = "S", parrentMenu = "05-002", path = "-", icon = "fa fa-file-invoice-dollar fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "06-001", name = "จ่ายชำระ", name2 = "Payment", Desc1 = "", Desc2 = "", Module = "Payment", MenuType = "H1", parrentMenu = "06-001", path = "Payment", icon = "fas fa-receipt text-hover-primary fs-2x pr-3", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "06-002", name = "ซื้นสด", name2 = "Cash Purchase bill", Desc1 = "", Desc2 = "", Module = "Payment", MenuType = "H2", parrentMenu = "06-001", path = "", icon = "", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "06-003", name = "บิลเงินสด", name2 = "Cash Buy", Desc1 = "", Desc2 = "", Module = "Payment", MenuType = "S", parrentMenu = "06-002", path = "-", icon = "fa fa-file-invoice fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "06-004", name = "ลดหนี้ ", name2 = "Cash Buy Credit Note", Desc1 = "", Desc2 = "", Module = "Payment", MenuType = "S", parrentMenu = "06-002", path = "-", icon = "fa fa-file-alt fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "06-005", name = "เพิ่มหนี้ ", name2 = "Cash Buy Debit Note", Desc1 = "", Desc2 = "", Module = "Payment", MenuType = "S", parrentMenu = "06-002", path = "-", icon = "fa fa-file-upload fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "06-006", name = "จ่ายเงินมัดจำ", name2 = "Cash Buy Deposit", Desc1 = "", Desc2 = "", Module = "Payment", MenuType = "S", parrentMenu = "06-002", path = "-", icon = "fa fa-file-invoice-dollar fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "06-007", name = "ตามหนี้ี้", name2 = "Payment", Desc1 = "", Desc2 = "", Module = "Payment", MenuType = "H2", parrentMenu = "06-001", path = "Payment", icon = "", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "06-008", name = "รับใบวางบิล", name2 = "Billing", Desc1 = "", Desc2 = "", Module = "Payment", MenuType = "S", parrentMenu = "06-007", path = "Bill/RL", icon = "fa fa-receipt fa-3x", command = "PBL", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "06-009", name = "ใบเสร็จจ่ายชำระ", name2 = "Payment", Desc1 = "", Desc2 = "", Module = "Payment", MenuType = "H2", parrentMenu = "06-001", path = "Payment", icon = "", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "06-010", name = "ใบเสร็จก่อนการจ่ายชำระ", name2 = "Prepare Payment", Desc1 = "", Desc2 = "", Module = "Payment", MenuType = "S", parrentMenu = "06-009", path = "-", icon = "file-powerpoint fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "06-011", name = "ใบเสร็จจ่าย", name2 = "Payment Receipt", Desc1 = "", Desc2 = "", Module = "Payment", MenuType = "S", parrentMenu = "06-009", path = "-", icon = "fa fa-receipt fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });

            menus.Add(new menu { code = "07-001", name = "สินค้าคงคลัง", name2 = "Inventory", Desc1 = "", Desc2 = "", Module = "Inventory", MenuType = "H1", parrentMenu = "07-001", path = "Inventory", icon = "fas fa-boxes text-hover-primary fs-2x pr-3", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "07-002", name = "บันทึกใบรับ/ส่ง สินค้าชั่วคราว", name2 = "Delivery", Desc1 = "", Desc2 = "", Module = "Inventory", MenuType = "H2", parrentMenu = "07-001", path = "", icon = "", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "07-003", name = "ใบรับสินค้าชั่วคราว", name2 = "Delivery Order", Desc1 = "", Desc2 = "", Module = "Inventory", MenuType = "S", parrentMenu = "07-002", path = "", icon = "fa fa-file-import fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "07-004", name = "ใบสั่่งสินค้าชั่วคราว", name2 = "Goods received", Desc1 = "", Desc2 = "", Module = "Inventory", MenuType = "S", parrentMenu = "07-002", path = "", icon = "fa fa-file-export fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "07-005", name = "บันทึกการยืมสินค้า", name2 = "Borrow", Desc1 = "", Desc2 = "", Module = "Inventory", MenuType = "H2", parrentMenu = "07-001", path = "", icon = "", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "07-006", name = "ใบขอยืมสินค้า", name2 = "Product Loan Request", Desc1 = "", Desc2 = "", Module = "Inventory", MenuType = "S", parrentMenu = "07-005", path = "-", icon = "fa fa-file-contract fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "07-007", name = "ใบยืมสินค้า", name2 = "Borrowing form", Desc1 = "", Desc2 = "", Module = "Inventory", MenuType = "S", parrentMenu = "07-005", path = "-", icon = "fa fa-file-signature fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "07-008", name = "ใบคืนสินค้าจากการยืม", name2 = "Borrowing Note from loan   ", Desc1 = "", Desc2 = "", Module = "Inventory", MenuType = "S", parrentMenu = "07-005", path = "-", icon = "fa fa-file-upload fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "07-009", name = "บันทึกโอนสินค้า", name2 = "Transfer", Desc1 = "", Desc2 = "", Module = "Inventory", MenuType = "H2", parrentMenu = "07-001", path = "", icon = "", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "07-010", name = "ใบขอโอนสินค้าระหว่างคลัง", name2 = "Warehouse Transfer Requset", Desc1 = "", Desc2 = "", Module = "Inventory", MenuType = "S", parrentMenu = "07-009", path = "-", icon = "fa fa-file-code fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "07-011", name = "ใบโอนระหว่างคลัง", name2 = "Warehouse Transfer", Desc1 = "", Desc2 = "", Module = "Inventory", MenuType = "S", parrentMenu = "07-009", path = "-", icon = "fa fa-file-code fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "07-012", name = "ใบขอโอนสินค้าระหว่างสาขา", name2 = "Branch Transfer Request", Desc1 = "", Desc2 = "", Module = "Inventory", MenuType = "S", parrentMenu = "07-009", path = "-", icon = "fa fa-file-alt fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "07-013", name = "ใบโอนระหว่างสาขา", name2 = "Branch Transfer", Desc1 = "", Desc2 = "", Module = "Inventory", MenuType = "S", parrentMenu = "07-009", path = "-", icon = "fa fa-file-alt fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "07-014", name = "บันทึกเบิก/จ่ายระหว่างผลิต", name2 = "Requisition", Desc1 = "", Desc2 = "", Module = "Inventory", MenuType = "H2", parrentMenu = "07-001", path = "", icon = "", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "07-015", name = "ใบขอเบิกวัตถุดิบ", name2 = "Requisition", Desc1 = "", Desc2 = "", Module = "Inventory", MenuType = "S", parrentMenu = "07-014", path = "-", icon = "fa fa-file-code fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "07-016", name = "ใบเบิกวัตถุดิบ", name2 = "Raw material requisition", Desc1 = "", Desc2 = "", Module = "Inventory", MenuType = "S", parrentMenu = "07-014", path = "-", icon = "fa fa-file-code fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "07-017", name = "ใบรับสินค้าสำเร็จรูป", name2 = "Finished goods receipt", Desc1 = "", Desc2 = "", Module = "Inventory", MenuType = "S", parrentMenu = "07-014", path = "-", icon = "fa fa-file-alt fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "07-018", name = "บันทึกต้นทุนการผลิต", name2 = "Production Cost", Desc1 = "", Desc2 = "", Module = "Inventory", MenuType = "S", parrentMenu = "07-014", path = "-", icon = "fa fa-file-alt fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "07-019", name = "บันทึกปรับปรุงยอดสินค้า", name2 = "Adjust stock", Desc1 = "", Desc2 = "", Module = "Inventory", MenuType = "H2", parrentMenu = "07-001", path = "", icon = "", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "07-020", name = "ใบปรับยอด", name2 = "Adjust inventory", Desc1 = "", Desc2 = "", Module = "Inventory", MenuType = "S", parrentMenu = "07-019", path = "-", icon = "fa fa-stack-overflow fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "07-021", name = "ใบตรวจนับสต๊อก", name2 = "Check inventory", Desc1 = "", Desc2 = "", Module = "Inventory", MenuType = "S", parrentMenu = "07-019", path = "-", icon = "fa fa-file-image-check fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "07-022", name = "รายงานสินค้าคงเหลือ", name2 = "Inventory Report", Desc1 = "", Desc2 = "", Module = "Inventory", MenuType = "H2", parrentMenu = "07-001", path = "", icon = "", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });


            menus.Add(new menu { code = "08-001", name = "สินทรัพย์", name2 = "Fixed Asset", Desc1 = "", Desc2 = "", Module = "Asset", MenuType = "H1", parrentMenu = "08-001", path = "Asset", icon = "fas fa-building text-hover-primary fs-2x pr-3", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "08-002", name = "คำนวณ", name2 = "Generate", Desc1 = "", Desc2 = "", Module = "Asset", MenuType = "H2", parrentMenu = "08-001", path = "", icon = "", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "08-003", name = "ประมวลผลค่าเสื่อมราคา", name2 = "Generate Depreciation", Desc1 = "", Desc2 = "", Module = "Asset", MenuType = "S", parrentMenu = "08-002", path = "-", icon = "fa fa-play fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "08-004", name = "ประมวลผลเบี้ยประกันภัย", name2 = "Generate Premium", Desc1 = "", Desc2 = "", Module = "Asset", MenuType = "S", parrentMenu = "08-002", path = "-", icon = "fa fa-play fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "08-005", name = "แก้ไขมูคค่าค่าเสื่อมราคา", name2 = "Edti Depreciation", Desc1 = "", Desc2 = "", Module = "Asset", MenuType = "S", parrentMenu = "08-002", path = "-", icon = "fa fa-reply-all fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "08-006", name = "แก้ไขมูคค่าเบี้ยประกันภัย", name2 = "Edti Premius", Desc1 = "", Desc2 = "", Module = "Asset", MenuType = "S", parrentMenu = "08-002", path = "-", icon = "fa fa-repl fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "08-007", name = "บันทึกค่าซ่อมแซม", name2 = "Repair cost", Desc1 = "", Desc2 = "", Module = "Asset", MenuType = "S", parrentMenu = "08-002", path = "-", icon = "fa fa-file-contract fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "08-008", name = "ทะเบียนทรัพย์สิน", name2 = "Fax Asset Master", Desc1 = "บันทึกรายการทรัพย์สินของบริษัท", Desc2 = "Company property records", Module = "Database", MenuType = "H2", parrentMenu = "08-001", path = "Database/Fixedasset", icon = "", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "08-009", name = "ทะเบียนทรัพย์สิน", name2 = "Asset register", Desc1 = "เพิ่ม/แก้ไข รายชื่อทรัพย์สินของบริษัท เพื่อเก็บเป็นทะเบียน และใช้ในการคำนวณค่าเสื่อมราคา", Desc2 = "Add/edit the list of company assets To be registered And used to calculate depreciation", Module = "Database", MenuType = "S", parrentMenu = "08-008", path = "Database/Asset", icon = "fa fa-building fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "08-010", name = "กลุ่มทรัพย์สิน", name2 = "Asset group", Desc1 = "เพิ่ม/แก้ไข กลุ่มทรัพย์สินของบริษัท เพื่อจัดหมวดหมู่ของสินทรัยพ์ และกำหนดรหัสบัญชีให้ในกลุ่มสินทรัพย์ในการใช้คำนวณค่าเสื่อมราคา", Desc2 = "Add/Edit Group of Company Assets To categorize assets And assign an accounting code to the asset group for use in depreciation", Module = "Database", MenuType = "S", parrentMenu = "08-008", path = "Database/AssetGroup", icon = "fa fa-city fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "08-011", name = "บันทึกเบี้ยประภัย", name2 = "Insure", Desc1 = "เพิ่ม/แก้ไข เบี้ยประกันภัยของทรัพย์สิน เพื่อนำไปคำนวณ และลงบัญชีค่าใช้จ่าย", Desc2 = "Add/edit property insurance premiums To calculate And account for expenses", Module = "Database", MenuType = "S", parrentMenu = "08-008", path = "Database/Insure", icon = "fa fa-car-crash fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "09-001", name = "บัญชีแยกประเภท", name2 = "General Ledger", Desc1 = "", Desc2 = "", Module = "GL", MenuType = "H1", parrentMenu = "09-001", path = "GL", icon = "fas fa-file-signature text-hover-primary fs-2x pr-3", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "09-002", name = "บันทึกรายวัน", name2 = "Ledger account", Desc1 = "", Desc2 = "", Module = "GL", MenuType = "H2", parrentMenu = "09-001", path = "GL", icon = "", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "09-003", name = "รายวันทั่วไป", name2 = "General Journal", Desc1 = "บันทึกรายการบัญชีรายวันแยกประเภทรายการทั่วไป", Desc2 = "", Module = "GL", MenuType = "S", parrentMenu = "09-002", path = "GL/GLM", icon = "fa fa-file-alt fa-3x", command = "JV", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "09-004", name = "รายวันซื้อ", name2 = "Purchase Journal", Desc1 = "บันทึกรายการบัญชีรายวันแยกประเภทรายการตั้งหนี้ซื้อ", Desc2 = "", Module = "GL", MenuType = "S", parrentMenu = "09-002", path = "GL/GLM", icon = "fa fa-file-contract fa-3x", command = "AP", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "09-005", name = "รายวันจ่าย", name2 = "Payment Voucher", Desc1 = "บันทึกรายการบัญชีรายวันแยกประเภทรายการจ่ายชำระ", Desc2 = "", Module = "GL", MenuType = "S", parrentMenu = "09-002", path = "GL/GLM", icon = "fa fa-file-3x", command = "PV", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "09-006", name = "รายวันขาย", name2 = "Sales journal", Desc1 = "บันทึกรายการบัญชีรายวันแยกประเภทรายการตั้ั้งหนี้ขาย", Desc2 = "", Module = "GL", MenuType = "S", parrentMenu = "09-002", path = "GL/GLM", icon = "fa fa-file-invoice fa-3x", command = "AR", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "09-007", name = "รายวันรับ", name2 = "Receipt journal", Desc1 = "บันทึกรายการบัญชีรายวันแยกประเภทรายการรับชำระ", Desc2 = "", Module = "GL", MenuType = "S", parrentMenu = "09-002", path = "GL/GLM", icon = "fa fa-file-invoice-dollar fa-3x", command = "SV", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "09-008", name = "เงินสดย่อย", name2 = "Petty cash", Desc1 = "", Desc2 = "", Module = "GL", MenuType = "H2", parrentMenu = "09-001", path = "", icon = "", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "09-009", name = "บันทึกภาษี", name2 = "Vat Register", Desc1 = "", Desc2 = "", Module = "GL", MenuType = "H2", parrentMenu = "09-001", path = "", icon = "", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "09-010", name = "บันทึกภาษีหัก ณ ที่จ่าย", name2 = "Withholding tax Register", Desc1 = "", Desc2 = "", Module = "GL", MenuType = "S", parrentMenu = "09-009", path = "", icon = "fa fa-file-alt fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "09-011", name = "งบประมาณ", name2 = "Budget", Desc1 = "", Desc2 = "", Module = "GL", MenuType = "H2", parrentMenu = "09-001", path = "", icon = "", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "09-012", name = "รายงานภาษี", name2 = "Tax Report", Desc1 = "", Desc2 = "", Module = "GL", MenuType = "H2", parrentMenu = "09-001", path = "", icon = "", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "09-013", name = "รายงานแยกประเภท", name2 = "Ledger report", Desc1 = "", Desc2 = "", Module = "GL", MenuType = "H2", parrentMenu = "09-001", path = "", icon = "", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "09-014", name = "รายงานงบการเงิน", name2 = "Financial statement", Desc1 = "", Desc2 = "", Module = "GL", MenuType = "H2", parrentMenu = "09-001", path = "", icon = "", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "09-015", name = "รายงานงบประมาณ", name2 = "Budget report", Desc1 = "", Desc2 = "", Module = "GL", MenuType = "H2", parrentMenu = "09-001", path = "", icon = "", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "09-016", name = "แบบฟอร์มงบ", name2 = "Financial Form Design", Desc1 = "", Desc2 = "", Module = "GL", MenuType = "H2", parrentMenu = "09-001", path = "", icon = "", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "10-001", name = "ธนาคาร", name2 = "Bank documents", Desc1 = "", Desc2 = "", Module = "Bank", MenuType = "H1", parrentMenu = "10-001", path = "Bank", icon = "fas fa-file-invoice-dollar text-hover-primary fs-2x pr-3", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "10-002", name = "บันทึกเอกสาร", name2 = "Bank Documents", Desc1 = "", Desc2 = "", Module = "Bank", MenuType = "H2", parrentMenu = "10-001", path = "Bank", icon = "", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "10-003", name = "บันทึกเคลื่องไหว", name2 = "Bank Transaction", Desc1 = "เพิ่ม/แก้ไข เอกสารการเคลื่อนไหวของสมุดบัญชีเงินฝาก การใช้เมนูนี้ไม่มีผลกับการบันทึกรายวันทางบัญชี", Desc2 = "Add/edit passbook movement document This menu operation has no effect on accounting journals", Module = "Bank", MenuType = "S", parrentMenu = "10-002", path = "Bank", icon = "fa fa-file-medical-alt fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "10-004", name = "บันทึกใบนำฝาก", name2 = "Bank deposit", Desc1 = "เพิ่ม/แก้ไข ใบนำฝากธนาคาร ใช้ในกรณีต้องการนำฝากเช็ครับ, ฝากเงินสด เป็นต้น การบันทึกที่เมนูนี้โปรแกรมจะบันทึกรายวันที่ระบบบัญชีให้อัตโนมัติ", Desc2 = "Add/edit Bank deposit Used in the event of a check deposit, cash deposit, etc.Save at this menu, the program will automatically record the daily accounting system", Module = "Bank", MenuType = "S", parrentMenu = "10-002", path = "Bank", icon = "fa fa-file-invoice-dollar fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "10-005", name = "บันทึกเช็ครับที่ผ่าน(บันทึกบัญชี)", name2 = "Pass Cheque", Desc1 = "", Desc2 = "", Module = "Bank", MenuType = "S", parrentMenu = "10-002", path = "Bank", icon = "fa fa-money-check fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "10-006", name = "บันทึกประวัติเช็คคืน", name2 = "Return Cheque", Desc1 = "", Desc2 = "", Module = "Bank", MenuType = "S", parrentMenu = "10-002", path = "Bank", icon = "fa fa-money-check-alt fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "10-007", name = "กลับรายการเช็คจ่าย(บันทึกบัญชี)", name2 = "Reversing Entries Cheque", Desc1 = "", Desc2 = "", Module = "Bank", MenuType = "S", parrentMenu = "10-002", path = "Bank", icon = "fa fa-credit-card fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "10-008", name = "บันทึกเช็คจ่ายที่ผ่าน(ไม่บันทึกบัญชี)", name2 = "Pass Pay cheque", Desc1 = "", Desc2 = "", Module = "Bank", MenuType = "S", parrentMenu = "10-002", path = "Bank", icon = "fa fa-money-bill fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "10-009", name = "โอนระหว่างสมุดบัญชี", name2 = "Bank Transfer", Desc1 = "", Desc2 = "", Module = "Bank", MenuType = "S", parrentMenu = "10-002", path = "Bank", icon = "fa fa-copy fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "10-009", name = "รายงานเอกสารธนาคาร", name2 = "Bank statement Report", Desc1 = "", Desc2 = "", Module = "Bank", MenuType = "H2", parrentMenu = "10-001", path = "Bank", icon = "", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-001", name = "ฐานข้อมูล", name2 = "Master data", Desc1 = "บันทึกฐานข้อมูลทะบียนรายชื่อที่ต้องนำไปใช้ในการบันทึกเอกสารต่าง ๆ ในระบบ", Desc2 = "Record a list of names that must be used for saving documents in the system", Module = "Database", MenuType = "H1", parrentMenu = "11-001", path = "Database", icon = "fas fa-database text-hover-primary fs-2x pr-3", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-002", name = "ลูกค้า", name2 = "Sales Master", Desc1 = "บันทึกข้อมูลทะเบียนราชื่อที่ต้องนำไปใช้ในระบบขายสินค้า", Desc2 = "Record the registration information of the name that must be used in the selling system", Module = "Database", MenuType = "H2", parrentMenu = "11-001", path = "Database/Sales", icon = "", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-003", name = "ทะเบียนลูกค้า", name2 = "Customer", Desc1 = "เพิ่ม/แก้ไข รายชื่อลูกค้า เพื่อนำไปใช้ในการบันทึกเอกสารระบบขาย", Desc2 = "Add/edit customer list For use in documenting sales systems", Module = "Database", MenuType = "S", parrentMenu = "11-002", path = "Database/Customer", icon = "fa fa-id-card fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-004", name = "กลุ่มลูกค้า", name2 = "Customer group", Desc1 = "เพิ่ม/แก้ไข รายชื่อกลุ่มลูกค้า เพื่อประโยชน์ในการตรวจสอบการขายแยกตามกลุ่มลูกค้า", Desc2 = "Add/edit customer groups For the benefit of monitoring sales by customer groups", Module = "Database", MenuType = "S", parrentMenu = "11-002", path = "Database/CustGroup", icon = "fa fa-users fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-005", name = "พนักงานขาย", name2 = "Sales person", Desc1 = "เพิ่ม/แก้ไข รายชื่อพนักงานขาย เพื่อตรวจสอบการขายแยกตามพนักงาน และคำนวณค่าคอมมิชชั่น", Desc2 = "Add/edit the list of sales staff To monitor sales by employees And calculate the commission", Module = "Database", MenuType = "S", parrentMenu = "11-002", path = "Database/SaleMan", icon = "fa fa-user-tie fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-006", name = "ทีมขาย", name2 = "Sales team", Desc1 = "เพิ่ม/แก้ไข รายชื่อทีมขายเพื่อตรวจสอบยอดขายแยกแยกตามทีม", Desc2 = "Add/edit sales team lists to monitor sales separately by teams", Module = "Database", MenuType = "S", parrentMenu = "11-002", path = "Database/SaleTeam", icon = "fa fa-users-cog fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-007", name = "เขตการขาย", name2 = "Territory", Desc1 = "เพิ่ม/แก้ไข รายชื่อเขตการขายเพื่อตรวจสอบยอดขายแยกตามเขตของลูกค้า", Desc2 = "Add/edit a list of sales territories to check sales by region of the customer", Module = "Database", MenuType = "S", parrentMenu = "11-002", path = "Database/Territory", icon = "fa fa-map fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-008", name = "ส่วนแบ่งการตลาด", name2 = "Seqment", Desc1 = "เพิ่ม/แก้ไข รายชื่อส่วนแบ่งการตลาดเพื่อวิเคราะมูลค่าส่วนแบ่งการตลาดแยกตามลูกค้า", Desc2 = "Add/edit market share list to analyze market share value by customer", Module = "Database", MenuType = "S", parrentMenu = "11-002", path = "Database/Seqment", icon = "fa fa-globe fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-009", name = "ราคาขาย", name2 = "Price list", Desc1 = "เพิ่ม/แก้ไข ราคาสินค้าตามผู้จำหน่ายแต่ละรายเพื่อนำไปใช้ในเอกสารซื้อซึ่งจะแสดงราคาซื้อตามผู้จำหน่าย", Desc2 = "", Module = "Database", MenuType = "S", parrentMenu = "11-002", path = "Database/PriceList", icon = "fa fa-tag fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-010", name = "ราคาขายตามลูกค้า", name2 = "Price list Customer", Desc1 = "เพิ่ม/แก้ไข ราคาสินค้าตามผู้จำหน่ายแต่ละรายเพื่อนำไปใช้ในเอกสารซื้อซึ่งจะแสดงราคาซื้อตามผู้จำหน่าย", Desc2 = "Add/edit product prices by individual vendor for use in purchase documents, which will display purchase prices by vendor", Module = "Database", MenuType = "S", parrentMenu = "11-002", path = "Database/PriceListCust", icon = "fa fa-tags fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-011", name = "ผู้จำหน่าย", name2 = "Purchase Master", Desc1 = "บันทึกข้อมูลทะเบียนราชื่อที่ต้องนำไปใช้ในระบบขายสินค้า", Desc2 = "Record the registration information of the name that must be used in the selling system", Module = "Database", MenuType = "H2", parrentMenu = "11-001", path = "Database/Purchase", icon = "", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-012", name = "ทะเบียนผู้จำหน่าย", name2 = "Vendor", Desc1 = "เพิ่ม/แก้ไข รายชื่อผู้จำหน่าย เพื่อนำไปใช้ในการบันทึกเอกสารระบบซื้อ", Desc2 = "Add/edit supplier list To be used for documenting the purchase system", Module = "Database", MenuType = "S", parrentMenu = "11-011", path = "Database/Vendor", icon = "fa fa-id-card fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-013", name = "กลุ่มผู้จำหน่าย", name2 = "Vendor group", Desc1 = "เพิ่ม/แก้ไข รายชื่อกลุ่มผู้จำหน่ายเพื่อประโยชน์ในการตรวจสอบการขายแยกตามกลุ่มผู้จำหน่าย", Desc2 = "Add/edit a list of vendors for the benefit of monitoring sales by dealer group", Module = "Database", MenuType = "S", parrentMenu = "11-011", path = "Database/VenderGrp", icon = "fa fa-users fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-014", name = "ราคาขาย", name2 = "Price list", Desc1 = "เพิ่ม/แก้ไข ราคาสินค้าตามผู้จำหน่ายแต่ละรายเพื่อนำไปใช้ในเอกสารซื้อซึ่งจะแสดงราคาซื้อตามผู้จำหน่าย", Desc2 = "", Module = "Database", MenuType = "S", parrentMenu = "11-011", path = "Database/PriceList", icon = "fa fa-tag fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-015", name = "ราคาขายผู้จำหน่าย", name2 = "Price list Vendor", Desc1 = "เพิ่ม/แก้ไข ราคาสินค้าตามผู้จำหน่ายแต่ละรายเพื่อนำไปใช้ในเอกสารซื้อซึ่งจะแสดงราคาซื้อตามผู้จำหน่าย", Desc2 = "Add/edit product prices by individual vendor for use in purchase documents, which will display purchase prices by vendor", Module = "Database", MenuType = "S", parrentMenu = "11-011", path = "Database/PriceListVendor", icon = "fa fa-tags fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-016", name = "สินค้า", name2 = "Inventory Master", Desc1 = "บันทึกข้อมูลเกี่ยวกับสินค้าคงคลัง รายชื่อสินค้า กลุ่มสินค้า อื่นๆ", Desc2 = "Add/edit inventory information List of other products", Module = "Database", MenuType = "H2", parrentMenu = "11-001", path = "Database/Product", icon = "", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-017", name = "ทะเบียนสินค้า", name2 = "Products", Desc1 = "เพิ่ม/แก้ไข รายการสินค้า, วัตถุดิบ, สินทรัพย์ หรือรายการใด ๆ เพื่อนำไปใช้กับเอกสารซื้อ-ขาย", Desc2 = "Add/edit a list of products, materials, assets or any items for use in the documents.", Module = "Database", MenuType = "S", parrentMenu = "11-016", path = "Database/Prod", icon = "fa fa-qrcode fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-018", name = "ทะเบียนงานบริการ", name2 = "Service", Desc1 = "เพิ่ม/แก้ไข รายการรายได้บริการ และ ค่าใช้จ่ายเพื่อนำไปใช้กับเอกสารซื้อ-ขาย", Desc2 = "Add/edit items of income, services and expenses to be applied to the documents.", Module = "Database", MenuType = "S", parrentMenu = "11-016", path = "Database/Service", icon = "fa fa-barcode fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-019", name = "เพิ่มชุดสินค้า", name2 = "Product set", Desc1 = "เพิ่ม/แก้ไข ชุดสินค้า เป็นการจัดประกอบสินค้าเพื่อแสดงการขายเป็นชุด ", Desc2 = "Add/edit product batches, assemble products to show selling as a set.", Module = "Database", MenuType = "S", parrentMenu = "11-016", path = "Database/ProductSet", icon = "fa fa-cubes fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-020", name = "หน่วยนับ", name2 = "Unit", Desc1 = "เพิ่ม/แก้ไข หน่วยนับสินค้า เพื่อนำไปใช้เพื่อระบุหน่วยของสินค้าแต่ละรายการ", Desc2 = "Add/edit product counts This will be used to identify the units of each item.", Module = "Database", MenuType = "S", parrentMenu = "11-016", path = "Database/Um", icon = "fa fa-cube fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-021", name = "กลุ่มสินค้า", name2 = "Product group", Desc1 = "เพิ่ม/แก้ไข กลุ่มสินค้าเพือประโยชน์ในการออกรายงานตามกลุ่มสินค้า", Desc2 = "Add/edit product groups for the benefit of reporting by product group.", Module = "Database", MenuType = "S", parrentMenu = "11-016", path = "Database/ProdGrp", icon = "fa fa-layer-group fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-022", name = "สมาชิก", name2 = "Member", Desc1 = "เพิ่ม/แก้ไข สมาชิกเพื่อนำไปใช้กำหนดราคาสินค้าแยกตามกลุ่มสมาชิก", Desc2 = "Add/edit members to be used to set product prices by member group", Module = "Database", MenuType = "S", parrentMenu = "11-016", path = "Database/member", icon = "fa fa-address-card fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-023", name = "คลังสินค้า", name2 = "Whouse", Desc1 = "เพิ่ม/แก้ไข คลังสินค้าเพื่อตรวจสอบสินค้าคงเหลือแยกตามคลัง", Desc2 = "Add/edit warehouse to check inventory by warehouse", Module = "Database", MenuType = "S", parrentMenu = "11-016", path = "Database/Whouse", icon = "fa fa-warehouse fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-024", name = "ชั้นวาง", name2 = "Shelf", Desc1 = "เพิ่ม/แก้ไข ชั้นวางสินค้าเพื่อระบุตำแหน่งที่เก็บของสินค้าภายในคลัง", Desc2 = "Add/edit shelf to locate products in the warehouse", Module = "Database", MenuType = "S", parrentMenu = "11-016", path = "Database/Shelf", icon = "fa fa-pallet fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-025", name = "หมวด", name2 = "Category", Desc1 = "เพิ่ม/แก้ไข หมวดสินค้าเพื่อประโยชน์ในการตรวจสอบสินค้าแยกตามหมวด", Desc2 = "Add/edit product categories for the benefit of checking products classified by category", Module = "Database", MenuType = "S", parrentMenu = "11-016", path = "Database/Category", icon = "fa fa-pills fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-026", name = "ยี่ห้อ", name2 = "Brand", Desc1 = "เพิ่ม/แก้ไข ยี่ห้อสินค้าเพื่อประโยชน์ในการตรวจสอบสินค้าแยกตามยี่ห้อ", Desc2 = "Add/edit product brands for the benefit of checking products classified by brands", Module = "Database", MenuType = "S", parrentMenu = "11-016", path = "Database/Brand", icon = "fa fa-capsules fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-027", name = "รูปแบบ", name2 = "Format", Desc1 = "เพิ่ม/แก้ไข รูปแบบสินค้าเพื่อประโยชน์ในการตรวจสอบสินค้าแยกตามรูปแบบ", Desc2 = "Add/edit product types for the purpose of inspecting products by format", Module = "Database", MenuType = "S", parrentMenu = "11-016", path = "Database/Format", icon = "fa fa-tablets fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-028", name = "การออกแบบ", name2 = "Design", Desc1 = "เพิ่ม/แก้ไข ออกแบบสินค้าเพื่อประโยชน์ในการตรวจสอบสินค้าแยกตามออกแบบ", Desc2 = "Add/edit product designs for the benefit of product inspection by design", Module = "Database", MenuType = "S", parrentMenu = "11-016", path = "Database/Design", icon = "fa fa-boxes fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-029", name = "คุณภาพสินค้า", name2 = "Quality", Desc1 = "เพิ่ม/แก้ไข คุณภาพสินค้า หรือ เกรดสินค้า เพื่อประโยชน์ในการตรวจสอบสินค้าแยกตามคุณภาพ ", Desc2 = "Add/edit product grades for the benefit of checking products classified by grade", Module = "Database", MenuType = "S", parrentMenu = "11-016", path = "Database/Grade", icon = "fa fa-dolly fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-030", name = "รุ่น", name2 = "Model", Desc1 = "เพิ่ม/แก้ไข รุ่นสินค้าเพื่อประโยชน์ในการตรวจสอบสินค้าแยกตามรุ่น", Desc2 = "Add/edit product models for the benefit of checking products by model", Module = "Database", MenuType = "S", parrentMenu = "11-016", path = "Database/Model", icon = "fa fa-baseball-ball fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-031", name = "ขนาด", name2 = "Size", Desc1 = "เพิ่ม/แก้ไข ขนาดสินค้าเพื่อประโยชน์ในการตรวจสอบสินค้าแยกตามขนาด", Desc2 = "Add/edit product sizes for the benefit of checking products by size", Module = "Database", MenuType = "S", parrentMenu = "11-016", path = "Database/Size", icon = "fa fa-archive fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-032", name = "สี", name2 = "Color", Desc1 = "เพิ่ม/แก้ไข สีสินค้าเพื่อประโยชน์ในการตรวจสอบสินค้าแยกตามสี", Desc2 = "Add/edit product colors for the benefit of checking products by color", Module = "Database", MenuType = "S", parrentMenu = "11-016", path = "Database/Color", icon = "fa fa-palette fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-033", name = "น้ำหนัก", name2 = "Weight", Desc1 = "เพิ่ม/แก้ไข น้ำหนักสินค้าเพื่อประโยชน์ในการตรวจสอบสินค้าแยกตามน้ำหนัก", Desc2 = "Add/edit product weight for the purpose of inspecting products by weight", Module = "Database", MenuType = "S", parrentMenu = "11-016", path = "Database/Weight", icon = "fa fa-weight fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-034", name = "บัญชี", name2 = "Accounting Master", Desc1 = "สร้างข้อมูลตั้งต้นของงานบัญชี เพื่อนำไปใช้ในระบบต่าง ๆ เช่น ผังบัญชี, อัตราภาษี เป็นต้น", Desc2 = "Generate initial accounting information For use in various systems such as chart of accounts, tax rates, etc.", Module = "Database", MenuType = "H2", parrentMenu = "11-001", path = "Database/Account", icon = "", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-035", name = "ผังบัญชี", name2 = "Account code", Desc1 = "เพิ่ม/แก้ไข รหัสบัญชีเพื่อนำไปใช้ในการบันทึกรายวัน ตรวจสอบรายงานแยกประเภท และงบการเงิน", Desc2 = "Add/edit billing codes to be used for journaling.Examine the ledger and financial statements", Module = "Database", MenuType = "S", parrentMenu = "11-034", path = "Database/Acchart", icon = "fa fa-solar-panel fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-036", name = "สมุดรายวัน", name2 = "Journal book", Desc1 = "เพิ่ม/แก้ไข สมุดรายวันแยกประเภท เพื่อแยกประเภทการบันทึกรายวันแยกประเภท", Desc2 = "Add/edit classified journal To categorize journaling by category", Module = "Database", MenuType = "S", parrentMenu = "11-034", path = "Database/AccBook", icon = "fa fa-swatchbook fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-037", name = "บัญชีแยกประเภทที่ใช้บ่อย", name2 = "Dummy General Ledger ", Desc1 = "เพิ่ม/แก้ไข บัญชีแยกประเภทที่ใช้ซ้ำ ๆ เช่น ลงรายวันประเภทเงินเดือน ฯลฯ", Desc2 = "Add/edit  Dummy General Ledger ", Module = "Database", MenuType = "S", parrentMenu = "11-034", path = "Database", icon = "fa fa-book fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-038", name = "อัตราภาษี", name2 = "Tax rate", Desc1 = "เพิ่ม/แก้ไข อัตราภาษีมูลค่าเพิ่ม เพิ่มนำไประบุในเอกสารต่าง ๆ และตรวจสอบรายงานภาษี", Desc2 = "Add/edit VAT rates Add to be identified in various documents and check the tax report.", Module = "Database", MenuType = "S", parrentMenu = "11-034", path = "Database/VatType", icon = "fa fa-vote-yea fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-039", name = "ธนาคาร", name2 = "Accounting Master", Desc1 = "สร้างข้อมูลตั้งต้นของงานบัญชี เพื่อนำไปใช้ในระบบต่าง ๆ เช่น ผังบัญชี, อัตราภาษี เป็นต้น", Desc2 = "Generate initial accounting information For use in various systems such as chart of accounts, tax rates, etc.", Module = "Database", MenuType = "H2", parrentMenu = "11-001", path = "Database/Account", icon = "", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-040", name = "สมุดบัญชีเงินฝาก", name2 = "Book Bank", Desc1 = "เพิ่ม/แก้ไข เล่มบัญชีธนาคาร", Desc2 = "Add/edit the Book Bank", Module = "Database", MenuType = "S", parrentMenu = "11-039", path = "Database/BookBank", icon = "fa fa-money-check fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-041", name = "รายชื่อธนาคาร", name2 = "Bank", Desc1 = "เพิ่ม/แก้ไข รายชื่อธนาคารเพื่อใช้ในการระบุ สมุดบัญชีเงินฝาก และระบุตอนรับ-จ่ายเงิน", Desc2 = "Add/edit bank names for identification purposes. Passbook And specify when receiving-paying", Module = "Database", MenuType = "S", parrentMenu = "11-039", path = "Database/Bank", icon = "fa fa-university fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-042", name = "สาขาธนาคาร", name2 = "Bank Branch", Desc1 = "เพิ่ม/แก้ไข รายชื่อสาขาธนาคารเพื่อใช้ในการระบุ สมุดบัญชีเงินฝาก และระบุตอนรับ-จ่ายเงิน", Desc2 = "Add/edit the list of bank branches to identify Passbook And specify when receiving-paying", Module = "Database", MenuType = "S", parrentMenu = "11-039", path = "Database/BankBranch", icon = "fa fa-archway fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-043", name = "หน่วยเงินอัตราแลกเปลี่ยน", name2 = "Currency", Desc1 = "เพิ่ม/แก้ไข หน่วยเงินตรา ที่จะนำไปใช้งานในการคำนวณอัตราแลกเปลี่ยน", Desc2 = "Add/edit currency units to be used in currency exchange calculations.", Module = "Database", MenuType = "S", parrentMenu = "11-039", path = "Database/Currency", icon = "fa fa-file-invoice-dollar fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-044", name = "อัตราแลกเปลี่ยนประจำวัน", name2 = "Currency per Day", Desc1 = "เพิ่ม/แก้ไข อัตราแลกเปลี่ยนเงินประจำวัน", Desc2 = "Add/edit daily exchange rates", Module = "Database", MenuType = "S", parrentMenu = "11-039", path = "Database/CurrencyDay", icon = "fa fa-money-check-alt fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-044", name = "สินทรััพย์", name2 = "Asset", Desc1 = "เพิ่ม/แก้ไข ฐานข้อมูลสินทรัพสำหรับคำนวนค่าเสื่อมราคา", Desc2 = "Add/edit Asset", Module = "Database", MenuType = "H2", parrentMenu = "11-001", path = "Database/Asset", icon = "", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-045", name = "ฐานข้้อมูลสินทรัพย์", name2 = "Asset", Desc1 = "เพิ่ม/แก้ไข ฐานข้้อมูลสินทรัพย์", Desc2 = "Add/Edit Asset", Module = "Database", MenuType = "S", parrentMenu = "11-044", path = "Database/Asset", icon = "fa fa-money-check fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-046", name = "ฐานข้อมููลกลุ่มสินทรัพย์", name2 = "Asset Group", Desc1 = "เพิ่ม/แก้ไข ฐานข้้อมูลกลุ่มสินทรัพย์", Desc2 = "Add/Edit Asset Group", Module = "Database", MenuType = "S", parrentMenu = "11-044", path = "Database/AssetGroup", icon = "fa fa-money-check fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-049", name = "ข้อมูลองค์กร", name2 = "Organization", Desc1 = "บันทึกรายละเอียดข้อมูลขององค์กร เช่น ชื่อบริษัท, สาขา, แผนก, โครงการ เป็นต้น", Desc2 = "Save detailed information of the organization such as company name, branch, department, project, etc.", Module = "Database", MenuType = "H2", parrentMenu = "11-001", path = "Database/Company", icon = "", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-050", name = "แผนก", name2 = "Department", Desc1 = "เพิ่ม/แก้ไข รายชื่อแผนก เพื่อนำไปใช้ในการแยกบัญชีรายได้-ค่าใช้จ่าย และตรวจสอบงบการเงินแยกตามแผนก", Desc2 = "Add/edit the list of departments to be used for income-expense separation.And issue financial statements separated by department", Module = "Database", MenuType = "S", parrentMenu = "11-049", path = "Database/Department", icon = "fa fa-sign fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-051", name = "ฝ่าย", name2 = "Section", Desc1 = "เพิ่ม/แก้ไข รายชื่อฝ่าย เพื่อนำไปกำหนดหมวดของแผนก และแยกบัญชีรายได้-ค่าใช้จ่าย เพื่อตรวจสอบงบการเงินแยกตามฝ่าย", Desc2 = "Add/edit the list of departments to define departments And separate income-expenses accounts To examine the financial statements by department", Module = "Database", MenuType = "S", parrentMenu = "11-049", path = "Database/Section", icon = "fa fa-th-large fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-052", name = "โครงการ", name2 = "Project", Desc1 = "เพิ่ม/แก้ไข รายชื่อโครงการ เพื่อนำไปใช้ในจัดสรรค์งบประมาณของโครงการ ในการตรวจสอบ บัญชีรายได้-ค่าใช้จ่าย และตรวจสอบงบการเงินแยกตามโครงการ", Desc2 = "Add/edit project list To be used in the budgeting of the project in the audit of income-expenses.And examining the financial statements separated by projects", Module = "Database", MenuType = "S", parrentMenu = "11-049", path = "Database/Project", icon = "fa fa-th fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-053", name = "แผนงาน", name2 = "Plan", Desc1 = "เพิ่ม/แก้ไข รายชื่อแผนงาน เพื่อนำไปใช้จัดหมวดของโครงการ ในการตรวจสอบ บัญชีรายได้-ค่าใช้จ่าย และตรวจสอบงบการเงินแยกตามแผนงาน", Desc2 = "Add/edit plan list To be used to categorize projects to verify income-expenses.And audited financial statements separated by plans", Module = "Database", MenuType = "S", parrentMenu = "11-049", path = "Database/Plan", icon = "fa fa-th-list fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-054", name = "แขวง/ตำบล", name2 = "District", Desc1 = "เพิ่ม/แก้ไข รายชื่อแขวง/ตำบล เพื่อเป็นข้อมูลที่นำไปใช้ในการระบุที่อยู่ของระบบต่าง ๆ", Desc2 = "Add/edit list of sub-district To be information that can be used to identify the address of various systems.", Module = "Database", MenuType = "S", parrentMenu = "11-049", path = "Database/PostalSubdisrict", icon = "fa fa-map-marked-alt fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-055", name = "เขต/อำเภอ", name2 = "Ampoe", Desc1 = "เพิ่ม/แก้ไข รายชื่อเขต/อำเภอ เพื่อเป็นข้อมูลที่นำไปใช้ในการระบุที่อยู่ของระบบต่าง ๆ", Desc2 = "Add/edit the list of districts to provide information that can be used for addressing various systems.", Module = "Database", MenuType = "S", parrentMenu = "11-049", path = "Database/PostalDisrict", icon = "fa fa-map-marked fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-056", name = "จังหวัด", name2 = "Province", Desc1 = "เพิ่ม/แก้ไข รายชื่อจังหวัด เพื่อเป็นข้อมูลที่นำไปใช้ในการระบุที่อยู่ของระบบต่าง ๆ", Desc2 = "Add/edit the list of provinces To be information that can be used to identify the address of various systems.", Module = "Database", MenuType = "S", parrentMenu = "11-049", path = "Database/PostalProvince", icon = "fa fa-map fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-057", name = "ประเทศ", name2 = "Country", Desc1 = "เพิ่ม/แก้ไข รายชื่อประเทศ เพื่อเป็นข้อมูลที่นำไปใช้ในการระบุที่อยู่ของระบบต่าง ๆ", Desc2 = "Add/edit country list To be information that can be used to identify the address of various systems.", Module = "Database", MenuType = "S", parrentMenu = "11-049", path = "Database/PostalCountry", icon = "fa fa-globe-asia fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-058", name = "สาขา", name2 = "Branch", Desc1 = "เพิ่ม/แก้ไข รายชื่อสาขาของบริษัทที่ใช้งาน ", Desc2 = "Add/edit the list of branches of the company used.", Module = "Database", MenuType = "S", parrentMenu = "11-049", path = "Database/Branch", icon = "fa fa-building fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "11-059", name = "บริษัท", name2 = "Company", Desc1 = "เพิ่ม/แก้ไข รายละเอียดชื่อบริษัท ที่อยู่, เลขประจำตัวผู้เสียภาษี", Desc2 = "Add/edit details, company name, address, tax ID number", Module = "Database", MenuType = "S", parrentMenu = "11-049", path = "Database/Company", icon = "fa fa-city fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "12-001", name = "กำหนดค่าเริ่มต้น", name2 = "Configuration", Desc1 = "", Desc2 = "", Module = "Config", MenuType = "H1", parrentMenu = "12-001", path = "", icon = "fas fa-cog text-hover-primary fs-2x pr-3", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "12-002", name = "บันทึกข้อมูล", name2 = "Save Configuration", Desc1 = "กำหนดค่าตั้งต้นในการใช้งาน ", Desc2 = "Set the default usage", Module = "Config", MenuType = "H2", parrentMenu = "12-001", path = "Database/Config", icon = "", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "12-003", name = "Config", name2 = "Document Format", Desc1 = "กำหนดรูปแบบรหัสเล่มเอกสาร, รูปแบบการ Running เลขที่ของเอกสาร รวมถึงรูปแบบการบันทึกรายวันที่ระบบบัญชี และการกำหนดแบบฟอร์มพิมพ์ต่าง ๆ", Desc2 = "Set the format, code, document book, running format, document number Including the daily recording format at the accounting system And assigning various print forms", Module = "Config", MenuType = "S", parrentMenu = "12-002", path = "Config/ErpConfig", icon = "fa fa-book-open fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "12-004", name = "หน้าที่บัญชีหลัก", name2 = "Account Role Main", Desc1 = "เพิ่ม/แก้ไข หน้าที่บัญขีหลักใช้งานกับทุกส่วนของระบบ", Desc2 = "Add/edit the account Role main use all system", Module = "Config", MenuType = "S", parrentMenu = "12-002", path = "Database/AccRole", icon = "fa fa-book-open fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "12-005", name = "หน้าที่บัญชีเฉพาะ", name2 = "Account Role Specific", Desc1 = "เพิ่ม/แก้ไข หน้าที่บัญขีเฉพาะ", Desc2 = "Add/edit the account Role Specific", Module = "Config", MenuType = "S", parrentMenu = "12-002", path = "Database/AccRoleTemplate", icon = "fa fa-book-reader fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "12-006", name = "เล่มเอกสาร", name2 = "Book Document", Desc1 = "เพิ่ม/แก้ไข เล่มเอกสาร", Desc2 = "Add/edit the Book Document", Module = "Config", MenuType = "S", parrentMenu = "12-002", path = "Database/Book", icon = "fa fa-book fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "12-007", name = "บันทึกยอดยกมา", name2 = "Beginning balance", Desc1 = "", Desc2 = "", Module = "Database", MenuType = "H2", parrentMenu = "12-001", path = "Database", icon = "", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "12-008", name = "เจ้าหนี้ยกมา", name2 = "Accounts Payable balance", Desc1 = "เพิ่ม/แก้ไข เอกสารเจ้าหนี้ยกมากตั้งต้น สามารถบันทึกแบบรวบเอกสารเป็นยอดเดียว หรือจะบันทึกแบบแยกเอกสารได้ทั้ง 2 แบบ", Desc2 = "Add/edit documents Able to save the document as a single amount Or can save both types of documents separately", Module = "Database", MenuType = "S", parrentMenu = "12-007", path = "Database", icon = "fa fa-id-card fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "12-009", name = "ลูกหนี้ยกมา", name2 = "Accounts Receivable balance", Desc1 = "เพิ่ม/แก้ไข เอกสารลูกหนี้ยกมากตั้งต้น สามารถบันทึกแบบรวบเอกสารเป็นยอดเดียว หรือจะบันทึกแบบแยกเอกสารได้ทั้ง 2 แบบ", Desc2 = "Add/edit documents from the default receivables Able to save the document as a single amount Or can save both types of documents separately", Module = "Database", MenuType = "S", parrentMenu = "12-007", path = "Database", icon = "fa fa-id-card fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "12-010", name = "สินค้ายกมา", name2 = "Inventory balance", Desc1 = "เพิ่ม/แก้ไข สินค้าคงเหลือยกมาตั้งต้น ณ วันที่เริ่มใช้ระบบ", Desc2 = "Add/edit inventory from the beginning of the system use.", Module = "Database", MenuType = "S", parrentMenu = "12-007", path = "Database", icon = "fa fa-boxes fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "12-011", name = "บัญชียกมา(งบดุล)", name2 = "Balance sheet", Desc1 = "เพิ่ม/แก้ไข ยอดยกมาทางบัญชี ณ วันที่เริ่มใช้ระบบ กรณีใช้เมนูนี้ให้บันทึกด้วยมูลค่าตามงบดุล", Desc2 = "Add/edit the account balance as of the system start date.If using this menu, record the balance sheet value.", Module = "Database", MenuType = "S", parrentMenu = "12-007", path = "Database", icon = "fa fa-chart-bar fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "12-012", name = "เช็คยกมา", name2 = "Cheque Balance", Desc1 = "เพิ่ม/แก้ไข ยอดยกเช็คค้างรับ และค้างจ่ายยกมา ณ วันที่เริ่มใช้งานระบบ", Desc2 = "เพิ่ม/แก้ไข ยอดยกเช็คค้างรับ และค้างจ่ายยกมา ณ วันที่เริ่มใช้งานระบบ", Module = "Database", MenuType = "S", parrentMenu = "12-007", path = "Database", icon = "fa fa-money-check fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "13-001", name = "กำหนดสิทธิ์", name2 = "Permissions", Desc1 = "", Desc2 = "", Module = "Permissions", MenuType = "H1", parrentMenu = "13-001", path = "", icon = "fas fa-shield-alt text-hover-primary fs-2x pr-3", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "13-002", name = "บันทึกข้อมูล", name2 = "Add Data", Desc1 = "", Desc2 = "", Module = "Permissions", MenuType = "H2", parrentMenu = "13-001", path = "Database/User", icon = "", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "13-003", name = "ผู้ใช้งาน", name2 = "User", Desc1 = "เพิ่ม/แก้ไข ผู้ใช้งานระบบ", Desc2 = "Add/Edit username and password", Module = "Permissions", MenuType = "S", parrentMenu = "13-002", path = "Database/UserLogin", icon = "fas fa-user fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "13-004", name = "ตำแหน่ง", name2 = "Position", Desc1 = "เพิ่ม/แก้ไข ตำแหน่ง ผู้ใช้งาน", Desc2 = "Add/Edit position", Module = "Permissions", MenuType = "S", parrentMenu = "13-002", path = "Database/Position", icon = "fas fa-user-tie fa-3x", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            menus.Add(new menu { code = "14-001", name = "ออกจากโปรแกรม", name2 = "Exit", Desc1 = "", Desc2 = "", Module = "Exit", MenuType = "H1", parrentMenu = "14-001", path = "", icon = "fas fa-shield-alt text-hover-primary fs-2x pr-3", command = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            int maxlenght = menus.Count;
            for (int i = 0; i < maxlenght; i += 400)
            {
                menu[] liResult = menus.Skip(i).Take(400).ToArray();
                if (liResult is not null && liResult.Length > 0)
                {
                    context.AddRange(liResult);
                    context.SaveChanges(true);
                }
            }
        }
    }
}
