using Microsoft.EntityFrameworkCore;
using RichnessSoft.Entity.Class;
using RichnessSoft.Entity.Model;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
namespace RichnessSoft.Data
{
    public static class initDocType
    {
        public static void InitializeAsync(RicnessDbContext context
            , RichnessLogDbContext contextlog
            , SuperAdminDefaultOptions superAdminDefaultOptions)
        {
            List<docType> doctypes = new List<docType>();

            doctypes.Add(new docType() { System = "PURCHASE", Menu = "PURCHASE ORDER", Type = "Order", Formula = "PR", Doc_Group = "PO", Code = "PR", Name = "ใบขอซื้อ", Name2 = "Purchase Request", Vat = "Y", Cash = "", Service = "", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "PURCHASE", Menu = "PURCHASE ORDER", Type = "Order", Formula = "PO", Doc_Group = "PO", Code = "PO", Name = "ใบสั่งซื้อ ", Name2 = "Purchase Order", Vat = "", Cash = "", Service = "", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "PURCHASE", Menu = "PURCHASE", Type = "Buy Trading", Formula = "BI", Doc_Group = "BT", Code = "IVB", Name = "ใบกำกับภาษี/แจ้งหนี้ ซื้อเชื่อ", Name2 = "Purchase Tax Invoice", Vat = "Y", Cash = "", Service = "", Tax_Refund = "Y", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "PURCHASE", Menu = "PURCHASE", Type = "Buy Trading", Formula = "BM", Doc_Group = "BT", Code = "CNB", Name = "ใบกำกับภาษี/ลดหนี้ ซื้อเชื่อ", Name2 = "Purchase Credit note", Vat = "Y", Cash = "", Service = "", Tax_Refund = "Y", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "PURCHASE", Menu = "PURCHASE", Type = "Buy Trading", Formula = "BN", Doc_Group = "BT", Code = "DNB", Name = "ใบกำกับภาษี/เพิ่มหนี้ ซื้อเชื่อ", Name2 = "Purchase Debit note", Vat = "Y", Cash = "", Service = "", Tax_Refund = "Y", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "PURCHASE", Menu = "PURCHASE", Type = "Buy Service", Formula = "BV", Doc_Group = "BS", Code = "BIV", Name = "ใบแจ้งหนี้ ซื้อเชื่อ(ภาษียังไม่ถึงกำหนด)", Name2 = "Invoice(Undue Input Vat)", Vat = "N", Cash = "", Service = "", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "PURCHASE", Menu = "PURCHASE", Type = "Buy Service", Formula = "BC", Doc_Group = "BS", Code = "BCN", Name = "ใบแจ้งหนี้/ลดหนี้ ซื้อเชื่อ(ภาษียังไม่ถึงกำหนด)", Name2 = "Credit Note(Undue Input Vat)", Vat = "N", Cash = "", Service = "", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "PURCHASE", Menu = "PURCHASE", Type = "Buy Service", Formula = "BD", Doc_Group = "BS", Code = "BDN", Name = "ใบแจ้งหนี้/เพิ่มหนี้ ซื้อเชื่อ(ภาษียังไม่ถึงกำหนด)", Name2 = "Debit Note(Undue Input Vat)", Vat = "", Cash = "", Service = "", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "PURCHASE", Menu = "PURCHASE", Type = "Buy Trading", Formula = "R5", Doc_Group = "BT", Code = "ADP", Name = "ใบแจ้งหนี้ เงินมัดจำจ่ายล่วงหน้า ", Name2 = "Advance Dposit Paid", Vat = "Y", Cash = "", Service = "", Tax_Refund = "Y", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "PURCHASE", Menu = "PAYMENT", Type = "Buy Trading", Formula = "BR", Doc_Group = "BC", Code = "PCI", Name = "ใบกำกับภาษี/ใบเสร็จรับเงิน(ซื้อสด)", Name2 = "Cash Buy", Vat = "Y", Cash = "", Service = "", Tax_Refund = "Y", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "PURCHASE", Menu = "PAYMENT", Type = "Buy Trading", Formula = "BA", Doc_Group = "BC", Code = "PCN", Name = "ใบกำกับภาษี/ลดหนี้(ซื้อสด)", Name2 = "Cash Buy Credit Note", Vat = "Y", Cash = "", Service = "", Tax_Refund = "Y", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "PURCHASE", Menu = "PAYMENT", Type = "Buy Trading", Formula = "BB", Doc_Group = "BC", Code = "PDN", Name = "ใบกำกับภาษี/เพิ่มหนี้(ซื้อสอ)", Name2 = "Cash Buy Debit Note", Vat = "Y", Cash = "", Service = "", Tax_Refund = "Y", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "PURCHASE", Menu = "PAYMENT", Type = "Pay Billing", Formula = "PL", Doc_Group = "PL", Code = "PBL", Name = "ใบวางบิล ", Name2 = "Billing", Vat = "  ", Cash = "", Service = "", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "PURCHASE", Menu = "PAYMENT", Type = "Pay Before", Formula = "PB", Doc_Group = "PP", Code = "PPR", Name = "ใบเตรียมจ่ายชำระ(ก่อนรับใบเสร็จ)", Name2 = "Prepare Payment", Vat = "  ", Cash = "", Service = "", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "PURCHASE", Menu = "PAYMENT", Type = "Pay Trading", Formula = "PI", Doc_Group = "PM", Code = "PRE", Name = "ใบเสร็จรับเงิน", Name2 = "Payment Receipt", Vat = "  ", Cash = "", Service = "", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "PURCHASE", Menu = "PAYMENT", Type = "Pay Before", Formula = "PT", Doc_Group = "PP", Code = "PPI", Name = "ใบเตรียมจ่ายชำระ(ก่อนรับใบเสร็จ/ใบกำกับภาษี)", Name2 = "Perpare Payment Invoice", Vat = "  ", Cash = "", Service = "", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "PURCHASE", Menu = "PAYMENT", Type = "Pay Service", Formula = "PV", Doc_Group = "PM", Code = "PIV", Name = "ใบเสร็จ/ใบกำกับภาษี", Name2 = "Payment Receipt Invoice", Vat = "Y", Cash = "", Service = "", Tax_Refund = "Y", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "PURCHASE", Menu = "PAYMENT", Type = "Pay Trading", Formula = "", Doc_Group = "PM", Code = "PDP", Name = "ใบเสร็จ/ใบกำกับภาษี จ่ายเงินมัดจำล่วงหน้า", Name2 = "Cash Buy Deposit", Vat = "Y", Cash = "", Service = "", Tax_Refund = "Y", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "INVENTORY", Menu = "INVENTORY", Type = "Delivery", Formula = "DO", Doc_Group = "DO", Code = "GR", Name = "ใบรับสินค้าชั่วคราว ", Name2 = "Goods received", Vat = "  ", Cash = "", Service = "", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "INVENTORY", Menu = "INVENTORY", Type = "Delivery", Formula = "GB", Doc_Group = "DO", Code = "DO", Name = "ใบส่งสินค้าชั่วคราว", Name2 = "Delivery Order", Vat = "  ", Cash = "", Service = "", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "INVENTORY", Menu = "INVENTORY", Type = "Stock Requset", Formula = "QA", Doc_Group = "RQ", Code = "RL", Name = "ใบขอยืมสินค้า", Name2 = "Borrowing form", Vat = "", Cash = "", Service = "", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "INVENTORY", Menu = "INVENTORY", Type = "Stock Out", Formula = "", Doc_Group = "LO", Code = "LB", Name = "ใบยืมสินค้า", Name2 = "Borrowing Note from loan   ", Vat = "", Cash = "", Service = "", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "INVENTORY", Menu = "INVENTORY", Type = "Stock In", Formula = "", Doc_Group = "LO", Code = "LR", Name = "ใบคืนสินค้าจากการยืม", Name2 = "Return Note to loan   ", Vat = "", Cash = "", Service = "", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "INVENTORY", Menu = "INVENTORY", Type = "Stock Requset", Formula = "QB", Doc_Group = "RQ", Code = "WTR", Name = "ใบขอโอนสินค้าระหว่างคลัง", Name2 = "Warehouse Transfer Requset", Vat = "  ", Cash = "", Service = "", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "INVENTORY", Menu = "INVENTORY", Type = "Stock Transfer", Formula = "TR", Doc_Group = "TF", Code = "WTF", Name = "ใบโอนระหว่างคลัง", Name2 = "Warehouse Transfer", Vat = "", Cash = "", Service = "", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "INVENTORY", Menu = "INVENTORY", Type = "Stock Requset", Formula = "QT", Doc_Group = "RQ", Code = "BTR", Name = "ใบขอโอนสินค้าระหว่างสาขา", Name2 = "Branch Transfer Request", Vat = "", Cash = "", Service = "", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "INVENTORY", Menu = "INVENTORY", Type = "Stock Transfer", Formula = "TB", Doc_Group = "TF", Code = "BTF", Name = "ใบโอนระหว่างสาขา", Name2 = "Branch Transfer", Vat = "", Cash = "", Service = "", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "INVENTORY", Menu = "INVENTORY", Type = "Adjust", Formula = "AJ", Doc_Group = "AJ", Code = "AJ", Name = "ใบปรับยอด", Name2 = "Adjust inventory", Vat = "  ", Cash = "", Service = "", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "INVENTORY", Menu = "INVENTORY", Type = "Adjust", Formula = "CS", Doc_Group = "AJ", Code = "CK", Name = "ใบตรวจนับสต๊อก", Name2 = "Check inventory", Vat = "  ", Cash = "", Service = "", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "SALE", Menu = "SALE ORDER", Type = "Reserve", Formula = "QS", Doc_Group = "SO", Code = "QT", Name = "ใบเสนอราคา สินค้า/บริการ", Name2 = "Quotation", Vat = "", Cash = "", Service = "", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "SALE", Menu = "SALE ORDER", Type = "Reserve", Formula = "SO", Doc_Group = "SO", Code = "SO", Name = "ใบรับคำสั่งซื้อ สินค้า/บริการ", Name2 = "Sale Order", Vat = "", Cash = "", Service = "", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "SALE", Menu = "SALE", Type = "Sale Service", Formula = "R5", Doc_Group = "ST", Code = "DPR", Name = "ใบกำกับภาษี เงินมัดจำรับล่วงหน้า ", Name2 = "Deposit Received", Vat = "Y", Cash = "", Service = "", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "SALE", Menu = "SALE", Type = "Sale trading", Formula = "SI", Doc_Group = "ST", Code = "IVS", Name = "ใบกำกับภาษี/ใบแจ้งหนี้ ขายเชื่อ ", Name2 = "Tax invoice Sales ", Vat = "Y", Cash = "", Service = "", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "SALE", Menu = "SALE", Type = "Sale trading", Formula = "SM", Doc_Group = "ST", Code = "CNS", Name = "ใบกำกับภาษี/ลดหนี้ ขายเชื่อ", Name2 = "Credit Note Sales ", Vat = "Y", Cash = "", Service = "", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "SALE", Menu = "SALE", Type = "Sale trading", Formula = "SN", Doc_Group = "ST", Code = "DNS", Name = "ใบกำกับภาษี/เพิ่มหนี้ ขายเชื่อ", Name2 = "Debit  Note Sales ", Vat = "Y", Cash = "", Service = "", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "SALE", Menu = "SALE", Type = "Sale Service", Formula = "SV", Doc_Group = "SS", Code = "SIV", Name = "ใบแจ้งหนี้ ขายเชื่อ(ภาษียังไม่ถึงกำหนด)", Name2 = "Service Invoice", Vat = "N", Cash = "", Service = "Y", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "SALE", Menu = "SALE", Type = "Sale Service", Formula = "SC", Doc_Group = "SS", Code = "SCN", Name = "ใบแจ้งหนี้/ลดหนี้ ขายเชื่อ(ภาษียังไม่ถึงกำหนด)", Name2 = "Service Credit Note", Vat = "N", Cash = "", Service = "Y", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "SALE", Menu = "SALE", Type = "Sale Service", Formula = "SD", Doc_Group = "SS", Code = "SDN", Name = "ใบแจ้งหนี้/เพิ่มหนี้ ขายเชื่อ(ภาษียังไม่ถึงกำหนด)", Name2 = "Service Debit Note", Vat = "N", Cash = "", Service = "Y", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "SALE", Menu = "RECEIPT", Type = "Sale trading", Formula = "SR", Doc_Group = "SC", Code = "RCI", Name = "ใบกำกับภาษี/ใบเสร็จรับเงิน ขายสด", Name2 = "Cash Sales Tax invoice", Vat = "Y", Cash = "Y", Service = "", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "SALE", Menu = "RECEIPT", Type = "Sale trading", Formula = "SA", Doc_Group = "SC", Code = "RCN", Name = "ใบกำกับภาษี/ลดหนี้ ขายสด", Name2 = "Cash Sell Credit Note", Vat = "Y", Cash = "Y", Service = "", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "SALE", Menu = "RECEIPT", Type = "Sale trading", Formula = "SB", Doc_Group = "SC", Code = "RDN", Name = "ใบกำกับภาษี/เพิ่มหนี้ ขายสด", Name2 = "Cash Sell Debit Note", Vat = "Y", Cash = "Y", Service = "", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "SALE", Menu = "RECEIPT", Type = "Receipt Bill", Formula = "RL", Doc_Group = "RL", Code = "RBL", Name = "ใบรับวางบิล ", Name2 = "Bill", Vat = "", Cash = "", Service = "", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "SALE", Menu = "RECEIPT", Type = "Receipt Before", Formula = "RB", Doc_Group = "RP", Code = "RPR", Name = "ใบเสร็จ(เพิ่มก่อนการรับเงิน)", Name2 = "Perpare Receipt", Vat = "", Cash = "", Service = "", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "SALE", Menu = "RECEIPT", Type = "Receipt trading", Formula = "RI", Doc_Group = "RE", Code = "RRE", Name = "ใบเสร็จรับเงิน ", Name2 = "Receipt", Vat = "N", Cash = "Y", Service = "Y", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "SALE", Menu = "RECEIPT", Type = "Receipt Before", Formula = "RT", Doc_Group = "RP", Code = "RPI", Name = "ใบเสร็จ/ใบกำกับภาษี(พิมพ์ก่อนการรับเงิน)", Name2 = "Perpare Receipt invoice", Vat = "", Cash = "", Service = "Y", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "SALE", Menu = "RECEIPT", Type = "Receipt Service", Formula = "RV", Doc_Group = "RE", Code = "RIV", Name = "ใบเสร็จ/ใบกำกับภาษี ", Name2 = "Receip Invoice", Vat = "N", Cash = "", Service = "", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "SALE", Menu = "RECEIPT", Type = "Receipt Trading", Formula = "RE", Doc_Group = "RE", Code = "RDP", Name = "ใบเสร็จ/ใบกำกับภาษี เงินมัดจำรับ", Name2 = "Cash Sell Deposit", Vat = "Y", Cash = "", Service = "", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "BANK", Menu = "BANK", Type = "Bank", Formula = "CQ", Doc_Group = "BK", Code = "CQE", Name = "เช็ค", Name2 = "Cheque", Vat = "", Cash = "", Service = "", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "BANK", Menu = "BANK", Type = "Bank", Formula = "PS", Doc_Group = "BK", Code = "PIN", Name = "ใบนำฝาก                                                                                             ", Name2 = "Deposit slip                                                                                  ", Vat = "", Cash = "", Service = "", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "BANK", Menu = "BANK", Type = "Bank", Formula = "TR", Doc_Group = "CQ", Code = "TRF", Name = "ใบโอนเงินระหว่างธนาคาร", Name2 = "Bank Transfer", Vat = "", Cash = "", Service = "", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "GL", Menu = "GL", Type = "GL", Formula = "", Doc_Group = "GL", Code = "VC", Name = "ใบสำคัญการลงบัญชี", Name2 = "Voucher", Vat = "", Cash = "", Service = "", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "PURCHASE", Menu = "GL", Type = "Withholding Tax", Formula = "XQ", Doc_Group = "WH", Code = "PN1", Name = "ใบภาษีหัก ณ ที่จ่าย บริษัทหักบุคคลธรรมดายื่น ภ.ง.ด. 1", Name2 = " Withholding Tax Note-PERSONAL-SUBMIT TAX RETURN FORM 1 ", Vat = "", Cash = "", Service = "", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "PURCHASE", Menu = "GL", Type = "Withholding Tax", Formula = "XQ", Doc_Group = "WH", Code = "PN2", Name = "ใบภาษีหัก ณ ที่จ่าย บริษัทหักบุคคลธรรมดายื่น ภ.ง.ด. 2", Name2 = " Withholding Tax Note-PERSONAL-SUBMIT TAX RETURN FORM 2", Vat = "", Cash = "", Service = "", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "PURCHASE", Menu = "GL", Type = "Withholding Tax", Formula = "XP", Doc_Group = "WH", Code = "PN3", Name = "ใบภาษีหัก ณ ที่จ่าย บริษัท หักบุคคลธรรมดายื่น ภ.ง.ด. 3 ", Name2 = " Withholding Tax Note-PERSONAL-SUBMIT TAX RETURN FORM 3", Vat = "", Cash = "", Service = "", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "PURCHASE", Menu = "GL", Type = "Withholding Tax", Formula = "XQ", Doc_Group = "WH", Code = "P1K", Name = "ใบภาษีหัก ณ ที่จ่าย บริษัทหักบุคคลธรรมดายื่น ภ.ง.ด. 1ก", Name2 = " Withholding Tax Note-PERSONAL-SUBMIT TAX RETURN FORM 1 k", Vat = "", Cash = "", Service = "", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "PURCHASE", Menu = "GL", Type = "Withholding Tax", Formula = "XQ", Doc_Group = "WH", Code = "P1S", Name = "ใบภาษีหัก ณ ที่จ่าย บริษัทหักบุคคลธรรมดายื่น ภ.ง.ด. 1ก พิเศษ", Name2 = " Withholding Tax Note-PERSONAL-SUBMIT TAX RETURN FORM 1 special", Vat = "", Cash = "", Service = "", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "PURCHASE", Menu = "GL", Type = "Withholding Tax", Formula = "XQ", Doc_Group = "WH", Code = "P2K", Name = "ใบภาษีหัก ณ ที่จ่าย บริษัทหักบุคคลธรรมดายื่น ภ.ง.ด. 2ก", Name2 = " Withholding Tax Note-PERSONAL-SUBMIT TAX RETURN FORM 2 k", Vat = "", Cash = "", Service = "", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "PURCHASE", Menu = "GL", Type = "Withholding Tax", Formula = "XQ", Doc_Group = "WH", Code = "P3K", Name = "ใบภาษีหัก ณ ที่จ่าย บริษัท หักบุคคลธรรมดายื่น ภ.ง.ด. 3ก", Name2 = " Withholding Tax Note-PERSONAL-SUBMIT TAX RETURN FORM 3 k", Vat = "", Cash = "", Service = "", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "PURCHASE", Menu = "GL", Type = "Withholding Tax", Formula = "XL", Doc_Group = "WH", Code = "P53", Name = "ใบภาษีหัก ณ ที่จ่าย บริษัท หักนิติบุคคลยื่น ภ.ง.ด. 53", Name2 = " Withholding Tax Note-COMPANY-SUBMIT TAX RETURN FORM 53 ", Vat = "", Cash = "", Service = "", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "PURCHASE", Menu = "GL", Type = "Withholding Tax", Formula = "XQ", Doc_Group = "WH", Code = "P54", Name = "ใบภาษีหัก ณ ที่จ่าย บริษัท หักนิติบุคคลยื่น ภ.ง.ด. 54", Name2 = " Withholding Tax Note-COMPANY-SUBMIT TAX RETURN FORM 54", Vat = "", Cash = "", Service = "", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "PURCHASE", Menu = "GL", Type = "Withholding Tax", Formula = "XS", Doc_Group = "WH", Code = "WTO", Name = "ใบภาษีหัก ณ ที่จ่ายอื่นๆ(หักภาษี ณ ที่จ่ายไว้)", Name2 = " Withholding Tax Note-OTHER(NOT SUBMIT BUT FOR CHECKING)", Vat = "", Cash = "", Service = "", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "PURCHASE", Menu = "GL", Type = "Withholding Tax", Formula = "TP", Doc_Group = "WH", Code = "PND", Name = "ใบภาษีหัก ณ ที่จ่าย(กรณีเราเป็นผู้จ่าย/ผู้หักภาษี)", Name2 = " Withholding Tax Note(Pay)  ", Vat = "", Cash = "", Service = "", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "PURCHASE", Menu = "GL", Type = "Withholding Tax", Formula = "OP", Doc_Group = "WH", Code = "WT3", Name = "ใบภาษีหัก ณ ที่จ่ายกระทำการแทน บริษัท หักบุคคลธรรมดา ยื่นภงด. 3", Name2 = "Rrepesent  Withholding Tax Note-PERSONAL-SUBMIT TAX RETURN FORM 3 ", Vat = "", Cash = "", Service = "", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "PURCHASE", Menu = "GL", Type = "Withholding Tax", Formula = "OL", Doc_Group = "WH", Code = "WT5", Name = "ใบภาษีหัก ณ ที่จ่ายกระทำการแทน บริษัท หักนิติบุคคล ยื่นภงด.53 ", Name2 = "Represent  Withholding Tax Note-COMPANY-SUBMIT TAX RETURN FORM 53 ", Vat = "", Cash = "", Service = "", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "SALE", Menu = "GL", Type = "Withholding Tax", Formula = "WP", Doc_Group = "WH", Code = "WHP", Name = "ใบภาษีหัก ณ ที่จ่าย บุคคลธรรมดาถูกหัก ไม่ต้องนำส่ง", Name2 = " Withholding Tax Note-PERSONAL-NOT SUBMIT", Vat = "", Cash = "", Service = "", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "SALE", Menu = "GL", Type = "Withholding Tax", Formula = "WL", Doc_Group = "WH", Code = "WHC", Name = "ใบภาษีหัก ณ ที่จ่าย บริษัทถูกหัก ไม่นำส่งแต่ไว้ตรวจสอบรายการ", Name2 = " Withholding Tax Note-COMPANY-NOT SUBMIT-BUT FOR CHECKING  ", Vat = "", Cash = "", Service = "", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "SALE", Menu = "GL", Type = "Withholding Tax", Formula = "XT", Doc_Group = "WH", Code = "WHO", Name = "ใบภาษีหัก ณ ที่จ่ายอื่นๆ(ถูกหักภาษี ณ ที่จ่าย)", Name2 = " Withholding Tax Note-OTHER", Vat = "", Cash = "", Service = "", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });
            doctypes.Add(new docType() { System = "SALE", Menu = "GL", Type = "Withholding Tax", Formula = "TS", Doc_Group = "WH", Code = "WHN", Name = "ใบภาษีหัก ณ ที่จ่าย(กรณีเราเป็นผู้รับ/ถูกหักภาษี)", Name2 = " Withholding Tax Note(NOT-SUBMIT) ", Vat = "", Cash = "", Service = "", Tax_Refund = "", CreateAtUtc = DateTime.Now, UpdateAtUtc = DateTime.Now });

            try
            {
                context.AddRange(doctypes.ToArray());
                context.SaveChanges();
            }
            catch (Exception ex)
            {
                Console.WriteLine($" Exception : {ex}");
            }
            
        }
    }
}
