using RichnessSoft.Common;
using RichnessSoft.Entity.Class;
using RichnessSoft.Entity.Model;
using System;
using System.Collections.Generic;
using System.Linq;

namespace RichnessSoft.Data
{
    public static class InitPayType
    {
        public static void InitializeAsync(RicnessDbContext context
            , RichnessLogDbContext contextlog
            , SuperAdminDefaultOptions superAdminDefaultOptions)
        {
            IList<PayType> listData = new List<PayType>()
            {
                new PayType() { Code = SysDef.PayType.gc_PAYTYPE_CM, Name ="ค่าธรรมเนียม", Name2="Fee" , Active = ConstUtil.ACTIVE.YES , Group= SysDef.PayGroup.gc_PAYGROUP_INTEREST , InOut = SysDef.PayType_IO.gc_PAY_OUT , IsDeposit = ConstUtil.CONFIRM.YES , IsWithdraw = ConstUtil.CONFIRM.YES, CreateAtUtc = DateTime.Now , CreateBy="System", LinkID = StrUtil.GetUniqueKey(25) },
                new PayType() { Code = SysDef.PayType.gc_PAYTYPE_COU , Name ="คูปองส่วนลด", Name2="Discount Coupons" , Active = ConstUtil.ACTIVE.YES , Group= SysDef.PayGroup.gc_PAYGROUP_CASH, InOut = SysDef.PayType_IO.gc_PAY_IN , IsDeposit = ConstUtil.CONFIRM.YES , IsWithdraw = ConstUtil.CONFIRM.YES, CreateAtUtc = DateTime.Now , CreateBy="System", LinkID = StrUtil.GetUniqueKey(25) },
                new PayType() { Code = SysDef.PayType.gc_PAYTYPE_CR, Name ="เช็คคืน", Name2="Returned Cheque" , Active = ConstUtil.ACTIVE.YES , Group= SysDef.PayGroup.gc_PAYGROUP_CHEQUE , InOut = SysDef.PayType_IO.gc_PAY_IN , IsDeposit = ConstUtil.CONFIRM.YES , IsWithdraw = ConstUtil.CONFIRM.YES, CreateAtUtc = DateTime.Now , CreateBy="System", LinkID = StrUtil.GetUniqueKey(25) },
                new PayType() { Code = SysDef.PayType.gc_PAYTYPE_INW, Name ="ดอกเบี้ย", Name2="Interest" , Active = ConstUtil.ACTIVE.YES , Group= SysDef.PayGroup.gc_PAYGROUP_INTEREST , InOut = SysDef.PayType_IO.gc_PAY_IN , IsDeposit = ConstUtil.CONFIRM.YES , IsWithdraw = ConstUtil.CONFIRM.YES, CreateAtUtc = DateTime.Now , CreateBy="System", LinkID = StrUtil.GetUniqueKey(25) },
                new PayType() { Code = SysDef.PayType.gc_PAYTYPE_LC, Name ="เล็ตเตอร์ออฟเครดิต", Name2="Letter Of Credit" , Active = ConstUtil.ACTIVE.YES , Group= SysDef.PayGroup.gc_PAYGROUP_TRAN, InOut = SysDef.PayType_IO.gc_PAY_EMPTY , IsDeposit = ConstUtil.CONFIRM.YES , IsWithdraw = ConstUtil.CONFIRM.YES, CreateAtUtc = DateTime.Now , CreateBy="System", LinkID = StrUtil.GetUniqueKey(25) },
                new PayType() { Code = SysDef.PayType.gc_PAYTYPE_OCI, Name ="เงินเกิน", Name2="Excess Money" , Active = ConstUtil.ACTIVE.YES , Group= SysDef.PayGroup.gc_PAYGROUP_CASH , InOut = SysDef.PayType_IO.gc_PAY_IN , IsDeposit = ConstUtil.CONFIRM.YES , IsWithdraw = ConstUtil.CONFIRM.YES, CreateAtUtc = DateTime.Now , CreateBy="System", LinkID = StrUtil.GetUniqueKey(25) },
                new PayType() { Code = SysDef.PayType.gc_PAYTYPE_OCL, Name ="เงินขาด", Name2="Lack Of Money" , Active = ConstUtil.ACTIVE.YES , Group= SysDef.PayGroup.gc_PAYGROUP_CASH , InOut = SysDef.PayType_IO.gc_PAY_IN , IsDeposit = ConstUtil.CONFIRM.YES , IsWithdraw = ConstUtil.CONFIRM.YES, CreateAtUtc = DateTime.Now , CreateBy="System", LinkID = StrUtil.GetUniqueKey(25) },
                new PayType() { Code = SysDef.PayType.gc_PAYTYPE_RF, Name ="Refer", Name2="Refer" , Active = ConstUtil.ACTIVE.YES , Group= SysDef.PayGroup.gc_PAYGROUP_AUTO , InOut = SysDef.PayType_IO.gc_PAY_EMPTY, IsDeposit = ConstUtil.CONFIRM.YES , IsWithdraw = ConstUtil.CONFIRM.YES, CreateAtUtc = DateTime.Now , CreateBy="System", LinkID = StrUtil.GetUniqueKey(25) },
                new PayType() { Code = SysDef.PayType.gc_PAYTYPE_ATS , Name ="รายการบัญชีอัตโนมัติ", Name2="Automatic Transaction" , Active = ConstUtil.ACTIVE.YES , Group= SysDef.PayGroup.gc_PAYGROUP_TRAN , InOut = SysDef.PayType_IO.gc_PAY_EMPTY , IsDeposit = ConstUtil.CONFIRM.YES , IsWithdraw = ConstUtil.CONFIRM.YES, CreateAtUtc = DateTime.Now , CreateBy="System", LinkID = StrUtil.GetUniqueKey(25) },
                new PayType() { Code = SysDef.PayType.gc_PAYTYPE_CD, Name ="บัตรเครดิต", Name2="Credit Card" , Active = ConstUtil.ACTIVE.YES , Group= SysDef.PayGroup.gc_PAYGROUP_TRAN , InOut = SysDef.PayType_IO.gc_PAY_EMPTY, IsDeposit = ConstUtil.CONFIRM.YES , IsWithdraw = ConstUtil.CONFIRM.YES, CreateAtUtc = DateTime.Now , CreateBy="System", LinkID = StrUtil.GetUniqueKey(25) },
                new PayType() { Code = SysDef.PayType.gc_PAYTYPE_BB, Name ="ฝากโดยเช็ค เงินตราตปท.", Name2="Input check into the bank foreign currency deposit" , Active = ConstUtil.ACTIVE.YES , Group= SysDef.PayGroup.gc_PAYGROUP_CHEQUE , InOut = SysDef.PayType_IO.gc_PAY_IN , IsDeposit = ConstUtil.CONFIRM.YES , IsWithdraw = ConstUtil.CONFIRM.NO, CreateAtUtc = DateTime.Now , CreateBy="System", LinkID = StrUtil.GetUniqueKey(25) },
                new PayType() { Code = SysDef.PayType.gc_PAYTYPE_BG, Name ="Bank Guarantee", Name2="Bank Guarantee" , Active = ConstUtil.ACTIVE.YES , Group= SysDef.PayGroup.gc_PAYGROUP_GUARANTEE , InOut = SysDef.PayType_IO.gc_PAY_OUT , IsDeposit = ConstUtil.CONFIRM.YES , IsWithdraw = ConstUtil.CONFIRM.NO, CreateAtUtc = DateTime.Now , CreateBy="System", LinkID = StrUtil.GetUniqueKey(25) },
                new PayType() { Code = SysDef.PayType.gc_PAYTYPE_CL , Name ="ฝากโดยเช็คธนาคารอื่น", Name2="Other bank cheque deposit" , Active = ConstUtil.ACTIVE.YES , Group= SysDef.PayGroup.gc_PAYGROUP_CHEQUE, InOut = SysDef.PayType_IO.gc_PAY_IN , IsDeposit = ConstUtil.CONFIRM.YES , IsWithdraw = ConstUtil.CONFIRM.NO, CreateAtUtc = DateTime.Now , CreateBy="System", LinkID = StrUtil.GetUniqueKey(25) },
                new PayType() { Code = SysDef.PayType.gc_PAYTYPE_DD , Name ="ฝากโดยดราฟท์", Name2="Draft deposit" , Active = ConstUtil.ACTIVE.YES , Group= SysDef.PayGroup.gc_PAYGROUP_CHEQUE, InOut = SysDef.PayType_IO.gc_PAY_IN , IsDeposit = ConstUtil.CONFIRM.YES , IsWithdraw = ConstUtil.CONFIRM.NO, CreateAtUtc = DateTime.Now , CreateBy="System", LinkID = StrUtil.GetUniqueKey(25) },
                new PayType() { Code = SysDef.PayType.gc_PAYTYPE_MO , Name ="ธนาณัติ", Name2="Money Order" , Active = ConstUtil.ACTIVE.YES , Group= SysDef.PayGroup.gc_PAYGROUP_CASH, InOut = SysDef.PayType_IO.gc_PAY_EMPTY , IsDeposit = ConstUtil.CONFIRM.YES , IsWithdraw = ConstUtil.CONFIRM.NO, CreateAtUtc = DateTime.Now , CreateBy="System", LinkID = StrUtil.GetUniqueKey(25) },
                new PayType() { Code = SysDef.PayType.gc_PAYTYPE_PC , Name ="ฝากโดยเงินสด", Name2="Cash deposit" , Active = ConstUtil.ACTIVE.YES , Group= SysDef.PayGroup.gc_PAYGROUP_TRAN, InOut = SysDef.PayType_IO.gc_PAY_IN , IsDeposit = ConstUtil.CONFIRM.YES , IsWithdraw = ConstUtil.CONFIRM.NO, CreateAtUtc = DateTime.Now , CreateBy="System", LinkID = StrUtil.GetUniqueKey(25) },
                new PayType() { Code = SysDef.PayType.gc_PAYTYPE_TRD , Name ="ฝากโดยการโอน", Name2="Transfer deposit" , Active = ConstUtil.ACTIVE.YES , Group= SysDef.PayGroup.gc_PAYGROUP_TRAN, InOut = SysDef.PayType_IO.gc_PAY_IN , IsDeposit = ConstUtil.CONFIRM.YES , IsWithdraw = ConstUtil.CONFIRM.NO, CreateAtUtc = DateTime.Now , CreateBy="System", LinkID = StrUtil.GetUniqueKey(25) },
                new PayType() { Code = SysDef.PayType.gc_PAYTYPE_HC , Name ="ฝากโดยเช็ค (เช็ครับ)", Name2="Cheque deposit (Received cheque)" , Active = ConstUtil.ACTIVE.YES , Group= SysDef.PayGroup.gc_PAYGROUP_CHEQUE, InOut = SysDef.PayType_IO.gc_PAY_IN , IsDeposit = ConstUtil.CONFIRM.YES , IsWithdraw = ConstUtil.CONFIRM.NO, CreateAtUtc = DateTime.Now , CreateBy="System", LinkID = StrUtil.GetUniqueKey(25) },
                new PayType() { Code = SysDef.PayType.gc_PAYTYPE_CHI , Name ="เงินสดรับ", Name2="Cash received entry" , Active = ConstUtil.ACTIVE.YES , Group= SysDef.PayGroup.gc_PAYGROUP_CASH, InOut = SysDef.PayType_IO.gc_PAY_IN , IsDeposit = ConstUtil.CONFIRM.YES , IsWithdraw = ConstUtil.CONFIRM.NO, CreateAtUtc = DateTime.Now , CreateBy="System", LinkID = StrUtil.GetUniqueKey(25) },
                new PayType() { Code = SysDef.PayType.gc_PAYTYPE_CC , Name ="ฝากโดยเช็คเรียกเก็บ", Name2="Call cheque deposit" , Active = ConstUtil.ACTIVE.YES , Group= SysDef.PayGroup.gc_PAYGROUP_CHEQUE, InOut = SysDef.PayType_IO.gc_PAY_IN , IsDeposit = ConstUtil.CONFIRM.YES , IsWithdraw = ConstUtil.CONFIRM.NO, CreateAtUtc = DateTime.Now , CreateBy="System", LinkID = StrUtil.GetUniqueKey(25) },
                new PayType() { Code = SysDef.PayType.gc_PAYTYPE_CG , Name ="ถอนเงินผ่านเคลียริ่ง", Name2="Clearing withdraw" , Active = ConstUtil.ACTIVE.YES , Group= SysDef.PayGroup.gc_PAYGROUP_TRAN, InOut = SysDef.PayType_IO.gc_PAY_OUT , IsDeposit = ConstUtil.CONFIRM.NO , IsWithdraw = ConstUtil.CONFIRM.YES, CreateAtUtc = DateTime.Now , CreateBy="System", LinkID = StrUtil.GetUniqueKey(25) },
                new PayType() { Code = SysDef.PayType.gc_PAYTYPE_CS , Name ="ถอนเงินสด", Name2="Cash withdraw" , Active = ConstUtil.ACTIVE.YES , Group= SysDef.PayGroup.gc_PAYGROUP_TRAN, InOut = SysDef.PayType_IO.gc_PAY_OUT , IsDeposit = ConstUtil.CONFIRM.NO , IsWithdraw = ConstUtil.CONFIRM.YES, CreateAtUtc = DateTime.Now , CreateBy="System", LinkID = StrUtil.GetUniqueKey(25) },
                new PayType() { Code = SysDef.PayType.gc_PAYTYPE_OV , Name ="ค่า OV", Name2="OV" , Active = ConstUtil.ACTIVE.YES , Group= SysDef.PayGroup.gc_PAYGROUP_EMPTY, InOut = SysDef.PayType_IO.gc_PAY_EMPTY , IsDeposit = ConstUtil.CONFIRM.NO , IsWithdraw = ConstUtil.CONFIRM.YES, CreateAtUtc = DateTime.Now , CreateBy="System", LinkID = StrUtil.GetUniqueKey(25) },
                new PayType() { Code = SysDef.PayType.gc_PAYTYPE_TRW , Name ="ถอนโดยการโอน", Name2="Transfer withdraw" , Active = ConstUtil.ACTIVE.YES , Group= SysDef.PayGroup.gc_PAYGROUP_TRAN, InOut = SysDef.PayType_IO.gc_PAY_OUT , IsDeposit = ConstUtil.CONFIRM.NO , IsWithdraw = ConstUtil.CONFIRM.YES, CreateAtUtc = DateTime.Now , CreateBy="System", LinkID = StrUtil.GetUniqueKey(25) },
                new PayType() { Code = SysDef.PayType.gc_PAYTYPE_CW , Name ="ถอนโดยเช็ค (เช็คจ่าย)", Name2="Cheque withdraw (Paid cheque)" , Active = ConstUtil.ACTIVE.YES , Group= SysDef.PayGroup.gc_PAYGROUP_CHEQUE, InOut = SysDef.PayType_IO.gc_PAY_OUT , IsDeposit = ConstUtil.CONFIRM.NO , IsWithdraw = ConstUtil.CONFIRM.YES, CreateAtUtc = DateTime.Now , CreateBy="System", LinkID = StrUtil.GetUniqueKey(25) },
                new PayType() { Code = SysDef.PayType.gc_PAYTYPE_CHO , Name ="เงินสดจ่าย", Name2="Cash paid entry" , Active = ConstUtil.ACTIVE.YES , Group= SysDef.PayGroup.gc_PAYGROUP_CASH, InOut = SysDef.PayType_IO.gc_PAY_OUT , IsDeposit = ConstUtil.CONFIRM.NO , IsWithdraw = ConstUtil.CONFIRM.YES, CreateAtUtc = DateTime.Now , CreateBy="System", LinkID = StrUtil.GetUniqueKey(25) },
            };
            context.AddRange(listData.ToArray());
            context.SaveChanges();
        }
    }
}
