using RichnessSoft.Entity.Class;
using RichnessSoft.Entity.Context;
using RichnessSoft.Entity.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RichnessSoft.Entity.initData
{
    public static class initMenu
    {
        public static void InitializeAsync(RicnessDbContext context
             , RichnessLogDbContext contextlog
             , SuperAdminDefaultOptions superAdminDefaultOptions)
        {
            IList<Menu> menus = new List<Menu>();

            menus.Add(new Menu { code = "01-001", name1 = "รับคำสั่งขาย", name2 = "Sale Order", desc1 = "", desc2 = "", module = "Sale Order", menutype = "H1", parrentmenu = "01-001", path = "SO", icon = "fas fa-file-contract text-hover-primary fs-2x pr-3", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "01-002", name1 = "จองสินค้า", name2 = "Order", desc1 = "", desc2 = "", module = "Sale Order", menutype = "H2", parrentmenu = "01-001", path = "SO", icon = "", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "01-003", name1 = "บันทึกเสนอราคา", name2 = "Quotation", desc1 = "เพิ่ม/แก้ไข ใบเสนอราคา เพื่อนำเสนอราคาให้กับลูกค้าพิจราณา", desc2 = "Add/edit quotation", module = "Sale Order", menutype = "S", parrentmenu = "01-002", path = "SO/QT", icon = "fa fa-file-contract fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "01-004", name1 = "บันทึกสั่งขาย", name2 = "Sale Order", desc1 = "เพิ่ม/แก้ไข ใบสั่งขาย บันทึกเมื่อลูกค้าสั่งซื้อสินค้าหรือเมื่อได้รับเอกสารใบสั่งซื้อ(PO) จากลูกค้า", desc2 = "Add/edit sale order", module = "Sale Order", menutype = "S", parrentmenu = "01-002", path = "SO/SO", icon = "fa fa-file-signature fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "02-001", name1 = "ขายเชื่อ", name2 = "Accounts Receivable", desc1 = "", desc2 = "", module = "Sale", menutype = "H1", parrentmenu = "02-001", path = "AR", icon = "fas fa-file-invoice text-hover-primary fs-2x pr-3", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "02-002", name1 = "ตั้งลูกหนี้การค้า", name2 = "Sales Bill", desc1 = "", desc2 = "", module = "Sale", menutype = "H2", parrentmenu = "02-001", path = "Invoice", icon = "", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "02-003", name1 = "ขายเชื่อ", name2 = "Sales Invoice", desc1 = "เพิ่ม/แก้ไข บิลขาย(ใบกำกับภาษี/ใบแจ้งหนี้/ใบส่งสินค้า) เพื่อตั้งหนี้ลูกหนี้การค้า สามารถเพิมใหม่หรือแก้ไขบิลเดิม", desc2 = "Add/edit sales tax invoice", module = "Sale", menutype = "S", parrentmenu = "02-002", path = "Invoice/SOC", icon = "fa fa-file-invoice fa-3x", command = "IVS; SIV", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu
            {
                code = "02-004",
                name1 = "ลดหนี้",
                name2 = "Sales Credit Note",
                desc1 = "เพิ่ม/แก้ไข ลดหนี้(ใบกำกับภาษี/ใบลดหนี้) เพื่อลดหนี้ลูกหนี้การค้าโดยกำหนดคืนสินค้าหรือคืนเงิน สามารถเพิมใหม่หรือแก้ไขบิลเดิม",
                desc2 = "Add/edit sales credit note",
                module = "Sale",
                menutype = "S",
                parrentmenu = "02-002",
                path = "Invoice/CN",
                icon = "fa fa-file-download fa-3x",
                command = "SALE;CNS;SCN",
                createatutc = DateTime.Now,
                updateatutc = DateTime.Now
            });
            menus.Add(new Menu
            {
                code = "02-005",
                name1 = "เพิ่มหนี้",
                name2 = "Sales Debit Note",
                desc1 = "เพิ่ม/แก้ไข เพิ่มหนี้(ใบกำกับภาษี/ใบเพิ่มหนี้)เพื่อเพิ่มหนี้ลูกหนี้การค้าโดยกำหนดเพิ่มสินค้าหรือเพิ่มเงิน สามารถเพิมใหม่หรือแก้ไขบิลเดิม",
                desc2 = "Add/edit sales debit note",
                module = "Sale",
                menutype = "S",
                parrentmenu = "02-002",
                path = "Invoice/DN",
                icon = "fa fa-file-upload fa-3x",
                command = "SALE;DNS;SDN",
                createatutc = DateTime.Now,
                updateatutc = DateTime.Now
            });
            menus.Add(new Menu { code = "02-009", name1 = "เงินมัดจำรับ", name2 = "Deposit Received", desc1 = "เพิ่ม/แก้ไข เงินมัดจำรับล่วงหน้า เพื่อตั้งหนี้ลูกหนี้เงินมัดจำรับล่วงหน้า สามารถเพิมใหม่หรือแก้ไขบิลเดิม", desc2 = "Add/edit advance deposit receipts", module = "Sale", menutype = "S", parrentmenu = "02-002", path = "Invoice/DR", icon = "fa fa-file-contract fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "03-001", name1 = "รับชำระ", name2 = "Receipt", desc1 = "", desc2 = "", module = "Receipt", menutype = "H1", parrentmenu = "03-001", path = "Receipt", icon = "fas fa-receipt text-hover-primary fs-2x pr-3", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "03-002", name1 = "ขายสด", name2 = "cash Sales bill", desc1 = "", desc2 = "", module = "Receipt", menutype = "H2", parrentmenu = "03-001", path = "Receipt", icon = "", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "03-003", name1 = "บิลเงินสด", name2 = "cash Sell", desc1 = "เพิ่ม/แก้ไข บิลขายสด(ใบกำกับภาษี/ใบเสร็จรับเงิน) เพื่อตั้งหนี้ลูกหนี้การค้า สามารถเพิมใหม่หรือแก้ไขบิลเดิม", desc2 = "", module = "Receipt", menutype = "S", parrentmenu = "03-002", path = "-", icon = "fa fa-file-invoice fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "03-004", name1 = "ลดหนี้", name2 = "cash Sell Credit Note", desc1 = "เพิ่ม/แก้ไข ลดหนี้เงินสด(ใบกำกับภาษี/ใบลดหนี้/ใบเสร็จรับเงิน) เพื่อลดหนี้ลูกค้าโดยกำหนดคืนสินค้าหรือคืนเงิน สามารถเพิมใหม่หรือแก้ไขบิลเดิม", desc2 = "", module = "Receipt", menutype = "S", parrentmenu = "03-002", path = "-", icon = "fa fa-file-download fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "03-005", name1 = "เพิ่มหนี้ ", name2 = "cash Sell Debit Note", desc1 = "เพิ่ม/แก้ไข เพิ่มหนี้(ใบกำกับภาษี/ใบเพิ่มหนี้/ใบเสร็จรับเงิน) เพื่อเพิ่มหนี้ลูกค้าโดยกำหนดเพิ่มสินค้าหรือเพิ่มเงิน สามารถเพิมใหม่หรือแก้ไขบิลเดิม", desc2 = "", module = "Receipt", menutype = "S", parrentmenu = "03-002", path = "-", icon = "fa fa-file-upload fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "03-006", name1 = "รับเงินมัดจำ", name2 = "cash Sell Deposit", desc1 = "เพิ่ม/แก้ไข รับเงินมัดจำรับล่วงหน้า(ใบกำกับภาษี/ใบเสร็จรับเงิน) เพื่อเพิ่มหนี้ลูกค้าโดยกำหนดเพิ่มสินค้าหรือเพิ่มเงิน สามารถเพิมใหม่หรือแก้ไขบิลเดิม", desc2 = "", module = "Receipt", menutype = "S", parrentmenu = "03-002", path = "-", icon = "fa fa-file-invoice-dollar fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "03-007", name1 = "ตามหนี้", name2 = "cash Sales bill", desc1 = "", desc2 = "", module = "Receipt", menutype = "H2", parrentmenu = "03-001", path = "Receipt", icon = "", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "03-008", name1 = "ใบวางบิล", name2 = "Bill", desc1 = "เพิ่ม/แก้ไข ใบวางบิล บันทึกเอกสารวางบิลเพื่อทำการวางบิลลูกค้าเหมือนเป็นการหนี้ลูกค้าก่อนรับชำระเงิน", desc2 = "Add/edit bill", module = "Receipt", menutype = "S", parrentmenu = "03-007", path = "Bill/RL", icon = "fa fa-receipt fa-3x", command = "RBL", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "03-009", name1 = "สร้างใบวางบิลอัตโนมัติ", name2 = "Auto Generate billing", desc1 = "สร้างใบวางบิลอัตโนมัติ ใช้ในกรณีต้องการให้โปรแกรม Generate Bill Auto โดยสร้างจากเงื่อนไขในการกำหนดการวางบิล", desc2 = "", module = "Receipt", menutype = "S", parrentmenu = "03-007", path = "-", icon = "fa fa-file-import fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "03-010", name1 = "ใบเสร็จรับเงิน", name2 = "cash Sales bill", desc1 = "", desc2 = "", module = "Receipt", menutype = "H2", parrentmenu = "03-001", path = "Receipt", icon = "", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "03-011", name1 = "ใบเสร็จก่อนรับเงิน", name2 = "Prepare Receipt", desc1 = "เพิ่ม/แก้ไข ใบเสร็จ ก่อนการรับเงิน(ใบเสร็จรับเงิน) ใบเสร็จก่อนรับเงินเปรียบเสมือนการพิมพ์ใบเสร็จเพื่อนำไปเก็บเงินและให้ลูกค้า แต่ระบบยังไม่ตัดลูกหนี้การค้า เนื่องจากยังไม่ได้รับเงินจริง", desc2 = "Add/edit prepare receipt", module = "Receipt", menutype = "S", parrentmenu = "03-010", path = "Receipt/RP", icon = "fa fa-file-powerpoint fa-3x", command = "RPR; RPI ", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "03-012", name1 = "ใบเสร็จรับเงิน", name2 = "Receipt", desc1 = "เพิ่ม/แก้ไข ใบเสร็จรับเงิน บันทึกเมื่อมีการได้รับเงินจากลูกค้าเรียบร้อย โปรแกรมจะทำการล้างลูกหนี้การค้าออกจากระบบ ", desc2 = "Add/edit receipt", module = "Receipt", menutype = "S", parrentmenu = "03-010", path = "Receipt/RE", icon = "fa fa-receipt fa-3x", command = "RRE; RIV ", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "04-001", name1 = "สั่งซื้อสินค้า", name2 = "Purchase Order", desc1 = "", desc2 = "", module = "Purchase order", menutype = "H1", parrentmenu = "04-001", path = "Purchase order", icon = "fas fa-file-contract text-hover-primary fs-2x pr-3", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "04-002", name1 = "สั่งซื้้อ", name2 = "Purchase Order", desc1 = "", desc2 = "", module = "Purchase order", menutype = "H2", parrentmenu = "04-001", path = "PO", icon = "", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "04-003", name1 = "ใบขอซื้อ", name2 = "Purchase Request", desc1 = "", desc2 = "", module = "Purchase order", menutype = "S", parrentmenu = "04-002", path = "-", icon = "fa fa-file-contract fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "04-004", name1 = "ใบสั่งซื้อ", name2 = "Purchase Order", desc1 = "", desc2 = "", module = "Purchase order", menutype = "S", parrentmenu = "04-002", path = "-", icon = "fa fa-file-signature fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "05-001", name1 = "ซื้้อเชื่อ", name2 = "Accounts Payable", desc1 = "", desc2 = "", module = "Purchase", menutype = "H1", parrentmenu = "05-001", path = "Purchase", icon = "fas fa-file-invoice text-hover-primary fs-2x pr-3", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "05-002", name1 = "ตั้งเจ้าหนี้การค้า", name2 = "Purchase Bill", desc1 = "", desc2 = "", module = "Purchase", menutype = "H2", parrentmenu = "05-001", path = "", icon = "", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "05-003", name1 = "ซื้อเชื่อ", name2 = "Purchase Tax Invoice", desc1 = "", desc2 = "", module = "Purchase", menutype = "S", parrentmenu = "05-002", path = "-", icon = "fa fa-file-invoice fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "05-004", name1 = "ลดหนี้", name2 = "Purchase Credit note", desc1 = "", desc2 = "", module = "Purchase", menutype = "S", parrentmenu = "05-002", path = "-", icon = "fa fa-file-alt fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "05-005", name1 = "เพิ่มหนี้", name2 = "Purchase Debit note", desc1 = "", desc2 = "", module = "Purchase", menutype = "S", parrentmenu = "05-002", path = "-", icon = "fa fa-file-upload fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "05-006", name1 = "เงินมัดจำจ่าย", name2 = "Advance Dposit Paid", desc1 = "", desc2 = "", module = "Purchase", menutype = "S", parrentmenu = "05-002", path = "-", icon = "fa fa-file-invoice-dollar fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "06-001", name1 = "จ่ายชำระ", name2 = "Payment", desc1 = "", desc2 = "", module = "Payment", menutype = "H1", parrentmenu = "06-001", path = "Payment", icon = "fas fa-receipt text-hover-primary fs-2x pr-3", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "06-002", name1 = "ซื้นสด", name2 = "cash Purchase bill", desc1 = "", desc2 = "", module = "Payment", menutype = "H2", parrentmenu = "06-001", path = "", icon = "", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "06-003", name1 = "บิลเงินสด", name2 = "cash Buy", desc1 = "", desc2 = "", module = "Payment", menutype = "S", parrentmenu = "06-002", path = "-", icon = "fa fa-file-invoice fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "06-004", name1 = "ลดหนี้ ", name2 = "cash Buy Credit Note", desc1 = "", desc2 = "", module = "Payment", menutype = "S", parrentmenu = "06-002", path = "-", icon = "fa fa-file-alt fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "06-005", name1 = "เพิ่มหนี้ ", name2 = "cash Buy Debit Note", desc1 = "", desc2 = "", module = "Payment", menutype = "S", parrentmenu = "06-002", path = "-", icon = "fa fa-file-upload fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "06-006", name1 = "จ่ายเงินมัดจำ", name2 = "cash Buy Deposit", desc1 = "", desc2 = "", module = "Payment", menutype = "S", parrentmenu = "06-002", path = "-", icon = "fa fa-file-invoice-dollar fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "06-007", name1 = "ตามหนี้ี้", name2 = "Payment", desc1 = "", desc2 = "", module = "Payment", menutype = "H2", parrentmenu = "06-001", path = "Payment", icon = "", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "06-008", name1 = "รับใบวางบิล", name2 = "Billing", desc1 = "", desc2 = "", module = "Payment", menutype = "S", parrentmenu = "06-007", path = "Bill/RL", icon = "fa fa-receipt fa-3x", command = "PBL", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "06-009", name1 = "ใบเสร็จจ่ายชำระ", name2 = "Payment", desc1 = "", desc2 = "", module = "Payment", menutype = "H2", parrentmenu = "06-001", path = "Payment", icon = "", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "06-010", name1 = "ใบเสร็จก่อนการจ่ายชำระ", name2 = "Prepare Payment", desc1 = "", desc2 = "", module = "Payment", menutype = "S", parrentmenu = "06-009", path = "-", icon = "file-powerpoint fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "06-011", name1 = "ใบเสร็จจ่าย", name2 = "Payment Receipt", desc1 = "", desc2 = "", module = "Payment", menutype = "S", parrentmenu = "06-009", path = "-", icon = "fa fa-receipt fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });

            menus.Add(new Menu { code = "07-001", name1 = "สินค้าคงคลัง", name2 = "Inventory", desc1 = "", desc2 = "", module = "Inventory", menutype = "H1", parrentmenu = "07-001", path = "Inventory", icon = "fas fa-boxes text-hover-primary fs-2x pr-3", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "07-002", name1 = "บันทึกใบรับ/ส่ง สินค้าชั่วคราว", name2 = "Delivery", desc1 = "", desc2 = "", module = "Inventory", menutype = "H2", parrentmenu = "07-001", path = "", icon = "", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "07-003", name1 = "ใบรับสินค้าชั่วคราว", name2 = "Delivery Order", desc1 = "", desc2 = "", module = "Inventory", menutype = "S", parrentmenu = "07-002", path = "", icon = "fa fa-file-import fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "07-004", name1 = "ใบสั่่งสินค้าชั่วคราว", name2 = "Goods received", desc1 = "", desc2 = "", module = "Inventory", menutype = "S", parrentmenu = "07-002", path = "", icon = "fa fa-file-export fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "07-005", name1 = "บันทึกการยืมสินค้า", name2 = "Borrow", desc1 = "", desc2 = "", module = "Inventory", menutype = "H2", parrentmenu = "07-001", path = "", icon = "", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "07-006", name1 = "ใบขอยืมสินค้า", name2 = "Product Loan Request", desc1 = "", desc2 = "", module = "Inventory", menutype = "S", parrentmenu = "07-005", path = "-", icon = "fa fa-file-contract fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "07-007", name1 = "ใบยืมสินค้า", name2 = "Borrowing form", desc1 = "", desc2 = "", module = "Inventory", menutype = "S", parrentmenu = "07-005", path = "-", icon = "fa fa-file-signature fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "07-008", name1 = "ใบคืนสินค้าจากการยืม", name2 = "Borrowing Note from loan   ", desc1 = "", desc2 = "", module = "Inventory", menutype = "S", parrentmenu = "07-005", path = "-", icon = "fa fa-file-upload fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "07-009", name1 = "บันทึกโอนสินค้า", name2 = "Transfer", desc1 = "", desc2 = "", module = "Inventory", menutype = "H2", parrentmenu = "07-001", path = "", icon = "", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "07-010", name1 = "ใบขอโอนสินค้าระหว่างคลัง", name2 = "Warehouse Transfer Requset", desc1 = "", desc2 = "", module = "Inventory", menutype = "S", parrentmenu = "07-009", path = "-", icon = "fa fa-file-code fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "07-011", name1 = "ใบโอนระหว่างคลัง", name2 = "Warehouse Transfer", desc1 = "", desc2 = "", module = "Inventory", menutype = "S", parrentmenu = "07-009", path = "-", icon = "fa fa-file-code fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "07-012", name1 = "ใบขอโอนสินค้าระหว่างสาขา", name2 = "Branch Transfer Request", desc1 = "", desc2 = "", module = "Inventory", menutype = "S", parrentmenu = "07-009", path = "-", icon = "fa fa-file-alt fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "07-013", name1 = "ใบโอนระหว่างสาขา", name2 = "Branch Transfer", desc1 = "", desc2 = "", module = "Inventory", menutype = "S", parrentmenu = "07-009", path = "-", icon = "fa fa-file-alt fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "07-014", name1 = "บันทึกเบิก/จ่ายระหว่างผลิต", name2 = "Requisition", desc1 = "", desc2 = "", module = "Inventory", menutype = "H2", parrentmenu = "07-001", path = "", icon = "", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "07-015", name1 = "ใบขอเบิกวัตถุดิบ", name2 = "Requisition", desc1 = "", desc2 = "", module = "Inventory", menutype = "S", parrentmenu = "07-014", path = "-", icon = "fa fa-file-code fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "07-016", name1 = "ใบเบิกวัตถุดิบ", name2 = "Raw material requisition", desc1 = "", desc2 = "", module = "Inventory", menutype = "S", parrentmenu = "07-014", path = "-", icon = "fa fa-file-code fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "07-017", name1 = "ใบรับสินค้าสำเร็จรูป", name2 = "Finished goods receipt", desc1 = "", desc2 = "", module = "Inventory", menutype = "S", parrentmenu = "07-014", path = "-", icon = "fa fa-file-alt fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "07-018", name1 = "บันทึกต้นทุนการผลิต", name2 = "Production Cost", desc1 = "", desc2 = "", module = "Inventory", menutype = "S", parrentmenu = "07-014", path = "-", icon = "fa fa-file-alt fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "07-019", name1 = "บันทึกปรับปรุงยอดสินค้า", name2 = "Adjust stock", desc1 = "", desc2 = "", module = "Inventory", menutype = "H2", parrentmenu = "07-001", path = "", icon = "", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "07-020", name1 = "ใบปรับยอด", name2 = "Adjust inventory", desc1 = "", desc2 = "", module = "Inventory", menutype = "S", parrentmenu = "07-019", path = "-", icon = "fa fa-stack-overflow fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "07-021", name1 = "ใบตรวจนับสต๊อก", name2 = "Check inventory", desc1 = "", desc2 = "", module = "Inventory", menutype = "S", parrentmenu = "07-019", path = "-", icon = "fa fa-file-image-check fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "07-022", name1 = "รายงานสินค้าคงเหลือ", name2 = "Inventory Report", desc1 = "", desc2 = "", module = "Inventory", menutype = "H2", parrentmenu = "07-001", path = "", icon = "", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });


            menus.Add(new Menu { code = "08-001", name1 = "สินทรัพย์", name2 = "Fixed Asset", desc1 = "", desc2 = "", module = "Asset", menutype = "H1", parrentmenu = "08-001", path = "Asset", icon = "fas fa-building text-hover-primary fs-2x pr-3", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "08-002", name1 = "คำนวณ", name2 = "Generate", desc1 = "", desc2 = "", module = "Asset", menutype = "H2", parrentmenu = "08-001", path = "", icon = "", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "08-003", name1 = "ประมวลผลค่าเสื่อมราคา", name2 = "Generate Depreciation", desc1 = "", desc2 = "", module = "Asset", menutype = "S", parrentmenu = "08-002", path = "-", icon = "fa fa-play fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "08-004", name1 = "ประมวลผลเบี้ยประกันภัย", name2 = "Generate Premium", desc1 = "", desc2 = "", module = "Asset", menutype = "S", parrentmenu = "08-002", path = "-", icon = "fa fa-play fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "08-005", name1 = "แก้ไขมูคค่าค่าเสื่อมราคา", name2 = "Edti Depreciation", desc1 = "", desc2 = "", module = "Asset", menutype = "S", parrentmenu = "08-002", path = "-", icon = "fa fa-reply-all fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "08-006", name1 = "แก้ไขมูคค่าเบี้ยประกันภัย", name2 = "Edti Premius", desc1 = "", desc2 = "", module = "Asset", menutype = "S", parrentmenu = "08-002", path = "-", icon = "fa fa-repl fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "08-007", name1 = "บันทึกค่าซ่อมแซม", name2 = "Repair cost", desc1 = "", desc2 = "", module = "Asset", menutype = "S", parrentmenu = "08-002", path = "-", icon = "fa fa-file-contract fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "08-008", name1 = "ทะเบียนทรัพย์สิน", name2 = "fax Asset Master", desc1 = "บันทึกรายการทรัพย์สินของบริษัท", desc2 = "Company property records", module = "Database", menutype = "H2", parrentmenu = "08-001", path = "Database/Fixedasset", icon = "", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "08-009", name1 = "ทะเบียนทรัพย์สิน", name2 = "Asset register", desc1 = "เพิ่ม/แก้ไข รายชื่อทรัพย์สินของบริษัท เพื่อเก็บเป็นทะเบียน และใช้ในการคำนวณค่าเสื่อมราคา", desc2 = "Add/edit the list of company assets To be registered And used to calculate depreciation", module = "Database", menutype = "S", parrentmenu = "08-008", path = "Database/Asset", icon = "fa fa-building fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "08-010", name1 = "กลุ่มทรัพย์สิน", name2 = "Asset group", desc1 = "เพิ่ม/แก้ไข กลุ่มทรัพย์สินของบริษัท เพื่อจัดหมวดหมู่ของสินทรัยพ์ และกำหนดรหัสบัญชีให้ในกลุ่มสินทรัพย์ในการใช้คำนวณค่าเสื่อมราคา", desc2 = "Add/Edit group of Company Assets To categorize assets And assign an accounting code to the asset group for use in depreciation", module = "Database", menutype = "S", parrentmenu = "08-008", path = "Database/AssetGroup", icon = "fa fa-city fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "08-011", name1 = "บันทึกเบี้ยประภัย", name2 = "Insure", desc1 = "เพิ่ม/แก้ไข เบี้ยประกันภัยของทรัพย์สิน เพื่อนำไปคำนวณ และลงบัญชีค่าใช้จ่าย", desc2 = "Add/edit property insurance premiums To calculate And account for expenses", module = "Database", menutype = "S", parrentmenu = "08-008", path = "Database/Insure", icon = "fa fa-car-crash fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "09-001", name1 = "บัญชีแยกประเภท", name2 = "General Ledger", desc1 = "", desc2 = "", module = "GL", menutype = "H1", parrentmenu = "09-001", path = "GL", icon = "fas fa-file-signature text-hover-primary fs-2x pr-3", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "09-002", name1 = "บันทึกรายวัน", name2 = "Ledger account", desc1 = "", desc2 = "", module = "GL", menutype = "H2", parrentmenu = "09-001", path = "GL", icon = "", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "09-003", name1 = "รายวันทั่วไป", name2 = "General Journal", desc1 = "บันทึกรายการบัญชีรายวันแยกประเภทรายการทั่วไป", desc2 = "", module = "GL", menutype = "S", parrentmenu = "09-002", path = "GL/GLM", icon = "fa fa-file-alt fa-3x", command = "JV", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "09-004", name1 = "รายวันซื้อ", name2 = "Purchase Journal", desc1 = "บันทึกรายการบัญชีรายวันแยกประเภทรายการตั้งหนี้ซื้อ", desc2 = "", module = "GL", menutype = "S", parrentmenu = "09-002", path = "GL/GLM", icon = "fa fa-file-contract fa-3x", command = "AP", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "09-005", name1 = "รายวันจ่าย", name2 = "Payment Voucher", desc1 = "บันทึกรายการบัญชีรายวันแยกประเภทรายการจ่ายชำระ", desc2 = "", module = "GL", menutype = "S", parrentmenu = "09-002", path = "GL/GLM", icon = "fa fa-file-3x", command = "PV", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "09-006", name1 = "รายวันขาย", name2 = "Sales journal", desc1 = "บันทึกรายการบัญชีรายวันแยกประเภทรายการตั้ั้งหนี้ขาย", desc2 = "", module = "GL", menutype = "S", parrentmenu = "09-002", path = "GL/GLM", icon = "fa fa-file-invoice fa-3x", command = "AR", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "09-007", name1 = "รายวันรับ", name2 = "Receipt journal", desc1 = "บันทึกรายการบัญชีรายวันแยกประเภทรายการรับชำระ", desc2 = "", module = "GL", menutype = "S", parrentmenu = "09-002", path = "GL/GLM", icon = "fa fa-file-invoice-dollar fa-3x", command = "SV", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "09-008", name1 = "เงินสดย่อย", name2 = "Petty cash", desc1 = "", desc2 = "", module = "GL", menutype = "H2", parrentmenu = "09-001", path = "", icon = "", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "09-009", name1 = "บันทึกภาษี", name2 = "vat Register", desc1 = "", desc2 = "", module = "GL", menutype = "H2", parrentmenu = "09-001", path = "", icon = "", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "09-010", name1 = "บันทึกภาษีหัก ณ ที่จ่าย", name2 = "Withholding tax Register", desc1 = "", desc2 = "", module = "GL", menutype = "S", parrentmenu = "09-009", path = "", icon = "fa fa-file-alt fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "09-011", name1 = "งบประมาณ", name2 = "Budget", desc1 = "", desc2 = "", module = "GL", menutype = "H2", parrentmenu = "09-001", path = "", icon = "", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "09-012", name1 = "รายงานภาษี", name2 = "Tax Report", desc1 = "", desc2 = "", module = "GL", menutype = "H2", parrentmenu = "09-001", path = "", icon = "", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "09-013", name1 = "รายงานแยกประเภท", name2 = "Ledger report", desc1 = "", desc2 = "", module = "GL", menutype = "H2", parrentmenu = "09-001", path = "", icon = "", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "09-014", name1 = "รายงานงบการเงิน", name2 = "Financial statement", desc1 = "", desc2 = "", module = "GL", menutype = "H2", parrentmenu = "09-001", path = "", icon = "", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "09-015", name1 = "รายงานงบประมาณ", name2 = "Budget report", desc1 = "", desc2 = "", module = "GL", menutype = "H2", parrentmenu = "09-001", path = "", icon = "", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "09-016", name1 = "แบบฟอร์มงบ", name2 = "Financial Form Design", desc1 = "", desc2 = "", module = "GL", menutype = "H2", parrentmenu = "09-001", path = "", icon = "", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "10-001", name1 = "ธนาคาร", name2 = "Bank documents", desc1 = "", desc2 = "", module = "Bank", menutype = "H1", parrentmenu = "10-001", path = "Bank", icon = "fas fa-file-invoice-dollar text-hover-primary fs-2x pr-3", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "10-002", name1 = "บันทึกเอกสาร", name2 = "Bank Documents", desc1 = "", desc2 = "", module = "Bank", menutype = "H2", parrentmenu = "10-001", path = "Bank", icon = "", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "10-003", name1 = "บันทึกเคลื่องไหว", name2 = "Bank Transaction", desc1 = "เพิ่ม/แก้ไข เอกสารการเคลื่อนไหวของสมุดบัญชีเงินฝาก การใช้เมนูนี้ไม่มีผลกับการบันทึกรายวันทางบัญชี", desc2 = "Add/edit passbook movement document This menu operation has no effect on accounting journals", module = "Bank", menutype = "S", parrentmenu = "10-002", path = "Bank", icon = "fa fa-file-medical-alt fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "10-004", name1 = "บันทึกใบนำฝาก", name2 = "Bank deposit", desc1 = "เพิ่ม/แก้ไข ใบนำฝากธนาคาร ใช้ในกรณีต้องการนำฝากเช็ครับ, ฝากเงินสด เป็นต้น การบันทึกที่เมนูนี้โปรแกรมจะบันทึกรายวันที่ระบบบัญชีให้อัตโนมัติ", desc2 = "Add/edit Bank deposit Used in the event of a check deposit, cash deposit, etc.Save at this menu, the program will automatically record the daily accounting system", module = "Bank", menutype = "S", parrentmenu = "10-002", path = "Bank", icon = "fa fa-file-invoice-dollar fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "10-005", name1 = "บันทึกเช็ครับที่ผ่าน(บันทึกบัญชี)", name2 = "Pass Cheque", desc1 = "", desc2 = "", module = "Bank", menutype = "S", parrentmenu = "10-002", path = "Bank", icon = "fa fa-money-check fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "10-006", name1 = "บันทึกประวัติเช็คคืน", name2 = "Return Cheque", desc1 = "", desc2 = "", module = "Bank", menutype = "S", parrentmenu = "10-002", path = "Bank", icon = "fa fa-money-check-alt fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "10-007", name1 = "กลับรายการเช็คจ่าย(บันทึกบัญชี)", name2 = "Reversing Entries Cheque", desc1 = "", desc2 = "", module = "Bank", menutype = "S", parrentmenu = "10-002", path = "Bank", icon = "fa fa-credit-card fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "10-008", name1 = "บันทึกเช็คจ่ายที่ผ่าน(ไม่บันทึกบัญชี)", name2 = "Pass Pay cheque", desc1 = "", desc2 = "", module = "Bank", menutype = "S", parrentmenu = "10-002", path = "Bank", icon = "fa fa-money-bill fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "10-009", name1 = "โอนระหว่างสมุดบัญชี", name2 = "Bank Transfer", desc1 = "", desc2 = "", module = "Bank", menutype = "S", parrentmenu = "10-002", path = "Bank", icon = "fa fa-copy fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "10-009", name1 = "รายงานเอกสารธนาคาร", name2 = "Bank statement Report", desc1 = "", desc2 = "", module = "Bank", menutype = "H2", parrentmenu = "10-001", path = "Bank", icon = "", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-001", name1 = "ฐานข้อมูล", name2 = "Master data", desc1 = "บันทึกฐานข้อมูลทะบียนรายชื่อที่ต้องนำไปใช้ในการบันทึกเอกสารต่าง ๆ ในระบบ", desc2 = "Record a list of names that must be used for saving documents in the system", module = "Database", menutype = "H1", parrentmenu = "11-001", path = "Database", icon = "fas fa-database text-hover-primary fs-2x pr-3", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-002", name1 = "ลูกค้า", name2 = "Sales Master", desc1 = "บันทึกข้อมูลทะเบียนราชื่อที่ต้องนำไปใช้ในระบบขายสินค้า", desc2 = "Record the registration information of the name1 that must be used in the selling system", module = "Database", menutype = "H2", parrentmenu = "11-001", path = "Database/Sales", icon = "", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-003", name1 = "ทะเบียนลูกค้า", name2 = "customer", desc1 = "เพิ่ม/แก้ไข รายชื่อลูกค้า เพื่อนำไปใช้ในการบันทึกเอกสารระบบขาย", desc2 = "Add/edit customer list For use in documenting sales systems", module = "Database", menutype = "S", parrentmenu = "11-002", path = "Database/customer", icon = "fa fa-id-card fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-004", name1 = "กลุ่มลูกค้า", name2 = "customer group", desc1 = "เพิ่ม/แก้ไข รายชื่อกลุ่มลูกค้า เพื่อประโยชน์ในการตรวจสอบการขายแยกตามกลุ่มลูกค้า", desc2 = "Add/edit customer groups For the benefit of monitoring sales by customer groups", module = "Database", menutype = "S", parrentmenu = "11-002", path = "Database/CustGroup", icon = "fa fa-users fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-005", name1 = "พนักงานขาย", name2 = "Sales person", desc1 = "เพิ่ม/แก้ไข รายชื่อพนักงานขาย เพื่อตรวจสอบการขายแยกตามพนักงาน และคำนวณค่าคอมมิชชั่น", desc2 = "Add/edit the list of sales staff To monitor sales by employees And calculate the commission", module = "Database", menutype = "S", parrentmenu = "11-002", path = "Database/SaleMan", icon = "fa fa-user-tie fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-006", name1 = "ทีมขาย", name2 = "Sales team", desc1 = "เพิ่ม/แก้ไข รายชื่อทีมขายเพื่อตรวจสอบยอดขายแยกแยกตามทีม", desc2 = "Add/edit sales team lists to monitor sales separately by teams", module = "Database", menutype = "S", parrentmenu = "11-002", path = "Database/SaleTeam", icon = "fa fa-users-cog fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-007", name1 = "เขตการขาย", name2 = "Territory", desc1 = "เพิ่ม/แก้ไข รายชื่อเขตการขายเพื่อตรวจสอบยอดขายแยกตามเขตของลูกค้า", desc2 = "Add/edit a list of sales territories to check sales by region of the customer", module = "Database", menutype = "S", parrentmenu = "11-002", path = "Database/Territory", icon = "fa fa-map fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-008", name1 = "ส่วนแบ่งการตลาด", name2 = "Seqment", desc1 = "เพิ่ม/แก้ไข รายชื่อส่วนแบ่งการตลาดเพื่อวิเคราะมูลค่าส่วนแบ่งการตลาดแยกตามลูกค้า", desc2 = "Add/edit market share list to analyze market share value by customer", module = "Database", menutype = "S", parrentmenu = "11-002", path = "Database/Seqment", icon = "fa fa-globe fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-009", name1 = "ราคาขาย", name2 = "price list", desc1 = "เพิ่ม/แก้ไข ราคาสินค้าตามผู้จำหน่ายแต่ละรายเพื่อนำไปใช้ในเอกสารซื้อซึ่งจะแสดงราคาซื้อตามผู้จำหน่าย", desc2 = "", module = "Database", menutype = "S", parrentmenu = "11-002", path = "Database/PriceList", icon = "fa fa-tag fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-010", name1 = "ราคาขายตามลูกค้า", name2 = "price list customer", desc1 = "เพิ่ม/แก้ไข ราคาสินค้าตามผู้จำหน่ายแต่ละรายเพื่อนำไปใช้ในเอกสารซื้อซึ่งจะแสดงราคาซื้อตามผู้จำหน่าย", desc2 = "Add/edit product prices by individual vendor for use in purchase documents, which will display purchase prices by vendor", module = "Database", menutype = "S", parrentmenu = "11-002", path = "Database/PriceListCust", icon = "fa fa-tags fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-011", name1 = "ผู้จำหน่าย", name2 = "Purchase Master", desc1 = "บันทึกข้อมูลทะเบียนราชื่อที่ต้องนำไปใช้ในระบบขายสินค้า", desc2 = "Record the registration information of the name1 that must be used in the selling system", module = "Database", menutype = "H2", parrentmenu = "11-001", path = "Database/Purchase", icon = "", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-012", name1 = "ทะเบียนผู้จำหน่าย", name2 = "vendor", desc1 = "เพิ่ม/แก้ไข รายชื่อผู้จำหน่าย เพื่อนำไปใช้ในการบันทึกเอกสารระบบซื้อ", desc2 = "Add/edit supplier list To be used for documenting the purchase system", module = "Database", menutype = "S", parrentmenu = "11-011", path = "Database/vendor", icon = "fa fa-id-card fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-013", name1 = "กลุ่มผู้จำหน่าย", name2 = "vendor group", desc1 = "เพิ่ม/แก้ไข รายชื่อกลุ่มผู้จำหน่ายเพื่อประโยชน์ในการตรวจสอบการขายแยกตามกลุ่มผู้จำหน่าย", desc2 = "Add/edit a list of vendors for the benefit of monitoring sales by dealer group", module = "Database", menutype = "S", parrentmenu = "11-011", path = "Database/VenderGrp", icon = "fa fa-users fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-014", name1 = "ราคาขาย", name2 = "price list", desc1 = "เพิ่ม/แก้ไข ราคาสินค้าตามผู้จำหน่ายแต่ละรายเพื่อนำไปใช้ในเอกสารซื้อซึ่งจะแสดงราคาซื้อตามผู้จำหน่าย", desc2 = "", module = "Database", menutype = "S", parrentmenu = "11-011", path = "Database/PriceList", icon = "fa fa-tag fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-015", name1 = "ราคาขายผู้จำหน่าย", name2 = "price list vendor", desc1 = "เพิ่ม/แก้ไข ราคาสินค้าตามผู้จำหน่ายแต่ละรายเพื่อนำไปใช้ในเอกสารซื้อซึ่งจะแสดงราคาซื้อตามผู้จำหน่าย", desc2 = "Add/edit product prices by individual vendor for use in purchase documents, which will display purchase prices by vendor", module = "Database", menutype = "S", parrentmenu = "11-011", path = "Database/PriceListVendor", icon = "fa fa-tags fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-016", name1 = "สินค้า", name2 = "Inventory Master", desc1 = "บันทึกข้อมูลเกี่ยวกับสินค้าคงคลัง รายชื่อสินค้า กลุ่มสินค้า อื่นๆ", desc2 = "Add/edit inventory information List of other products", module = "Database", menutype = "H2", parrentmenu = "11-001", path = "Database/Product", icon = "", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-017", name1 = "ทะเบียนสินค้า", name2 = "Products", desc1 = "เพิ่ม/แก้ไข รายการสินค้า, วัตถุดิบ, สินทรัพย์ หรือรายการใด ๆ เพื่อนำไปใช้กับเอกสารซื้อ-ขาย", desc2 = "Add/edit a list of products, materials, assets or any items for use in the documents.", module = "Database", menutype = "S", parrentmenu = "11-016", path = "Database/Prod", icon = "fa fa-qrcode fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-018", name1 = "ทะเบียนงานบริการ", name2 = "service", desc1 = "เพิ่ม/แก้ไข รายการรายได้บริการ และ ค่าใช้จ่ายเพื่อนำไปใช้กับเอกสารซื้อ-ขาย", desc2 = "Add/edit items of income, services and expenses to be applied to the documents.", module = "Database", menutype = "S", parrentmenu = "11-016", path = "Database/service", icon = "fa fa-barcode fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-019", name1 = "เพิ่มชุดสินค้า", name2 = "Product set", desc1 = "เพิ่ม/แก้ไข ชุดสินค้า เป็นการจัดประกอบสินค้าเพื่อแสดงการขายเป็นชุด ", desc2 = "Add/edit product batches, assemble products to show selling as a set.", module = "Database", menutype = "S", parrentmenu = "11-016", path = "Database/ProductSet", icon = "fa fa-cubes fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-020", name1 = "หน่วยนับ", name2 = "Unit", desc1 = "เพิ่ม/แก้ไข หน่วยนับสินค้า เพื่อนำไปใช้เพื่อระบุหน่วยของสินค้าแต่ละรายการ", desc2 = "Add/edit product counts This will be used to identify the units of each item.", module = "Database", menutype = "S", parrentmenu = "11-016", path = "Database/Um", icon = "fa fa-cube fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-021", name1 = "กลุ่มสินค้า", name2 = "Product group", desc1 = "เพิ่ม/แก้ไข กลุ่มสินค้าเพือประโยชน์ในการออกรายงานตามกลุ่มสินค้า", desc2 = "Add/edit product groups for the benefit of reporting by product group.", module = "Database", menutype = "S", parrentmenu = "11-016", path = "Database/ProdGrp", icon = "fa fa-layer-group fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-022", name1 = "สมาชิก", name2 = "Member", desc1 = "เพิ่ม/แก้ไข สมาชิกเพื่อนำไปใช้กำหนดราคาสินค้าแยกตามกลุ่มสมาชิก", desc2 = "Add/edit members to be used to set product prices by member group", module = "Database", menutype = "S", parrentmenu = "11-016", path = "Database/member", icon = "fa fa-address-card fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-023", name1 = "คลังสินค้า", name2 = "Whouse", desc1 = "เพิ่ม/แก้ไข คลังสินค้าเพื่อตรวจสอบสินค้าคงเหลือแยกตามคลัง", desc2 = "Add/edit warehouse to check inventory by warehouse", module = "Database", menutype = "S", parrentmenu = "11-016", path = "Database/Whouse", icon = "fa fa-warehouse fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-024", name1 = "ชั้นวาง", name2 = "Shelf", desc1 = "เพิ่ม/แก้ไข ชั้นวางสินค้าเพื่อระบุตำแหน่งที่เก็บของสินค้าภายในคลัง", desc2 = "Add/edit shelf to locate products in the warehouse", module = "Database", menutype = "S", parrentmenu = "11-016", path = "Database/Shelf", icon = "fa fa-pallet fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-025", name1 = "หมวด", name2 = "Category", desc1 = "เพิ่ม/แก้ไข หมวดสินค้าเพื่อประโยชน์ในการตรวจสอบสินค้าแยกตามหมวด", desc2 = "Add/edit product categories for the benefit of checking products classified by category", module = "Database", menutype = "S", parrentmenu = "11-016", path = "Database/Category", icon = "fa fa-pills fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-026", name1 = "ยี่ห้อ", name2 = "brand", desc1 = "เพิ่ม/แก้ไข ยี่ห้อสินค้าเพื่อประโยชน์ในการตรวจสอบสินค้าแยกตามยี่ห้อ", desc2 = "Add/edit product brands for the benefit of checking products classified by brands", module = "Database", menutype = "S", parrentmenu = "11-016", path = "Database/brand", icon = "fa fa-capsules fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-027", name1 = "รูปแบบ", name2 = "Format", desc1 = "เพิ่ม/แก้ไข รูปแบบสินค้าเพื่อประโยชน์ในการตรวจสอบสินค้าแยกตามรูปแบบ", desc2 = "Add/edit product types for the purpose of inspecting products by format", module = "Database", menutype = "S", parrentmenu = "11-016", path = "Database/Format", icon = "fa fa-tablets fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-028", name1 = "การออกแบบ", name2 = "Design", desc1 = "เพิ่ม/แก้ไข ออกแบบสินค้าเพื่อประโยชน์ในการตรวจสอบสินค้าแยกตามออกแบบ", desc2 = "Add/edit product designs for the benefit of product inspection by design", module = "Database", menutype = "S", parrentmenu = "11-016", path = "Database/Design", icon = "fa fa-boxes fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-029", name1 = "คุณภาพสินค้า", name2 = "Quality", desc1 = "เพิ่ม/แก้ไข คุณภาพสินค้า หรือ เกรดสินค้า เพื่อประโยชน์ในการตรวจสอบสินค้าแยกตามคุณภาพ ", desc2 = "Add/edit product grades for the benefit of checking products classified by grade", module = "Database", menutype = "S", parrentmenu = "11-016", path = "Database/Grade", icon = "fa fa-dolly fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-030", name1 = "รุ่น", name2 = "Model", desc1 = "เพิ่ม/แก้ไข รุ่นสินค้าเพื่อประโยชน์ในการตรวจสอบสินค้าแยกตามรุ่น", desc2 = "Add/edit product models for the benefit of checking products by model", module = "Database", menutype = "S", parrentmenu = "11-016", path = "Database/Model", icon = "fa fa-baseball-ball fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-031", name1 = "ขนาด", name2 = "Size", desc1 = "เพิ่ม/แก้ไข ขนาดสินค้าเพื่อประโยชน์ในการตรวจสอบสินค้าแยกตามขนาด", desc2 = "Add/edit product sizes for the benefit of checking products by size", module = "Database", menutype = "S", parrentmenu = "11-016", path = "Database/Size", icon = "fa fa-archive fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-032", name1 = "สี", name2 = "color", desc1 = "เพิ่ม/แก้ไข สีสินค้าเพื่อประโยชน์ในการตรวจสอบสินค้าแยกตามสี", desc2 = "Add/edit product colors for the benefit of checking products by color", module = "Database", menutype = "S", parrentmenu = "11-016", path = "Database/color", icon = "fa fa-palette fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-033", name1 = "น้ำหนัก", name2 = "Weight", desc1 = "เพิ่ม/แก้ไข น้ำหนักสินค้าเพื่อประโยชน์ในการตรวจสอบสินค้าแยกตามน้ำหนัก", desc2 = "Add/edit product weight for the purpose of inspecting products by weight", module = "Database", menutype = "S", parrentmenu = "11-016", path = "Database/Weight", icon = "fa fa-weight fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-034", name1 = "บัญชี", name2 = "Accounting Master", desc1 = "สร้างข้อมูลตั้งต้นของงานบัญชี เพื่อนำไปใช้ในระบบต่าง ๆ เช่น ผังบัญชี, อัตราภาษี เป็นต้น", desc2 = "Generate initial accounting information For use in various systems such as chart of accounts, tax rates, etc.", module = "Database", menutype = "H2", parrentmenu = "11-001", path = "Database/Account", icon = "", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-035", name1 = "ผังบัญชี", name2 = "Account code", desc1 = "เพิ่ม/แก้ไข รหัสบัญชีเพื่อนำไปใช้ในการบันทึกรายวัน ตรวจสอบรายงานแยกประเภท และงบการเงิน", desc2 = "Add/edit billing codes to be used for journaling.Examine the ledger and financial statements", module = "Database", menutype = "S", parrentmenu = "11-034", path = "Database/Acchart", icon = "fa fa-solar-panel fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-036", name1 = "สมุดรายวัน", name2 = "Journal book", desc1 = "เพิ่ม/แก้ไข สมุดรายวันแยกประเภท เพื่อแยกประเภทการบันทึกรายวันแยกประเภท", desc2 = "Add/edit classified journal To categorize journaling by category", module = "Database", menutype = "S", parrentmenu = "11-034", path = "Database/AccBook", icon = "fa fa-swatchbook fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-037", name1 = "บัญชีแยกประเภทที่ใช้บ่อย", name2 = "Dummy General Ledger ", desc1 = "เพิ่ม/แก้ไข บัญชีแยกประเภทที่ใช้ซ้ำ ๆ เช่น ลงรายวันประเภทเงินเดือน ฯลฯ", desc2 = "Add/edit  Dummy General Ledger ", module = "Database", menutype = "S", parrentmenu = "11-034", path = "Database", icon = "fa fa-book fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-038", name1 = "อัตราภาษี", name2 = "Tax rate", desc1 = "เพิ่ม/แก้ไข อัตราภาษีมูลค่าเพิ่ม เพิ่มนำไประบุในเอกสารต่าง ๆ และตรวจสอบรายงานภาษี", desc2 = "Add/edit VAT rates Add to be identified in various documents and check the tax report.", module = "Database", menutype = "S", parrentmenu = "11-034", path = "Database/vattype", icon = "fa fa-vote-yea fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-039", name1 = "ธนาคาร", name2 = "Accounting Master", desc1 = "สร้างข้อมูลตั้งต้นของงานบัญชี เพื่อนำไปใช้ในระบบต่าง ๆ เช่น ผังบัญชี, อัตราภาษี เป็นต้น", desc2 = "Generate initial accounting information For use in various systems such as chart of accounts, tax rates, etc.", module = "Database", menutype = "H2", parrentmenu = "11-001", path = "Database/Account", icon = "", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-040", name1 = "สมุดบัญชีเงินฝาก", name2 = "Book Bank", desc1 = "เพิ่ม/แก้ไข เล่มบัญชีธนาคาร", desc2 = "Add/edit the Book Bank", module = "Database", menutype = "S", parrentmenu = "11-039", path = "Database/BookBank", icon = "fa fa-money-check fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-041", name1 = "รายชื่อธนาคาร", name2 = "Bank", desc1 = "เพิ่ม/แก้ไข รายชื่อธนาคารเพื่อใช้ในการระบุ สมุดบัญชีเงินฝาก และระบุตอนรับ-จ่ายเงิน", desc2 = "Add/edit bank names for identification purposes. Passbook And specify when receiving-paying", module = "Database", menutype = "S", parrentmenu = "11-039", path = "Database/Bank", icon = "fa fa-university fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-042", name1 = "สาขาธนาคาร", name2 = "Bank Branch", desc1 = "เพิ่ม/แก้ไข รายชื่อสาขาธนาคารเพื่อใช้ในการระบุ สมุดบัญชีเงินฝาก และระบุตอนรับ-จ่ายเงิน", desc2 = "Add/edit the list of bank branches to identify Passbook And specify when receiving-paying", module = "Database", menutype = "S", parrentmenu = "11-039", path = "Database/bankbranch", icon = "fa fa-archway fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-043", name1 = "หน่วยเงินอัตราแลกเปลี่ยน", name2 = "Currency", desc1 = "เพิ่ม/แก้ไข หน่วยเงินตรา ที่จะนำไปใช้งานในการคำนวณอัตราแลกเปลี่ยน", desc2 = "Add/edit currency units to be used in currency exchange calculations.", module = "Database", menutype = "S", parrentmenu = "11-039", path = "Database/Currency", icon = "fa fa-file-invoice-dollar fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-044", name1 = "อัตราแลกเปลี่ยนประจำวัน", name2 = "Currency per Day", desc1 = "เพิ่ม/แก้ไข อัตราแลกเปลี่ยนเงินประจำวัน", desc2 = "Add/edit daily exchange rates", module = "Database", menutype = "S", parrentmenu = "11-039", path = "Database/CurrencyDay", icon = "fa fa-money-check-alt fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-044", name1 = "สินทรััพย์", name2 = "Asset", desc1 = "เพิ่ม/แก้ไข ฐานข้อมูลสินทรัพสำหรับคำนวนค่าเสื่อมราคา", desc2 = "Add/edit Asset", module = "Database", menutype = "H2", parrentmenu = "11-001", path = "Database/Asset", icon = "", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-045", name1 = "ฐานข้้อมูลสินทรัพย์", name2 = "Asset", desc1 = "เพิ่ม/แก้ไข ฐานข้้อมูลสินทรัพย์", desc2 = "Add/Edit Asset", module = "Database", menutype = "S", parrentmenu = "11-044", path = "Database/Asset", icon = "fa fa-money-check fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-046", name1 = "ฐานข้อมููลกลุ่มสินทรัพย์", name2 = "Asset group", desc1 = "เพิ่ม/แก้ไข ฐานข้้อมูลกลุ่มสินทรัพย์", desc2 = "Add/Edit Asset group", module = "Database", menutype = "S", parrentmenu = "11-044", path = "Database/AssetGroup", icon = "fa fa-money-check fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-049", name1 = "ข้อมูลองค์กร", name2 = "Organization", desc1 = "บันทึกรายละเอียดข้อมูลขององค์กร เช่น ชื่อบริษัท, สาขา, แผนก, โครงการ เป็นต้น", desc2 = "Save detailed information of the organization such as company name1, branch, department, project, etc.", module = "Database", menutype = "H2", parrentmenu = "11-001", path = "Database/Company", icon = "", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-050", name1 = "แผนก", name2 = "Department", desc1 = "เพิ่ม/แก้ไข รายชื่อแผนก เพื่อนำไปใช้ในการแยกบัญชีรายได้-ค่าใช้จ่าย และตรวจสอบงบการเงินแยกตามแผนก", desc2 = "Add/edit the list of departments to be used for income-expense separation.And issue financial statements separated by department", module = "Database", menutype = "S", parrentmenu = "11-049", path = "Database/Department", icon = "fa fa-sign fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-051", name1 = "ฝ่าย", name2 = "Section", desc1 = "เพิ่ม/แก้ไข รายชื่อฝ่าย เพื่อนำไปกำหนดหมวดของแผนก และแยกบัญชีรายได้-ค่าใช้จ่าย เพื่อตรวจสอบงบการเงินแยกตามฝ่าย", desc2 = "Add/edit the list of departments to define departments And separate income-expenses accounts To examine the financial statements by department", module = "Database", menutype = "S", parrentmenu = "11-049", path = "Database/Section", icon = "fa fa-th-large fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-052", name1 = "โครงการ", name2 = "Project", desc1 = "เพิ่ม/แก้ไข รายชื่อโครงการ เพื่อนำไปใช้ในจัดสรรค์งบประมาณของโครงการ ในการตรวจสอบ บัญชีรายได้-ค่าใช้จ่าย และตรวจสอบงบการเงินแยกตามโครงการ", desc2 = "Add/edit project list To be used in the budgeting of the project in the audit of income-expenses.And examining the financial statements separated by projects", module = "Database", menutype = "S", parrentmenu = "11-049", path = "Database/Project", icon = "fa fa-th fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-053", name1 = "แผนงาน", name2 = "Plan", desc1 = "เพิ่ม/แก้ไข รายชื่อแผนงาน เพื่อนำไปใช้จัดหมวดของโครงการ ในการตรวจสอบ บัญชีรายได้-ค่าใช้จ่าย และตรวจสอบงบการเงินแยกตามแผนงาน", desc2 = "Add/edit plan list To be used to categorize projects to verify income-expenses.And audited financial statements separated by plans", module = "Database", menutype = "S", parrentmenu = "11-049", path = "Database/Plan", icon = "fa fa-th-list fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-054", name1 = "แขวง/ตำบล", name2 = "District", desc1 = "เพิ่ม/แก้ไข รายชื่อแขวง/ตำบล เพื่อเป็นข้อมูลที่นำไปใช้ในการระบุที่อยู่ของระบบต่าง ๆ", desc2 = "Add/edit list of sub-district To be information that can be used to identify the address of various systems.", module = "Database", menutype = "S", parrentmenu = "11-049", path = "Database/PostalSubdisrict", icon = "fa fa-map-marked-alt fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-055", name1 = "เขต/อำเภอ", name2 = "Ampoe", desc1 = "เพิ่ม/แก้ไข รายชื่อเขต/อำเภอ เพื่อเป็นข้อมูลที่นำไปใช้ในการระบุที่อยู่ของระบบต่าง ๆ", desc2 = "Add/edit the list of districts to provide information that can be used for addressing various systems.", module = "Database", menutype = "S", parrentmenu = "11-049", path = "Database/PostalDisrict", icon = "fa fa-map-marked fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-056", name1 = "จังหวัด", name2 = "Province", desc1 = "เพิ่ม/แก้ไข รายชื่อจังหวัด เพื่อเป็นข้อมูลที่นำไปใช้ในการระบุที่อยู่ของระบบต่าง ๆ", desc2 = "Add/edit the list of provinces To be information that can be used to identify the address of various systems.", module = "Database", menutype = "S", parrentmenu = "11-049", path = "Database/PostalProvince", icon = "fa fa-map fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-057", name1 = "ประเทศ", name2 = "Country", desc1 = "เพิ่ม/แก้ไข รายชื่อประเทศ เพื่อเป็นข้อมูลที่นำไปใช้ในการระบุที่อยู่ของระบบต่าง ๆ", desc2 = "Add/edit country list To be information that can be used to identify the address of various systems.", module = "Database", menutype = "S", parrentmenu = "11-049", path = "Database/PostalCountry", icon = "fa fa-globe-asia fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-058", name1 = "สาขา", name2 = "Branch", desc1 = "เพิ่ม/แก้ไข รายชื่อสาขาของบริษัทที่ใช้งาน ", desc2 = "Add/edit the list of branches of the company used.", module = "Database", menutype = "S", parrentmenu = "11-049", path = "Database/Branch", icon = "fa fa-building fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "11-059", name1 = "บริษัท", name2 = "Company", desc1 = "เพิ่ม/แก้ไข รายละเอียดชื่อบริษัท ที่อยู่, เลขประจำตัวผู้เสียภาษี", desc2 = "Add/edit details, company name1, address, tax ID number", module = "Database", menutype = "S", parrentmenu = "11-049", path = "Database/Company", icon = "fa fa-city fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "12-001", name1 = "กำหนดค่าเริ่มต้น", name2 = "Configuration", desc1 = "", desc2 = "", module = "Config", menutype = "H1", parrentmenu = "12-001", path = "", icon = "fas fa-cog text-hover-primary fs-2x pr-3", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "12-002", name1 = "บันทึกข้อมูล", name2 = "Save Configuration", desc1 = "กำหนดค่าตั้งต้นในการใช้งาน ", desc2 = "Set the default usage", module = "Config", menutype = "H2", parrentmenu = "12-001", path = "Database/Config", icon = "", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "12-003", name1 = "Config", name2 = "Document Format", desc1 = "กำหนดรูปแบบรหัสเล่มเอกสาร, รูปแบบการ Running เลขที่ของเอกสาร รวมถึงรูปแบบการบันทึกรายวันที่ระบบบัญชี และการกำหนดแบบฟอร์มพิมพ์ต่าง ๆ", desc2 = "Set the format, code, document book, running format, document number Including the daily recording format at the accounting system And assigning various print forms", module = "Config", menutype = "S", parrentmenu = "12-002", path = "Config/ErpConfig", icon = "fa fa-book-open fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "12-004", name1 = "หน้าที่บัญชีหลัก", name2 = "Account Role Main", desc1 = "เพิ่ม/แก้ไข หน้าที่บัญขีหลักใช้งานกับทุกส่วนของระบบ", desc2 = "Add/edit the account Role main use all system", module = "Config", menutype = "S", parrentmenu = "12-002", path = "Database/AccRole", icon = "fa fa-book-open fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "12-005", name1 = "หน้าที่บัญชีเฉพาะ", name2 = "Account Role Specific", desc1 = "เพิ่ม/แก้ไข หน้าที่บัญขีเฉพาะ", desc2 = "Add/edit the account Role Specific", module = "Config", menutype = "S", parrentmenu = "12-002", path = "Database/AccRoleTemplate", icon = "fa fa-book-reader fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "12-006", name1 = "เล่มเอกสาร", name2 = "Book Document", desc1 = "เพิ่ม/แก้ไข เล่มเอกสาร", desc2 = "Add/edit the Book Document", module = "Config", menutype = "S", parrentmenu = "12-002", path = "Database/Book", icon = "fa fa-book fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "12-007", name1 = "บันทึกยอดยกมา", name2 = "Beginning balance", desc1 = "", desc2 = "", module = "Database", menutype = "H2", parrentmenu = "12-001", path = "Database", icon = "", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "12-008", name1 = "เจ้าหนี้ยกมา", name2 = "Accounts Payable balance", desc1 = "เพิ่ม/แก้ไข เอกสารเจ้าหนี้ยกมากตั้งต้น สามารถบันทึกแบบรวบเอกสารเป็นยอดเดียว หรือจะบันทึกแบบแยกเอกสารได้ทั้ง 2 แบบ", desc2 = "Add/edit documents Able to save the document as a single amount Or can save both types of documents separately", module = "Database", menutype = "S", parrentmenu = "12-007", path = "Database", icon = "fa fa-id-card fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "12-009", name1 = "ลูกหนี้ยกมา", name2 = "Accounts Receivable balance", desc1 = "เพิ่ม/แก้ไข เอกสารลูกหนี้ยกมากตั้งต้น สามารถบันทึกแบบรวบเอกสารเป็นยอดเดียว หรือจะบันทึกแบบแยกเอกสารได้ทั้ง 2 แบบ", desc2 = "Add/edit documents from the default receivables Able to save the document as a single amount Or can save both types of documents separately", module = "Database", menutype = "S", parrentmenu = "12-007", path = "Database", icon = "fa fa-id-card fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "12-010", name1 = "สินค้ายกมา", name2 = "Inventory balance", desc1 = "เพิ่ม/แก้ไข สินค้าคงเหลือยกมาตั้งต้น ณ วันที่เริ่มใช้ระบบ", desc2 = "Add/edit inventory from the beginning of the system use.", module = "Database", menutype = "S", parrentmenu = "12-007", path = "Database", icon = "fa fa-boxes fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "12-011", name1 = "บัญชียกมา(งบดุล)", name2 = "Balance sheet", desc1 = "เพิ่ม/แก้ไข ยอดยกมาทางบัญชี ณ วันที่เริ่มใช้ระบบ กรณีใช้เมนูนี้ให้บันทึกด้วยมูลค่าตามงบดุล", desc2 = "Add/edit the account balance as of the system start date.If using this menu, record the balance sheet value.", module = "Database", menutype = "S", parrentmenu = "12-007", path = "Database", icon = "fa fa-chart-bar fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "12-012", name1 = "เช็คยกมา", name2 = "Cheque Balance", desc1 = "เพิ่ม/แก้ไข ยอดยกเช็คค้างรับ และค้างจ่ายยกมา ณ วันที่เริ่มใช้งานระบบ", desc2 = "เพิ่ม/แก้ไข ยอดยกเช็คค้างรับ และค้างจ่ายยกมา ณ วันที่เริ่มใช้งานระบบ", module = "Database", menutype = "S", parrentmenu = "12-007", path = "Database", icon = "fa fa-money-check fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "13-001", name1 = "กำหนดสิทธิ์", name2 = "Permissions", desc1 = "", desc2 = "", module = "Permissions", menutype = "H1", parrentmenu = "13-001", path = "", icon = "fas fa-shield-alt text-hover-primary fs-2x pr-3", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "13-002", name1 = "บันทึกข้อมูล", name2 = "Add Data", desc1 = "", desc2 = "", module = "Permissions", menutype = "H2", parrentmenu = "13-001", path = "Database/User", icon = "", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "13-003", name1 = "ผู้ใช้งาน", name2 = "User", desc1 = "เพิ่ม/แก้ไข ผู้ใช้งานระบบ", desc2 = "Add/Edit username and password", module = "Permissions", menutype = "S", parrentmenu = "13-002", path = "Database/UserLogin", icon = "fas fa-user fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "13-004", name1 = "ตำแหน่ง", name2 = "position", desc1 = "เพิ่ม/แก้ไข ตำแหน่ง ผู้ใช้งาน", desc2 = "Add/Edit position", module = "Permissions", menutype = "S", parrentmenu = "13-002", path = "Database/position", icon = "fas fa-user-tie fa-3x", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            menus.Add(new Menu { code = "14-001", name1 = "ออกจากโปรแกรม", name2 = "Exit", desc1 = "", desc2 = "", module = "Exit", menutype = "H1", parrentmenu = "14-001", path = "", icon = "fas fa-shield-alt text-hover-primary fs-2x pr-3", command = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            int maxlenght = menus.Count;
            for (int i = 0; i < maxlenght; i += 400)
            {
                Menu[] liResult = menus.Skip(i).Take(400).ToArray();
                if (liResult is not null && liResult.Length > 0)
                {
                    context.AddRange(liResult);
                    context.SaveChanges(true);
                }
            }
        }
    }
}
