using RichnessSoft.Entity.Class;
using RichnessSoft.Entity.Context;
using RichnessSoft.Entity.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RichnessSoft.Entity.initData
{
    public static class initCountry
    {
        public static void InitializeAsync(RicnessDbContext context
            , RichnessLogDbContext contextlog
            , SuperAdminDefaultOptions superAdminDefaultOptions)
        {
            List<PostalCountry> ListPostalCountry = new List<PostalCountry>()
            {
                new PostalCountry { code = "00", code2 = "000", name1 = "<ไม่ระบุประเทศ>", name2 = "<ColorNot Define>", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "AA", code2 = "ABW", name1 = "อารูบา", name2 = "Aruba", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "AC", code2 = "ATG", name1 = "แอนติกาและบาร์บูดา", name2 = "Antigua and Barbuda", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "AF", code2 = "AFG", name1 = "อัฟกานิสถาน", name2 = "Afghanistan", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "AG", code2 = "DZA", name1 = "แอลจีเรีย", name2 = "Algeria", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "AJ", code2 = "AZE", name1 = "อาเซอร์ไบจาน", name2 = "Azerbaijan", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "AL", code2 = "ALB", name1 = "แอลเบเนีย", name2 = "Albania", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "AM", code2 = "ARM", name1 = "อาร์เมเนีย", name2 = "Armenia", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "AN", code2 = "AND", name1 = "อันดอร์รา", name2 = "Andorra", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "AO", code2 = "AGO", name1 = "แองโกลา", name2 = "Angola", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "AQ", code2 = "ASM", name1 = "อเมริกันซามัว", name2 = "American Samoa", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "AR", code2 = "ARG", name1 = "อาร์เจนตินา", name2 = "Argentina", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "AS", code2 = "AUS", name1 = "ออสเตรเลีย", name2 = "Australia", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "AU", code2 = "AUT", name1 = "ออสเตรีย", name2 = "Austria", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "AV", code2 = "AIA", name1 = "แองกวิลลา", name2 = "Anguilla", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "AY", code2 = "ATA", name1 = "แอนตาร์กติกา", name2 = "Antarctica", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "BA", code2 = "BHR", name1 = "บาห์เรน", name2 = "Bahrain", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "BB", code2 = "BRB", name1 = "บาร์เบโดส", name2 = "Barbados", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "BC", code2 = "BWA", name1 = "บอตสวานา", name2 = "Botswana", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "BD", code2 = "BMU", name1 = "เบอร์มิวดา", name2 = "Bermuda", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "BE", code2 = "BEL", name1 = "เบลเยี่ยม", name2 = "Belgium", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "BF", code2 = "BHS", name1 = "บาฮามาส", name2 = "Bahamas, The", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "BG", code2 = "BGD", name1 = "บังกลาเทศ", name2 = "Bangladesh", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "BH", code2 = "BLZ", name1 = "เบลีซ", name2 = "Belize", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "BK", code2 = "BIH", name1 = "บอสเนียและเฮอร์เซโก", name2 = "Bosnia and Herzegovina", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "BL", code2 = "BOL", name1 = "โบลิเวีย", name2 = "Bolivia", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "BM", code2 = "MMR", name1 = "เมียนมาร์ (พม่า)", name2 = "Myanmar (Burma)", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "BN", code2 = "BEN", name1 = "เบนิน", name2 = "Benin", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "BO", code2 = "BLR", name1 = "เบลารุส", name2 = "Belarus", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "BP", code2 = "SLB", name1 = "หมู่เกาะโซโลมอน", name2 = "Solomon Islands", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "BR", code2 = "BRA", name1 = "บราซิล", name2 = "Brazil", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "BT", code2 = "BTN", name1 = "ภูฏาน", name2 = "Bhutan", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "BU", code2 = "BGR", name1 = "บัลแกเรีย", name2 = "Bulgaria", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "BV", code2 = "NOR", name1 = "เกาะบูเวต", name2 = "Bouvet Island", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "BX", code2 = "BRN", name1 = "บรูไน", name2 = "Brunei", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "BY", code2 = "BDI", name1 = "บุรุนดี", name2 = "Burundi", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "CA", code2 = "CAN", name1 = "แคนาดา", name2 = "Canada", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "CB", code2 = "KHM", name1 = "กัมพูชา", name2 = "Cambodia", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "CD", code2 = "TCD", name1 = "ชาด", name2 = "Chad", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "CE", code2 = "LKA", name1 = "ศรีลังกา", name2 = "Sri Lanka", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "CF", code2 = "COG", name1 = "คองโก", name2 = "Congo", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "CG", code2 = "ZAR", name1 = "ซาอีร์", name2 = "Zaire", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "CH", code2 = "CHN", name1 = "ประเทศจีน", name2 = "China", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "CI", code2 = "CHL", name1 = "ชิลี", name2 = "Chile", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "CJ", code2 = "CYM", name1 = "หมู่เกาะเคย์แมน", name2 = "Cayman Islands", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "CK", code2 = "CCK", name1 = "หมู่เกาะโคโคส (คีลิง)", name2 = "Cocos (Keeling) Islands", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "CM", code2 = "CMR", name1 = "แคเมอรูน", name2 = "Cameroon", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "CN", code2 = "COM", name1 = "คอโมโรส", name2 = "Comoros", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "CO", code2 = "COL", name1 = "โคลอมเบีย", name2 = "Colombia", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "CQ", code2 = "MNP", name1 = "หมู่เกาะนอร์เทิร์นมาเรียนา", name2 = "Northern Mariana Islands", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "CS", code2 = "CRI", name1 = "คอสตาริกา", name2 = "Costa Rica", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "CT", code2 = "CAF", name1 = "สาธารณรัฐแอฟริกากลาง", name2 = "Central African Republic", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "CU", code2 = "CUB", name1 = "คิวบา", name2 = "Cuba", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "CV", code2 = "CPV", name1 = "เคปเวิร์ด", name2 = "Cape Verde", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "CW", code2 = "COK", name1 = "หมู่เกาะคุก", name2 = "Cook Islands", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "CY", code2 = "CYP", name1 = "ไซปรัส", name2 = "Cyprus", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "DA", code2 = "DNK", name1 = "เดนมาร์ก", name2 = "Denmark", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "DJ", code2 = "DJI", name1 = "จิบูตี", name2 = "Djibouti", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "DO", code2 = "DMA", name1 = "โดมินิกา", name2 = "Dominica", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "DQ", code2 = "UMI", name1 = "เกาะจาร์วิส", name2 = "Jarvis Island", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "DR", code2 = "DOM", name1 = "สาธารณรัฐโดมินิกัน", name2 = "Dominican Republic", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "EC", code2 = "ECU", name1 = "เอกวาดอร์", name2 = "Ecuador", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "EG", code2 = "EGY", name1 = "อียิปต์", name2 = "Egypt", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "EI", code2 = "IRL", name1 = "ไอร์แลนด์", name2 = "Ireland", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "EK", code2 = "GNQ", name1 = "อิเควทอเรียลกินี", name2 = "Equatorial Guinea", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "EN", code2 = "EST", name1 = "เอสโตเนีย", name2 = "Estonia", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "ER", code2 = "ERI", name1 = "เอริเทรีย", name2 = "Eritrea", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "ES", code2 = "SLV", name1 = "เอลซัลวาดอร์", name2 = "El Salvador", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "ET", code2 = "ETH", name1 = "เอธิโอเปีย", name2 = "Ethiopia", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "EZ", code2 = "CZE", name1 = "สาธารณรัฐเช็ก", name2 = "Czech Republic", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "FG", code2 = "GUF", name1 = "เฟรนช์เกีย", name2 = "French Guiana", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "FI", code2 = "FIN", name1 = "ฟินแลนด์", name2 = "Finland", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "FJ", code2 = "FJI", name1 = "ฟิจิ", name2 = "Fiji", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "FK", code2 = "FLK", name1 = "หมู่เกาะฟอล์กแลนด์ (Islas Malvinas)", name2 = "Falkland Islands (Islas Malvinas)", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "FM", code2 = "FSM", name1 = "สหพันธรัฐไมโครนีเซีย", name2 = "Federated States of Micronesia", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "FO", code2 = "FRO", name1 = "หมู่เกาะแฟโร", name2 = "Faroe Islands", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "FP", code2 = "PYF", name1 = "เฟรนช์โปลินีเซีย", name2 = "French Polynesia", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "FQ", code2 = "UMI", name1 = "เกาะเบเกอร์", name2 = "Baker Island", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "FR", code2 = "FRA", name1 = "ฝรั่งเศส", name2 = "France", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "FS", code2 = "ATF", name1 = "ดินแดนทางตอนใต้และแอนตาร์กติกของฝรั่งเศส", name2 = "French Southern & Antarctic Lands", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "GA", code2 = "GMB", name1 = "แกมเบีย, The", name2 = "Gambia, The", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "GB", code2 = "GAB", name1 = "กาบอง", name2 = "Gabon", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "GG", code2 = "GEO", name1 = "จอร์เจีย", name2 = "Georgia", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "GH", code2 = "GHA", name1 = "กานา", name2 = "Ghana", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "GI", code2 = "GIB", name1 = "ยิบรอลตาร์", name2 = "Gibraltar", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "GJ", code2 = "GRD", name1 = "เกรนาดา", name2 = "Grenada", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "GK", code2 = "XGK", name1 = "เกิร์นซีย์", name2 = "Guernsey", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "GL", code2 = "GRL", name1 = "กรีนแลนด์", name2 = "Greenland", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "GM", code2 = "DEU", name1 = "เยอรมนี", name2 = "Germany", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "GO", code2 = "REU", name1 = "หมู่เกาะกลอริโอโซ", name2 = "Glorioso Islands", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "GP", code2 = "GLP", name1 = "กวาเดอลูป", name2 = "Guadeloupe", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "GQ", code2 = "GUM", name1 = "กวม", name2 = "Guam", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "GR", code2 = "GRC", name1 = "กรีซ", name2 = "Greece", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "GT", code2 = "GTM", name1 = "กัวเตมาลา", name2 = "Guatemala", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "GV", code2 = "GIN", name1 = "กินี", name2 = "Guinea", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "GY", code2 = "GUY", name1 = "กายอานา", name2 = "Guyana", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "GZ", code2 = "ISR", name1 = "ฉนวนกาซา", name2 = "Gaza Strip", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "HA", code2 = "HTI", name1 = "เฮติ", name2 = "Haiti", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "HM", code2 = "HMD", name1 = "เกาะเฮิร์ดและหมู่เกาะแมคโดนัลด์", name2 = "Heard Island & McDonald Islands", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "HO", code2 = "HND", name1 = "ฮอนดูรัส", name2 = "Honduras", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "HQ", code2 = "UMI", name1 = "เกาะฮาวแลนด์", name2 = "Howland Island", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "HR", code2 = "HRV", name1 = "โครเอเชีย", name2 = "Croatia", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "HU", code2 = "HUN", name1 = "ฮังการี", name2 = "Hungary", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "IC", code2 = "ISL", name1 = "ไอซ์แลนด์", name2 = "Iceland", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "ID", code2 = "IDN", name1 = "อินโดนีเซีย", name2 = "Indonesia", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "IM", code2 = "XIM", name1 = "ไอล์ออฟแมน", name2 = "Isle of Man", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "IN", code2 = "IND", name1 = "อินเดีย", name2 = "India", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "IO", code2 = "IOT", name1 = "บริติชอินเดียนโอเชียนเทร์ริทอรี", name2 = "British Indian Ocean Territory", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "IR", code2 = "IRN", name1 = "อิหร่าน", name2 = "Iran", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "IS", code2 = "ISR", name1 = "อิสราเอล", name2 = "Israel", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "IT", code2 = "ITA", name1 = "อิตาลี", name2 = "Italy", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "IV", code2 = "CIV", name1 = "ไอวอรีโคสต์", name2 = "Ivory Coast", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "IZ", code2 = "IRQ", name1 = "อิรัก", name2 = "Iraq", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "JA", code2 = "JPN", name1 = "ญี่ปุ่น", name2 = "Japan", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "JE", code2 = "XJE", name1 = "เจอร์ซี", name2 = "Jersey", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "JM", code2 = "JAM", name1 = "จาเมกา", name2 = "Jamaica", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "JN", code2 = "SJM", name1 = "สฟาลบาร์และยานไมเอน", name2 = "Svalbard and Jan Mayen", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "JO", code2 = "JOR", name1 = "จอร์แดน", name2 = "Jordan", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "JQ", code2 = "UMI", name1 = "จอห์นสตันอะทอลล์", name2 = "Johnston Atoll", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "JU", code2 = "REU", name1 = "เกาะฮวนเดอโนวา", name2 = "Juan De Nova Island", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "KE", code2 = "KEN", name1 = "เคนยา", name2 = "Kenya", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "KG", code2 = "KGZ", name1 = "คีร์กีซสถาน", name2 = "Kyrgyzstan", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "KN", code2 = "PRK", name1 = "เกาหลีเหนือ", name2 = "North Korea", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "KR", code2 = "KIR", name1 = "คิริบาส", name2 = "Kiribati", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "KS", code2 = "KOR", name1 = "เกาหลีใต้", name2 = "South Korea", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "KT", code2 = "CXR", name1 = "เกาะคริสต์มาส", name2 = "Christmas Island", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "KU", code2 = "KWT", name1 = "คูเวต", name2 = "Kuwait", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "KZ", code2 = "KAZ", name1 = "คาซัคสถาน", name2 = "Kazakhstan", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "LA", code2 = "LAO", name1 = "ลาว", name2 = "Laos", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "LE", code2 = "LBN", name1 = "เลบานอน", name2 = "Lebanon", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "LG", code2 = "LVA", name1 = "ลัตเวีย", name2 = "Latvia", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "LH", code2 = "LTU", name1 = "ลิทัวเนีย", name2 = "Lithuania", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "LI", code2 = "LBR", name1 = "ไลบีเรีย", name2 = "Liberia", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "LO", code2 = "SVK", name1 = "สโลวาเกีย", name2 = "Slovakia", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "LS", code2 = "LIE", name1 = "ลิกเตนสไตน์", name2 = "Liechtenstein", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "LT", code2 = "LSO", name1 = "เลโซโท", name2 = "Lesotho", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "LU", code2 = "LUX", name1 = "ลักเซมเบิร์ก", name2 = "Luxembourg", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "LY", code2 = "LBY", name1 = "ลิเบีย", name2 = "Libya", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "MA", code2 = "MDG", name1 = "มาดากัสการ์", name2 = "Madagascar", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "MB", code2 = "MTQ", name1 = "มาร์ตินีก", name2 = "Martinique", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "MC", code2 = "MAC", name1 = "มาเก๊า", name2 = "Macau", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "MD", code2 = "MDA", name1 = "มอลโดวา", name2 = "Moldova", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "MF", code2 = "MYT", name1 = "มายอต", name2 = "Mayotte", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "MG", code2 = "MNG", name1 = "มองโกเลีย", name2 = "Mongolia", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "MH", code2 = "MSR", name1 = "มอนต์เซอร์รัต", name2 = "Montserrat", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "MI", code2 = "MWI", name1 = "มาลาวี", name2 = "Malawi", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "MK", code2 = "MKD", name1 = "มาซิโดเนีย", name2 = "Macedonia", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "ML", code2 = "MLI", name1 = "มาลี", name2 = "Mali", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "MN", code2 = "MCO", name1 = "โมนาโก", name2 = "Monaco", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "MO", code2 = "MAR", name1 = "โมร็อกโก", name2 = "Morocco", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "MP", code2 = "MUS", name1 = "มอริเชียส", name2 = "Mauritius", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "MQ", code2 = "UMI", name1 = "หมู่เกาะมิดเวย์", name2 = "Midway Islands", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "MR", code2 = "MRT", name1 = "มอริเตเนีย", name2 = "Mauritania", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "MT", code2 = "MLT", name1 = "มอลตา", name2 = "Malta", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "MU", code2 = "OMN", name1 = "โอมาน", name2 = "Oman", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "MV", code2 = "MDV", name1 = "มัลดีฟส์", name2 = "Maldives", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "MW", code2 = "MON", name1 = "มอนเตเนโกร", name2 = "Montenegro", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "MX", code2 = "MEX", name1 = "เม็กซิโก", name2 = "Mexico", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "MY", code2 = "MYS", name1 = "มาเลเซีย", name2 = "Malaysia", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "MZ", code2 = "MOZ", name1 = "โมซัมบิก", name2 = "Mozambique", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "NC", code2 = "NCL", name1 = "นิวแคลิโดเนีย", name2 = "New Caledonia", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "NE", code2 = "NIU", name1 = "นีอูเอ", name2 = "Niue", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "NF", code2 = "NFK", name1 = "เกาะนอร์ฟอล์ก", name2 = "Norfolk Island", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "NG", code2 = "NER", name1 = "ไนเจอร์", name2 = "Niger", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "NH", code2 = "VUT", name1 = "วานูอาตู", name2 = "Vanuatu", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "NI", code2 = "NGA", name1 = "ไนจีเรีย", name2 = "Nigeria", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "NL", code2 = "NLD", name1 = "เนเธอร์แลนด์", name2 = "Netherlands", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "NO", code2 = "NOR", name1 = "นอร์เวย์", name2 = "Norway", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "NP", code2 = "NPL", name1 = "เนปาล", name2 = "Nepal", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "NR", code2 = "NRU", name1 = "นาอูรู", name2 = "Nauru", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "NS", code2 = "SUR", name1 = "ซูรินาเม", name2 = "Suriname", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "NT", code2 = "ANT", name1 = "เนเธอร์แลนด์", name2 = "Netherlands Antilles", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "NU", code2 = "NIC", name1 = "นิการากัว", name2 = "Nicaragua", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "NZ", code2 = "NZL", name1 = "นิวซีแลนด์", name2 = "New Zealand", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "PA", code2 = "PRY", name1 = "ประเทศปารากวัย", name2 = "Paraguay", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "PC", code2 = "PCN", name1 = "หมู่เกาะพิตแคร์น", name2 = "Pitcairn Islands", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "PE", code2 = "PER", name1 = "เปรู", name2 = "Peru", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "PF", code2 = "XPF", name1 = "หมู่เกาะพาราเซล", name2 = "Paracel Islands", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "PG", code2 = "XPG", name1 = "หมู่เกาะสแปรตลี", name2 = "Spratly Islands", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "PK", code2 = "PAK", name1 = "ปากีสถาน", name2 = "Pakistan", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "PL", code2 = "POL", name1 = "โปแลนด์", name2 = "Poland", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "PM", code2 = "PAN", name1 = "ปานามา", name2 = "Panama", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "PO", code2 = "PRT", name1 = "โปรตุเกส", name2 = "Portugal", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "PP", code2 = "PNG", name1 = "ปาปัวนิวกินี", name2 = "Papua New Guinea", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "PS", code2 = "PLW", name1 = "หมู่เกาะแปซิฟิก (ปาเลา)", name2 = "Pacific Islands (Palau)", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "PU", code2 = "GNB", name1 = "กินี-บิสเซา", name2 = "Guinea-Bissau", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "QA", code2 = "QAT", name1 = "กาตาร์", name2 = "Qatar", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "RE", code2 = "REU", name1 = "เรอูนียง", name2 = "Reunion", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "RM", code2 = "MHL", name1 = "หมู่เกาะมาร์แชลล์", name2 = "Marshall Islands", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "RO", code2 = "ROM", name1 = "โรมาเนีย", name2 = "Romania", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "RP", code2 = "PHL", name1 = "ฟิลิปปินส์", name2 = "Philippines", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "RQ", code2 = "PRI", name1 = "เปอร์โตริโก้", name2 = "Puerto Rico", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "RS", code2 = "RUS", name1 = "รัสเซีย", name2 = "Russia", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "RW", code2 = "RWA", name1 = "รวันดา", name2 = "Rwanda", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "SA", code2 = "SAU", name1 = "ซาอุดิอาราเบีย", name2 = "Saudi Arabia", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "SB", code2 = "SPM", name1 = "เซนต์ปิแอร์และมีเกอลง", name2 = "St. Pierre and Miquelon", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "SC", code2 = "KNA", name1 = "เซนต์คิตส์และเนวิส", name2 = "St. Kitts and Nevis", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "SE", code2 = "SYC", name1 = "เซเชลส์", name2 = "Seychelles", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "SF", code2 = "ZAF", name1 = "แอฟริกาใต้", name2 = "South Africa", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "SG", code2 = "SEN", name1 = "เซเนกัล", name2 = "Senegal", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "SH", code2 = "SHN", name1 = "เซนต์เฮเลนา", name2 = "St. Helena", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "SI", code2 = "SVN", name1 = "สโลวีเนีย", name2 = "Slovenia", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "SL", code2 = "SLE", name1 = "เซียร์ราลีโอน", name2 = "Sierra Leone", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "SM", code2 = "SMR", name1 = "ซานมาริโน", name2 = "San Marino", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "SN", code2 = "SGP", name1 = "สิงคโปร์", name2 = "Singapore", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "SO", code2 = "SOM", name1 = "โซมาเลีย", name2 = "Somalia", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "SP", code2 = "ESP", name1 = "สเปน", name2 = "Spain", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "SR", code2 = "SRB", name1 = "เซอร์เบีย", name2 = "Serbia", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "ST", code2 = "LCA", name1 = "เซนต์ลูเซีย", name2 = "St. Lucia", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "SU", code2 = "SDN", name1 = "ซูดาน", name2 = "Sudan", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "SV", code2 = "SJM", name1 = "สฟาลบาร์", name2 = "Svalbard", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "SW", code2 = "SWE", name1 = "สวีเดน", name2 = "Sweden", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "SX", code2 = "SGS", name1 = "เซาท์จอร์เจียและเซาท์แซนด์วิชคือ", name2 = "South Georgia and the South Sandwich Is", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "SY", code2 = "SYR", name1 = "ซีเรีย", name2 = "Syria", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "SZ", code2 = "CHE", name1 = "สวิตเซอร์แลนด์", name2 = "Switzerland", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "TC", code2 = "ARE", name1 = "สหรัฐอาหรับเอมิเรตส์", name2 = "United Arab Emirates", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "TD", code2 = "TTO", name1 = "ตรินิแดดและโตเบโก", name2 = "Trinidad and Tobago", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "TH", code2 = "THA", name1 = "ประเทศไทย", name2 = "Thailand", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "TI", code2 = "TJK", name1 = "ทาจิกิสถาน", name2 = "Tajikistan", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "TK", code2 = "TCA", name1 = "หมู่เกาะเติกส์และหมู่เกาะเคคอส", name2 = "Turks and Caicos Islands", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "TL", code2 = "TKL", name1 = "โทเคอเลา", name2 = "Tokelau", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "TN", code2 = "TON", name1 = "ตองกา", name2 = "Tonga", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "TO", code2 = "TGO", name1 = "โตโก", name2 = "Togo", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "TP", code2 = "STP", name1 = "เซาตูเมและปรินซิปี", name2 = "Sao Tome and Principe", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "TS", code2 = "TUN", name1 = "ตูนิเซีย", name2 = "Tunisia", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "TU", code2 = "TUR", name1 = "ไก่งวง", name2 = "Turkey", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "TV", code2 = "TUV", name1 = "ตูวาลู", name2 = "Tuvalu", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "TW", code2 = "TWN", name1 = "ไต้หวัน", name2 = "Taiwan", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "TX", code2 = "TKM", name1 = "เติร์กเมนิสถาน", name2 = "Turkmenistan", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "TZ", code2 = "TZA", name1 = "แทนซาเนียสหสาธารณรัฐ", name2 = "Tanzania, United Republic of", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "UG", code2 = "UGA", name1 = "ยูกันดา", name2 = "Uganda", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "UK", code2 = "GBR", name1 = "ประเทศอังกฤษ", name2 = "United Kingdom", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "UP", code2 = "UKR", name1 = "ยูเครน", name2 = "Ukraine", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "US", code2 = "USA", name1 = "สหรัฐ", name2 = "United States", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "UV", code2 = "BFA", name1 = "บูร์กินาฟาโซ", name2 = "Burkina Faso", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "UY", code2 = "URY", name1 = "อุรุกวัย", name2 = "Uruguay", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "UZ", code2 = "UZB", name1 = "อุซเบกิสถาน", name2 = "Uzbekistan", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "VC", code2 = "VCT", name1 = "เซนต์วินเซนต์และเกรนาดีนส์", name2 = "St. Vincent and the Grenadines", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "VE", code2 = "VEN", name1 = "เวเนซุเอลา", name2 = "Venezuela", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "VI", code2 = "VGB", name1 = "หมู่เกาะบริติชเวอร์จิน", name2 = "British Virgin Islands", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "VM", code2 = "VNM", name1 = "เวียดนาม", name2= "Vietnam", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "VQ", code2 = "VIR", name1 = "หมู่เกาะเวอร์จิน", name2 = "Virgin Islands", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "WE", code2 = "ISR", name1 = "เวสต์แบงก์", name2 = "West Bank", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "WF", code2 = "WLF", name1 = "วาลลิสและฟุตูนา", name2 = "Wallis and Futuna", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "WI", code2 = "ESH", name1 = "ซาฮาร่าตะวันตก", name2 = "Western Sahara", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "WQ", code2 = "UMI", name1 = "เกาะเวก", name2 = "Wake Island", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "WS", code2 = "WSM", name1 = "ซามัวตะวันตก", name2 = "Western Samoa", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "WZ", code2 = "SWZ", name1 = "สวาซิแลนด์", name2 = "Swaziland", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "YM", code2 = "YEM", name1 = "เยเมน", name2 = "Yemen", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "ZA", code2 = "ZMB", name1 = "แซมเบีย", name2 = "Zambia", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "ZI", code2 = "ZWE", name1 = "ซิมบับเว", name2 = "Zimbabwe", createatutc = DateTime.Now, updateatutc = DateTime.Now },
                new PostalCountry { code = "WA", code2 = "NAM", name1 = "นามิเบีย", name2 = "Namibia", createatutc = DateTime.Now, updateatutc = DateTime.Now }

            };
            context.AddRange(ListPostalCountry.ToArray());
            context.SaveChanges();
        }
    }
}
