using RichnessSoft.Entity.Class;
using RichnessSoft.Entity.Context;
using RichnessSoft.Entity.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RichnessSoft.Entity.initData
{
    public static class initDocType
    {
        public static void InitializeAsync(RicnessDbContext context
            , RichnessLogDbContext contextlog
            , SuperAdminDefaultOptions superAdminDefaultOptions)
        {
            List<DocType> doctypes = new List<DocType>();

            doctypes.Add(new DocType() { system = "SALE", menu = "GL", type = "Withholding Tax", doc_group = "WH", code = "WHN", name1 = "ใบภาษีหัก ณ ที่จ่าย(กรณีเราเป็นผู้รับ/ถูกหักภาษี)", name2 = "Withholding Tax Note(NOT-SUBMIT)", vat = "", cash = "", service = "", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "SALE", menu = "SALE", type = "Sale service", doc_group = "ST", code = "DPR", name1 = "ใบกำกับภาษี เงินมัดจำรับล่วงหน้า", name2 = "Deposit Received", vat = "Y", cash = "", service = "", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "SALE", menu = "SALE ORDER", type = "Reserve", doc_group = "SO", code = "SO", name1 = "ใบรับคำสั่งซื้อ สินค้า/บริการ", name2 = "Sale Order", vat = "", cash = "", service = "", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "SALE", menu = "SALE ORDER", type = "Reserve", doc_group = "SO", code = "QT", name1 = "ใบเสนอราคา สินค้า/บริการ", name2 = "Quotation", vat = "", cash = "", service = "", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "INVENTORY", menu = "INVENTORY", type = "Adjust", doc_group = "AJ", code = "CK", name1 = "ใบตรวจนับสต๊อก", name2 = "Check inventory", vat = "", cash = "", service = "", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "INVENTORY", menu = "INVENTORY", type = "Adjust", doc_group = "AJ", code = "AJ", name1 = "ใบปรับยอด", name2 = "Adjust inventory", vat = "", cash = "", service = "", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "INVENTORY", menu = "INVENTORY", type = "Stock Transfer", doc_group = "TF", code = "BTF", name1 = "ใบโอนระหว่างสาขา", name2 = "Branch Transfer", vat = "", cash = "", service = "", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "INVENTORY", menu = "INVENTORY", type = "Stock Requset", doc_group = "RQ", code = "BTR", name1 = "ใบขอโอนสินค้าระหว่างสาขา", name2 = "Branch Transfer Request", vat = "", cash = "", service = "", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "INVENTORY", menu = "INVENTORY", type = "Stock Transfer", doc_group = "TF", code = "WTF", name1 = "ใบโอนระหว่างคลัง", name2 = "Warehouse Transfer", vat = "", cash = "", service = "", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "INVENTORY", menu = "INVENTORY", type = "Stock Requset", doc_group = "RQ", code = "WTR", name1 = "ใบขอโอนสินค้าระหว่างคลัง", name2 = "Warehouse Transfer Requset", vat = "", cash = "", service = "", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "INVENTORY", menu = "INVENTORY", type = "Stock In", doc_group = "LO", code = "LR", name1 = "ใบคืนสินค้าจากการยืม", name2 = "Return Note to loan", vat = "", cash = "", service = "", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "INVENTORY", menu = "INVENTORY", type = "Stock Out", doc_group = "LO", code = "LB", name1 = "ใบยืมสินค้า", name2 = "Borrowing Note from loan", vat = "", cash = "", service = "", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "INVENTORY", menu = "INVENTORY", type = "Stock Requset", doc_group = "RQ", code = "RL", name1 = "ใบขอยืมสินค้า", name2 = "Borrowing form", vat = "", cash = "", service = "", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "INVENTORY", menu = "INVENTORY", type = "Delivery", doc_group = "DO", code = "DO", name1 = "ใบส่งสินค้าชั่วคราว", name2 = "Delivery Order", vat = "", cash = "", service = "", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "INVENTORY", menu = "INVENTORY", type = "Delivery", doc_group = "DO", code = "GR", name1 = "ใบรับสินค้าชั่วคราว", name2 = "Goods received", vat = "", cash = "", service = "", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "SALE", menu = "SALE", type = "Sale trading", doc_group = "ST", code = "IVS", name1 = "ใบกำกับภาษี/ใบแจ้งหนี้ ขายเชื่อ", name2 = "Tax invoice Sales", vat = "Y", cash = "", service = "", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "PURCHASE", menu = "PAYMENT", type = "Pay Trading", doc_group = "PM", code = "PDP", name1 = "ใบเสร็จ/ใบกำกับภาษี จ่ายเงินมัดจำล่วงหน้า", name2 = "cash Buy Deposit", vat = "Y", cash = "", service = "", tax_refund = "Y", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "PURCHASE", menu = "PAYMENT", type = "Pay Before", doc_group = "PP", code = "PPI", name1 = "ใบเตรียมจ่ายชำระ(ก่อนรับใบเสร็จ/ใบกำกับภาษี)", name2 = "Perpare Payment Invoice", vat = "", cash = "", service = "", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "PURCHASE", menu = "PAYMENT", type = "Pay Trading", doc_group = "PM", code = "PRE", name1 = "ใบเสร็จรับเงิน", name2 = "Payment Receipt", vat = "", cash = "", service = "", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "PURCHASE", menu = "PAYMENT", type = "Pay Before", doc_group = "PP", code = "PPR", name1 = "ใบเตรียมจ่ายชำระ(ก่อนรับใบเสร็จ)", name2 = "Prepare Payment", vat = "", cash = "", service = "", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "PURCHASE", menu = "PAYMENT", type = "Pay Billing", doc_group = "PL", code = "PBL", name1 = "ใบวางบิล", name2 = "Billing", vat = "", cash = "", service = "", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "PURCHASE", menu = "PAYMENT", type = "Buy Trading", doc_group = "BC", code = "PDN", name1 = "ใบกำกับภาษี/เพิ่มหนี้(ซื้อสอ)", name2 = "cash Buy Debit Note", vat = "Y", cash = "", service = "", tax_refund = "Y", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "PURCHASE", menu = "PAYMENT", type = "Buy Trading", doc_group = "BC", code = "PCN", name1 = "ใบกำกับภาษี/ลดหนี้(ซื้อสด)", name2 = "cash Buy Credit Note", vat = "Y", cash = "", service = "", tax_refund = "Y", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "PURCHASE", menu = "PAYMENT", type = "Buy Trading", doc_group = "BC", code = "PCI", name1 = "ใบกำกับภาษี/ใบเสร็จรับเงิน(ซื้อสด)", name2 = "cash Buy", vat = "Y", cash = "", service = "", tax_refund = "Y", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "PURCHASE", menu = "PURCHASE", type = "Buy Trading", doc_group = "BT", code = "ADP", name1 = "ใบแจ้งหนี้ เงินมัดจำจ่ายล่วงหน้า", name2 = "Advance Dposit Paid", vat = "Y", cash = "", service = "", tax_refund = "Y", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "PURCHASE", menu = "PURCHASE", type = "Buy service", doc_group = "BS", code = "BDN", name1 = "ใบแจ้งหนี้/เพิ่มหนี้ ซื้อเชื่อ(ภาษียังไม่ถึงกำหนด)", name2 = "Debit Note(Undue Input vat)", vat = "", cash = "", service = "", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "PURCHASE", menu = "PURCHASE", type = "Buy service", doc_group = "BS", code = "BCN", name1 = "ใบแจ้งหนี้/ลดหนี้ ซื้อเชื่อ(ภาษียังไม่ถึงกำหนด)", name2 = "Credit Note(Undue Input vat)", vat = "N", cash = "", service = "", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "PURCHASE", menu = "PURCHASE", type = "Buy service", doc_group = "BS", code = "BIV", name1 = "ใบแจ้งหนี้ ซื้อเชื่อ(ภาษียังไม่ถึงกำหนด)", name2 = "Invoice(Undue Input vat)", vat = "N", cash = "", service = "", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "PURCHASE", menu = "PURCHASE", type = "Buy Trading", doc_group = "BT", code = "DNB", name1 = "ใบกำกับภาษี/เพิ่มหนี้ ซื้อเชื่อ", name2 = "Purchase Debit note", vat = "Y", cash = "", service = "", tax_refund = "Y", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "PURCHASE", menu = "PURCHASE", type = "Buy Trading", doc_group = "BT", code = "CNB", name1 = "ใบกำกับภาษี/ลดหนี้ ซื้อเชื่อ", name2 = "Purchase Credit note", vat = "Y", cash = "", service = "", tax_refund = "Y", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "PURCHASE", menu = "PURCHASE", type = "Buy Trading", doc_group = "BT", code = "IVB", name1 = "ใบกำกับภาษี/แจ้งหนี้ ซื้อเชื่อ", name2 = "Purchase Tax Invoice", vat = "Y", cash = "", service = "", tax_refund = "Y", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "PURCHASE", menu = "PAYMENT", type = "Pay service", doc_group = "PM", code = "PIV", name1 = "ใบเสร็จ/ใบกำกับภาษี", name2 = "Payment Receipt Invoice", vat = "Y", cash = "", service = "", tax_refund = "Y", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "SALE", menu = "SALE", type = "Sale trading", doc_group = "ST", code = "CNS", name1 = "ใบกำกับภาษี/ลดหนี้ ขายเชื่อ", name2 = "Credit Note Sales", vat = "Y", cash = "", service = "", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "SALE", menu = "SALE", type = "Sale trading", doc_group = "ST", code = "DNS", name1 = "ใบกำกับภาษี/เพิ่มหนี้ ขายเชื่อ", name2 = "Debit  Note Sales", vat = "Y", cash = "", service = "", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "SALE", menu = "SALE", type = "Sale service", doc_group = "SS", code = "SIV", name1 = "ใบแจ้งหนี้ ขายเชื่อ(ภาษียังไม่ถึงกำหนด)", name2 = "service Invoice", vat = "N", cash = "", service = "Y", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "SALE", menu = "GL", type = "Withholding Tax", doc_group = "WH", code = "WHO", name1 = "ใบภาษีหัก ณ ที่จ่ายอื่นๆ(ถูกหักภาษี ณ ที่จ่าย)", name2 = "Withholding Tax Note-OTHER", vat = "", cash = "", service = "", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "SALE", menu = "GL", type = "Withholding Tax", doc_group = "WH", code = "WHC", name1 = "ใบภาษีหัก ณ ที่จ่าย บริษัทถูกหัก ไม่นำส่งแต่ไว้ตรวจสอบรายการ", name2 = "Withholding Tax Note-COMPANY-NOT SUBMIT-BUT FOR CHECKING", vat = "", cash = "", service = "", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "SALE", menu = "GL", type = "Withholding Tax", doc_group = "WH", code = "WHP", name1 = "ใบภาษีหัก ณ ที่จ่าย บุคคลธรรมดาถูกหัก ไม่ต้องนำส่ง", name2 = "Withholding Tax Note-PERSONAL-NOT SUBMIT", vat = "", cash = "", service = "", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "PURCHASE", menu = "GL", type = "Withholding Tax", doc_group = "WH", code = "WT5", name1 = "ใบภาษีหัก ณ ที่จ่ายกระทำการแทน บริษัท หักนิติบุคคล ยื่นภงด.53", name2 = "Represent  Withholding Tax Note-COMPANY-SUBMIT TAX RETURN FORM 53", vat = "", cash = "", service = "", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "PURCHASE", menu = "GL", type = "Withholding Tax", doc_group = "WH", code = "WT3", name1 = "ใบภาษีหัก ณ ที่จ่ายกระทำการแทน บริษัท หักบุคคลธรรมดา ยื่นภงด. 3", name2 = "Rrepesent  Withholding Tax Note-PERSONAL-SUBMIT TAX RETURN FORM 3", vat = "", cash = "", service = "", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "PURCHASE", menu = "GL", type = "Withholding Tax", doc_group = "WH", code = "PND", name1 = "ใบภาษีหัก ณ ที่จ่าย(กรณีเราเป็นผู้จ่าย/ผู้หักภาษี)", name2 = "Withholding Tax Note(Pay)", vat = "", cash = "", service = "", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "PURCHASE", menu = "GL", type = "Withholding Tax", doc_group = "WH", code = "WTO", name1 = "ใบภาษีหัก ณ ที่จ่ายอื่นๆ(หักภาษี ณ ที่จ่ายไว้)", name2 = "Withholding Tax Note-OTHER(NOT SUBMIT BUT FOR CHECKING)", vat = "", cash = "", service = "", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "PURCHASE", menu = "GL", type = "Withholding Tax", doc_group = "WH", code = "P54", name1 = "ใบภาษีหัก ณ ที่จ่าย บริษัท หักนิติบุคคลยื่น ภ.ง.ด. 54", name2 = "Withholding Tax Note-COMPANY-SUBMIT TAX RETURN FORM 54", vat = "", cash = "", service = "", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "PURCHASE", menu = "GL", type = "Withholding Tax", doc_group = "WH", code = "P53", name1 = "ใบภาษีหัก ณ ที่จ่าย บริษัท หักนิติบุคคลยื่น ภ.ง.ด. 53", name2 = "Withholding Tax Note-COMPANY-SUBMIT TAX RETURN FORM 53", vat = "", cash = "", service = "", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "PURCHASE", menu = "GL", type = "Withholding Tax", doc_group = "WH", code = "P3K", name1 = "ใบภาษีหัก ณ ที่จ่าย บริษัท หักบุคคลธรรมดายื่น ภ.ง.ด. 3ก", name2 = "Withholding Tax Note-PERSONAL-SUBMIT TAX RETURN FORM 3 k", vat = "", cash = "", service = "", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "PURCHASE", menu = "GL", type = "Withholding Tax", doc_group = "WH", code = "P2K", name1 = "ใบภาษีหัก ณ ที่จ่าย บริษัทหักบุคคลธรรมดายื่น ภ.ง.ด. 2ก", name2 = "Withholding Tax Note-PERSONAL-SUBMIT TAX RETURN FORM 2 k", vat = "", cash = "", service = "", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "PURCHASE", menu = "GL", type = "Withholding Tax", doc_group = "WH", code = "P1S", name1 = "ใบภาษีหัก ณ ที่จ่าย บริษัทหักบุคคลธรรมดายื่น ภ.ง.ด. 1ก พิเศษ", name2 = "Withholding Tax Note-PERSONAL-SUBMIT TAX RETURN FORM 1 special", vat = "", cash = "", service = "", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "PURCHASE", menu = "GL", type = "Withholding Tax", doc_group = "WH", code = "P1K", name1 = "ใบภาษีหัก ณ ที่จ่าย บริษัทหักบุคคลธรรมดายื่น ภ.ง.ด. 1ก", name2 = "Withholding Tax Note-PERSONAL-SUBMIT TAX RETURN FORM 1 k", vat = "", cash = "", service = "", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "PURCHASE", menu = "GL", type = "Withholding Tax", doc_group = "WH", code = "PN3", name1 = "ใบภาษีหัก ณ ที่จ่าย บริษัท หักบุคคลธรรมดายื่น ภ.ง.ด. 3", name2 = "Withholding Tax Note-PERSONAL-SUBMIT TAX RETURN FORM 3", vat = "", cash = "", service = "", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "PURCHASE", menu = "GL", type = "Withholding Tax", doc_group = "WH", code = "PN2", name1 = "ใบภาษีหัก ณ ที่จ่าย บริษัทหักบุคคลธรรมดายื่น ภ.ง.ด. 2", name2 = "Withholding Tax Note-PERSONAL-SUBMIT TAX RETURN FORM 2", vat = "", cash = "", service = "", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "PURCHASE", menu = "GL", type = "Withholding Tax", doc_group = "WH", code = "PN1", name1 = "ใบภาษีหัก ณ ที่จ่าย บริษัทหักบุคคลธรรมดายื่น ภ.ง.ด. 1", name2 = "Withholding Tax Note-PERSONAL-SUBMIT TAX RETURN FORM 1", vat = "", cash = "", service = "", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "GL", menu = "GL", type = "GL", doc_group = "GL", code = "VC", name1 = "ใบสำคัญการลงบัญชี", name2 = "Voucher", vat = "", cash = "", service = "", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "SALE", menu = "SALE", type = "Sale service", doc_group = "SS", code = "SCN", name1 = "ใบแจ้งหนี้/ลดหนี้ ขายเชื่อ(ภาษียังไม่ถึงกำหนด)", name2 = "service Credit Note", vat = "N", cash = "", service = "Y", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "SALE", menu = "SALE", type = "Sale service", doc_group = "SS", code = "SDN", name1 = "ใบแจ้งหนี้/เพิ่มหนี้ ขายเชื่อ(ภาษียังไม่ถึงกำหนด)", name2 = "service Debit Note", vat = "N", cash = "", service = "Y", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "SALE", menu = "RECEIPT", type = "Sale trading", doc_group = "SC", code = "RCI", name1 = "ใบกำกับภาษี/ใบเสร็จรับเงิน ขายสด", name2 = "cash Sales Tax invoice", vat = "Y", cash = "Y", service = "", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "SALE", menu = "RECEIPT", type = "Sale trading", doc_group = "SC", code = "RCN", name1 = "ใบกำกับภาษี/ลดหนี้ ขายสด", name2 = "cash Sell Credit Note", vat = "Y", cash = "Y", service = "", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "SALE", menu = "RECEIPT", type = "Sale trading", doc_group = "SC", code = "RDN", name1 = "ใบกำกับภาษี/เพิ่มหนี้ ขายสด", name2 = "cash Sell Debit Note", vat = "Y", cash = "Y", service = "", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "SALE", menu = "RECEIPT", type = "Receipt Bill", doc_group = "RL", code = "RBL", name1 = "ใบรับวางบิล", name2 = "Bill", vat = "", cash = "", service = "", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "PURCHASE", menu = "PURCHASE ORDER", type = "Order", doc_group = "PO", code = "PO", name1 = "ใบสั่งซื้อ", name2 = "Purchase Order", vat = "", cash = "", service = "", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "SALE", menu = "RECEIPT", type = "Receipt Before", doc_group = "RP", code = "RPR", name1 = "ใบเสร็จ(เพิ่มก่อนการรับเงิน)", name2 = "Perpare Receipt", vat = "", cash = "", service = "", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "SALE", menu = "RECEIPT", type = "Receipt Before", doc_group = "RP", code = "RPI", name1 = "ใบเสร็จ/ใบกำกับภาษี(พิมพ์ก่อนการรับเงิน)", name2 = "Perpare Receipt invoice", vat = "", cash = "", service = "Y", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "SALE", menu = "RECEIPT", type = "Receipt service", doc_group = "RE", code = "RIV", name1 = "ใบเสร็จ/ใบกำกับภาษี", name2 = "Receip Invoice", vat = "N", cash = "", service = "", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "SALE", menu = "RECEIPT", type = "Receipt Trading", doc_group = "RE", code = "RDP", name1 = "ใบเสร็จ/ใบกำกับภาษี เงินมัดจำรับ", name2 = "cash Sell Deposit", vat = "Y", cash = "", service = "", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "BANK", menu = "BANK", type = "Bank", doc_group = "BK", code = "CQE", name1 = "เช็ค", name2 = "Cheque", vat = "", cash = "", service = "", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "BANK", menu = "BANK", type = "Bank", doc_group = "BK", code = "PIN", name1 = "ใบนำฝาก", name2 = "Deposit slip", vat = "", cash = "", service = "", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "BANK", menu = "BANK", type = "Bank", doc_group = "CQ", code = "TRF", name1 = "ใบโอนเงินระหว่างธนาคาร", name2 = "Bank Transfer", vat = "", cash = "", service = "", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "SALE", menu = "RECEIPT", type = "Receipt trading", doc_group = "RE", code = "RRE", name1 = "ใบเสร็จรับเงิน", name2 = "Receipt", vat = "N", cash = "Y", service = "Y", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            doctypes.Add(new DocType() { system = "PURCHASE", menu = "PURCHASE ORDER", type = "Order", doc_group = "PO", code = "PR", name1 = "ใบขอซื้อ", name2 = "Purchase Request", vat = "Y", cash = "", service = "", tax_refund = "", createatutc = DateTime.Now, updateatutc = DateTime.Now });
            try
            {
                context.AddRange(doctypes.ToArray());
                context.SaveChanges();
            }
            catch (Exception ex)
            {
                Console.WriteLine($" exception : {ex}");
            }

        }
    }
}
